### ISSUE TITLE
[1.12.2]Compatibility with Ichuns world portal mods?

### ISSUE THREAD

**Issue by Trinsdar** [sp614x/optifine#1019]
Could you make optifine work with mods that use ichun's world portals, eg. portal gun and GLASS(General Layman's Aesthetic Spying Screen )? currently it causes there to be only a blank blue screen.
Here is an image: https://imgur.com/a/vubOM

**Comment by sp614x** [comment]
I have no idea how the custom portals work, so it is not possible to fix them.

**Comment by sp614x** [comment]
Is this with shaders ON or OFF?

**Comment by Trinsdar** [comment]
neither of those worked. Here is a the fml-client latest log if you think it might help: https://pastebin.com/hSzCg0Vm. Mabye @iChun could help?

**Comment by iChun** [comment]
There's code in there just to make sure it doesn't crash with Optifine when it did before. Optifine modifies the RenderChunk class in a way that breaks vanilla compatibility.

**Comment by sp614x** [comment]
OptiFine modifies significantly the RenderChunk class.

**Comment by gatoborrachon** [comment]
mmm, well, i don't want to necro a dead issue, but i guess that this and render issues with [G.L.A.S.S.](https://www.curseforge.com/minecraft/mc-mods/general-laymans-aesthetic-spying-screen-glass) will never be fixed right?

**Comment by Tada201** [comment]
Some how I managed to get the G.L.A.S.S mod to work with Optifine 1.12.2
![2021-09-05_18 08 47](https://user-images.githubusercontent.com/90136516/132124622-ee1f6c59-d6ae-49d8-8aec-feabeb3a8b17.png)

**Comment by gatoborrachon** [comment]
@Tada201 you may be able to reproduce it? maybe is a certain configuration inside your optionsof.txt file?

**Comment by Tada201** [comment]
@gatoborrachon Actually at first I met the same problem mentioned above but I was only meddling with the settings in the game's menu that is available by the Optifine mod then I flipped the lever on the glass projector. Log out and and login somehow it fixes it 
but I am not sure how will I be able to create that situation.

**Comment by Tada201** [comment]
I think some of this issue is because of the Fast Renderer it uses an algorithm which may thought that the GLASS mod was the issue and also in the description it also said "may inflict with some mod" so that maybe the reason. Also at the time I upload the picture mentioned above:
> Some how I managed to get the G.L.A.S.S mod to work with Optifine 1.12.2
> ![2021-09-05_18 08 47](https://user-images.githubusercontent.com/90136516/132124622-ee1f6c59-d6ae-49d8-8aec-feabeb3a8b17.png)

I think that by some miracle that I messed up the algorithm that is use for the Fast Renderer that it accepts the GLASS block to render properly.

**Comment by gatoborrachon** [comment]
> Update: No wait it just makes the game a garbled mess

yeah, that's what i was thinking, i disabled fast render too and didn't work, so if you managed to make it work, then something was broken

**Comment by Tada201** [comment]
Well I still don't know how I tricked the Fast renderer AI to believe the GLASS block to render properly though but I can conclude some findings
1. Reset all video settings 
2. Turn on GLASS projector
3. Game crashes
4. Due to resetting the game settings Fast Renderer was set to OFF
5. Re-Download the entire 1.12.2 library including the  Forge and Optifine mod
6. Enter the game it somehow function all right without Fast Renderer being on and the Glass projector is fully functional
7. I tried mixing the order from 1-6 multiple times and somehow managed to recreate the problem but after reset video settings again and re-download the libraries again the problem is gone.

Note: I was also using Webdisplay mod but the result is in conclusive and still lacking any true method to solve this problem and I am not a programmer was just messing around when I found this problem while preparing for a video.
