### ISSUE TITLE
Composite alpha blending.

### ISSUE THREAD

**Issue by VignetteCoeff** [sp614x/optifine#1029]
Composites have alpha blending disabled by default, but I could think of a few cases where it'd be useful to enable it, specifically for reusing buffers and not clearing them. I propose adding something similar to this to turn alpha blending on or off, this would be on a per-program basis, including gbuffer programs. This would be in the shaders.properties file.

buffer.file.blending=blending mode

**Comment by jcm2606** [comment]
To give another use case, this would allow shaders to send data down the alpha channel from the gbuffers progams. The way that blending is set up now, is all buffers in the gbuffers programs use alpha blending, with the first buffer specified under the DRAWBUFFERS comment being a "dominant buffer", which requires an alpha > ~0.1, otherwise the entire fragment is automatically discarded.

This constant alpha blending means we have to ignore the alpha and only send data down the red, green and blue channels, which inflates buffer usage since we don't have enough space in a single buffer to store more than 12 8-bit values at once using 4x8 encoding (packs 4 8-bit floats into a single 32-bit float channel). That seems like a lot, but factor in that we need to store things like albedo (3 floats), normals (3 floats), lightmaps (2 floats, possibly 4 floats if you want separate directional lightmaps), a material mask (1 float), roughness (1 float), metallic/f0 (1 float), emission (1 float), pourosity (1 float), parallax shadow (1 float), and more things. For the average shader, you could fit most of these into 2 RGB32F buffers, but for a shader like Continuum or Spectrum, there's simply too much data to reliably pass around. Then factor in shaders that do "dual deferred", where they have *2* sets of this data available, one for opaque pixels, and one for transparent pixels, which allows for better handling of transparency (though with the new deferred programs, the need for this isn't as prevalent, some shaders will still use this system since it is so reliable), so these shaders will actually use *4* RGB32F buffers in total, *just* for gbuffers data.

If we could set blending to always overwrite the existing contents of the buffer, akin to how the composite shader currently functions, then that would open up the alpha channel, which gives us 4 additional 8-bit floats to work with, when using 4x8 encoding. That's a decent amount, and would allow some packs to open up an entire buffer or two.

**Comment by zombye** [comment]
Here's what the actual functionality I would expect to be implemented here:

```
<program>.blending.source.rgb=<operation applied to source rgb/color>
<program>.blending.source.alpha=<operation applied to source alpha>
<program>.blending.destination.rgb=<operation applied to destination rgb/color>
<program>.blending.destination.alpha=<operation applied to destination alpha>
<program>.usealphatest=<true/false>
```

Blending cannot be configured separately for individual buffers until OpenGL 4.0, at least not without extensions (see [glBlendFunc](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendFunc.xhtml) and [glBlendFuncSeparate](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendFuncSeparate.xhtml)), which is why I am not including anything about setting them per-buffer.

The option for alpha testing doesn't really need to be per-program, if it's just one setting controlling it for all programs where alpha testing is currently done that would be fine by me.

Could also include setting the blend equation, but I'm not sure how useful that would be. Currently it's adding source and destination after the blending operations have been applied to them, which is what you'd normally expect, but it could also be set to take the max of the two, the min of the two, or subtract them (in either order).

**Comment by sp614x** [comment]
A. For composite programs - enable blending

Blending mixes the output fragment color with the current write buffer color. 

With ping-pong buffers the composite write buffer usually has the color from 2 composite programs ago. It may happen to be identical to the read buffer if `composite_last` have been activated.

Generally the color of the composite write buffer is not defined and the composite program is expected to fully overwrite it.

B. For gbuffers

Blending is disabled for solid/cutout terrain and enabled for water/translucent. 

It is possible to disable blending and alpha testing per gbuffers program. In this case the shaders should take care to discard and blend fragments as needed.

**Comment by sp614x** [comment]
It looks like blend can be enabled/disabled per write buffer in GL30:
https://www.khronos.org/opengl/wiki/Blending#Blend_enabling
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glEnable.xhtml

Blend function per write buffer needs at least GL40:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendFunc.xhtml

**Comment by sp614x** [comment]
Blending could be configured like:
```
blend.<program>=<off | src dst | src dst srcA dstA>
alphafunc.<program>=<off | func | func ref>
```
for example:
```
blend.gbuffers_water=SRC_ALPHA ONE_MINUS_SRC_ALPHA ZERO ONE
alphafunc.gbuffers_water=GREATER 0.1
```
enable/disable blend per write buffer
```
blend.<program>.<buffer>=<on | off>
```

**Comment by sp614x** [comment]
Trace of blend state per frame: https://pastebin.com/2LGxYqCi

**Comment by sp614x** [comment]
alphaTest.gbuffers_water=LESS 0.5

![image](https://user-images.githubusercontent.com/16635441/34386103-4e9192c8-eb27-11e7-8b94-6e9b0060f4d3.png)

alphaTest.gbuffers_water=GREATER 0.5

![image](https://user-images.githubusercontent.com/16635441/34386114-6b670d6a-eb27-11e7-83da-8484ef8c974b.png)

alphaTest.gbuffers_water=off

![image](https://user-images.githubusercontent.com/16635441/34386139-823deb3a-eb27-11e7-8a6e-455a8c636c47.png)

**Comment by sp614x** [comment]
blend.gbuffers_water=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ZERO

![image](https://user-images.githubusercontent.com/16635441/34386374-97248e4a-eb28-11e7-8136-d1937f4c98e6.png)

blend.gbuffers_water=off

![image](https://user-images.githubusercontent.com/16635441/34386410-cbf089d0-eb28-11e7-84a7-7c5caf0ff294.png)

blend.gbuffers_water=SRC_ALPHA SRC_ALPHA ONE ONE

![image](https://user-images.githubusercontent.com/16635441/34386560-8deb2b30-eb29-11e7-843b-75455e6243f4.png)

blend.gbuffers_water=ONE ONE ONE ONE

![image](https://user-images.githubusercontent.com/16635441/34386577-aabeff34-eb29-11e7-8d77-2a23642f159d.png)

**Comment by sp614x** [comment]
Updated preview C8 for 1.12.2
- added alpha test and blend mode per program
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L352

**Comment by sp614x** [comment]
Blend equation and blend color could also be added if needed.
