### ISSUE TITLE
CTM crash with Botania floating flower

### ISSUE THREAD

**Issue by 0nepeop1e** [sp614x/optifine#1037]
Optifine tyring to connect textures of blocks with botania floating flower and causing NullPointerException.
i believe it might happen to other mod if any blocks which its textures cannot be connected.
[Crash Log](https://gist.github.com/0nepeop1e/420b3e727aa7fe20957b6ab2fd9e5a5a)

This issue can be avoid by turning connected texture features off, but i still hope this issue can be fixed.
Suggestion: may add a blocks blacklist for the features, or maybe just add a null check there

**Comment by sp614x** [comment]
the crash is inside Botania:
```
java.lang.NullPointerException: Tesselating block model
	at vazkii.botania.client.model.FloatingFlowerModel.getModel(FloatingFlowerModel.java:120)
        at vazkii.botania.client.model.FloatingFlowerModel.func_188616_a(FloatingFlowerModel.java:101)
```
the crash is here: https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/client/model/FloatingFlowerModel.java#L120
the real problem is probably here: https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/client/model/FloatingFlowerModel.java#L95
looks like the `BotaniaStateProps.SUBTILE_ID` is missing from the block state.

**Comment by sp614x** [comment]
And this is probably why the property value is missing: https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/client/renderer/BlockRendererDispatcher.java.patch#L27

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2 
- fixed crash with Botania and CTM
