### ISSUE TITLE
Game Crashed While Mining [1.10.2]

### ISSUE THREAD

**Issue by janagyjr** [sp614x/optifine#1048]
No crash log, but [fml log](https://gist.github.com/anonymous/6be8b4bb123f3db181aed82c2a79aecf) seems to point to optifine barfing at some point (and quite often) about missing mod textures, especially of interest seems to be line 5430

Referencing issue 

MC 1.10.2
Optifine: HD U E3
Forge: 2511

https://github.com/janagyjr/chill-pack-2/issues/2 is original issue filed

**Comment by sp614x** [comment]
Line 5430 is complaining that MC can't load the model for `modularforcefieldsystem:block/forceField` because the model JSON is missing (modularforcefieldsystem:models/block/forceField.json):
https://gist.github.com/anonymous/6be8b4bb123f3db181aed82c2a79aecf#file-chill-pack-1-10-2-alfa-crash-L5453

There are no OptiFine related errors in the log. 
There are many other errors (broken jsons, missing textures, etc), but it is hard to tell if they are critical.

If the game crashes without crash report, then it is usually caused by a graphics driver crash. Updating the graphics drivers, reducing render distance, enabling/disabling VBO could help.
