### ISSUE TITLE
Optifine 1.12.2 C7 sources

### ISSUE THREAD

**Issue by Wyn-Price** [sp614x/optifine#1106]
This isn't a bug, just to ask where the C7 sources are. If you could ask @Hexeption to release them or point me in the direction of where they are. I need the C7 sources as something in my mod broke with C7, and I have no way of fixing without the sources

**Comment by SetantaLP** [comment]
There is no official download for the sources because they contain a lot of minecraft classes. So I think there are only two ways to get the sources:
1. Copy all files you can find in the of.jar form the libraries-folder into the normal minecraft jar and decompile it with the mcp.
2. Use [simpledeobf](https://github.com/octarine-noise/simpledeobf) to create a deobfuscated jar and decompile this jar with fernflower.
These ways don't give the original source code (because some things are removed/changed by the compiler) but at least source code that works in the same way, which should be enough for finding bugs.

**Comment by sp614x** [comment]
@SetantaLP is correct.
