### ISSUE TITLE
Installing Optifine without installing the JDK on macOS

### ISSUE THREAD

**Issue by noclasoseh** [sp614x/optifine#1110]
When I try to install Optifine on macOS, I get a `.jar` file which I need to run. When I double click it, I get the following error:

> To use the “java -jar OptiFine_1.12.2_HD_U_C7.jar” command-line tool you need to install a JDK.

 I don't want to install the huge JDK in order to install Optifine. As far as I can tell, Optifine doesn't *depend* on the JDK to run; it's only needed to install it.

Would it be possible for me to install Optifine "manually" (as in the old days when we needed to drag files into `minecraft.jar`)?

**Comment by xCuri0** [comment]
@noclasoseh you can try running it with the Java runtime included with Minecraft

**Comment by xCuri0** [comment]
or you can install forge and drop the jar into forge

**Comment by sp614x** [comment]
OptiFine can't be installed without a JDK/JRE. There is some Java code that needs to run in order to create the runtime classes. Manually putting it in the minecraft.jar or the modern equivalent of adding it to the launcher class path is also not possible.
You should be able to run it using the java runtime bundled with Minecraft.
