### ISSUE TITLE
[Shaders] Scene voxelization support

### ISSUE THREAD

**Issue by bobcao3** [sp614x/optifine#1120]
So many shaders developers want a proper voxelization support, and the basic idea is to load the scene data into a texture3d.

Well there are a lot of different people want different voxelize methods, so I suggest a configurable format system. It's like defining struct in C or GLSL. Different formats can specify the stride of each voxel (binary alignment, 1 byte align, 16bits align, and ultimately 16 byte align - RGBA32I). And shader can specify how each data can be aligned into each voxel, and optifine can provide sets of standard data format.

e.g.
is_opaque  1bit
is_transparent 1bit
is_emmisive 1bit
entity_id 8bit
sky_light_level 4bit
torch_light_level 4bit
average_texture_color 8bit*3

and the shader can speficy a format that aligns to 4 bytes in a RGBA8I format, with this specified format for one voxel:
| ------------------------------------------------------------- | -------- |
| is_opaque is_transparent is_emmisive 0 sky_light_level    | color    |
| 1 byte                                                                                | 3 bytes |

With support of this, a lot more fantastic features can be implemented. Voxelized GI, path tracing, rough world space reflections, IBL lighting, skylight, colored block light, ...
This will make minecraft shaders become "Crysis"

**Comment by DethRaid** [comment]
If we're getting a voxel structure for raytracing, I would like to get a signed distance field. I'm thinking one channel of a 3d texture could be the signed distance, and another could be a material id

**Comment by robobo1221** [comment]
We need this!

**Comment by SergeantSarcasm** [comment]
yes we need pls

**Comment by jcm2606** [comment]
Need dis liek soos.

**Comment by DethRaid** [comment]
I said I'd expand more when I get home so here we are.

The way I see it, the biggest advantage of having access to the voxelized world in shaders is better raytracing. We could raytrace against a signed distance field, or against a bounding volume hierarchy like an octree or a  or something.

At first I wanted a SDF, but thinking about it now I think an octree would be better... It would be best for spx614 and some raytracing dudes to test each out for performance and usability, but I think a BHV would win for speed and it's not very hard to use.

I'd use spherical volumes in the BVH, since spheres are super easy to test for collision against. Each model (a fence, block, whatevs) would be a collection of faces, which could have a `vec3` for their center and another one for their normal. You'd all need an extent along the plane's face, so we have eight floats per face. You wouldn't need to upload every face of every block, just the ones that are visible today.

I'd also want each face to have a material ID. This ID would be an index into an array of materials. Each material would be a block ID and the min/max coordinates of that block's textures in the texture atlases. I'm assuming that the color, normal, and data textures are all at the same uv coordinates in their respective atlases.

In this system I'd have no need for Minecraft's lighting information, or for chunk meshes. I'd at least want an option to disable those so the chunk VBOs are never uploaded to the GPU and that memory is saved

Entities could be handled the same way as chunks. Their faces would just have to be updated as the entity animates. 

The big problem here as I see is weird things, like the selection box. Not sure how to handle that.

Anywho, that's what I think

**Comment by sp614x** [comment]
So far these are realistic:
- uploading a subset of the world data in a 3D texture
- the texture will be organized in W x L x 16 regions, each corresponding to one 16x16x16 chunk
- only single regions would be updated when the corresponding chunks are loaded/updated
- the texture would not be centered on the player
- the chunk X/Z coordinates would wrap around, so `U = X % W` and `V = Z % L` similar to the `ViewFrustum` class.
- the texture format would be configurable, for example `GL_R16UI` 
- the format of each channel should be configurable, for example: 1bit opaque, 1bit full cube, 4bit sun light, 4bit torch light

It is not clear how the GPUs would perform with bitwise operations.

These seem to be NOT realistic:
- signed distance fields - too complex to calculate in real time
- sub-block accuracy - fence model
- octree - not sure how this should be organized
- emissive property - there is no `emissive` property for blocks, only torch light levels 
- transparent property - the render layer may be checked, but there is no guarantee that the texture is transparent
- average texture color - some cube models use multiple textures (grass sides)

@DethRaid looks like you want OF to upload the raw models and let the shaders do the rendering. This would be overly complicated. There are also some things that don't have models at all (leash, fishing line, etc). Mod compatibility would be impossible.

**Comment by DethRaid** [comment]
Are you sure you couldn't do a signed distance field? Chunks don't change super often, and you could maybe run an async task that updates every second or so to not lag out the game

The raw models are currently in vram... Maybe you could just expose that, and some read/write memory, and a shader could build the bvh?

**Comment by sp614x** [comment]
There is an SDF implementation with linear time for 2D: http://www.codersnotes.com/notes/signed-distance-fields/. The world would need a 3D SDF, so it would be more complex. 

The models are in VRAM, but only when VBOs are enabled they can be accessed by shaders. The default is fixed (black box) display lists. Not sure how they can be exposed to shaders.

**Comment by SergeantSarcasm** [comment]
As far as average texture color goes I'm sure everyone would be satisfied with the average color being gathered by just the top texture on every block

**Comment by DethRaid** [comment]
I'd prefer to have one sdf layer for opaque blocks and one for transparents, but if that uses too much memory then I guess just opaque would be good.

I'd like to the the sdf at greater resolution than the world, maybe like eight or twenty seven sdf voxels per block? If that's too much vram usage then ignoring fences might be alright, although it would be cool to be able to toggle that.

I don't know if a way to get vertex data from an OpenGL display list and I'm fine with that. I would like to have shaders able to force Minecraft to use vbos so that the vbo is garuanteed to be available. Is there any advantage to using display lists other than compatibility with super low end systems that might not support shaders anyway?

**Comment by sp614x** [comment]
The 3D texture size:

One cubic chunk has 16 x 16 x 16 = 4096 blocks. Render distance 32 has 65 x 65 x 16 = 67600 cubic chunks. 
With 1 bit per block (opaque/empty), the texture would be 4096 x 67600 / 8 = 32 MB.
With 8 bits per block (sky + block light), the texture would be 32 * 8 = 256 MB.

**Comment by sp614x** [comment]
Is this relevant #791?

**Comment by DethRaid** [comment]
I think so. My primary motivation for image load store was scene voxelization

**Comment by bobcao3** [comment]
As #791 will be a more general and more effective solution, this issue should really be closed.
