### ISSUE TITLE
Allow to change size of RenderChunk (with proof of concept linked)

### ISSUE THREAD

**Issue by Barteks2x** [sp614x/optifine#1128]
Here is a cubic chunks PR that implements it, also compatible with OptiFine: https://github.com/OpenCubicChunks/CubicChunks/pull/325

It's very likely to be mostly compatible with mods without breaking anything, and as long as all render updates are processed off the main thread, it offers a nice performance improvement.

**Comment by sp614x** [comment]
I have tested the effects on bigger chunks on render performance and generally it does not have a noticeable effect. The FPS may increase a little, but not enough to justify the complexity of the changes. 

On the other hand increasing the RenderChunk size would SIGNIFICANTLY increase the chunk update lag (4x). Instead of updating one chunk the game will always have to update 4 (current) chunks. Placing and removing blocks, dynamic lights, redstone updates, etc. are going to become much more laggy.

The Forge workaround to force all updates on the background thread is a hack which adds significant block lag on slower systems. There would be a visible delay between placing a block and this block appearing on the screen. The same when removing blocks.

The current RenderChunk size is a nice balance between render speed (FPS) and update speed (terrain updates).

**Comment by Barteks2x** [comment]
I'm pretty sure there is a way to reduce the block lag by using many 16x16x16 VBOs/display lists rendered in one draw call for each RenderChunk but that would involve more complex changes and I would have to test that it's actually possible.

Based on tests done by @Foghrye4 it seems that it does noticably improve FPS at least on some systems. That was before fixing VisGraph so this may not really be the case, but seeing that inly rarely some chunks have been missing, the FPS increase seems noticable enough (20->30fps).

**Comment by sp614x** [comment]
The VBO fix would only work if VBO is supported and enabled. There are many older drivers that have problems with VBO (some intel drivers just crash). 

The idea to render the terrain with less OpenGL calls have been existing for a veeeery long time. This was the core functionality of the option FastRender up to OptiFine for 1.7.10. In OptiFine for 1.8 it was discontinued as it offered very minimal FPS increase but suffered from compatibility issues with many mods. 

Recently, when render distance 64 chunks was added, I experimented again with decreasing the render calls but the effect was again very small to justify the added complexity and potential mod conflicts. The experimental renderer is capable of rendering the whole visible terrain with a single call and it gives a pretty good estimation of the possible FPS gains.

**Comment by sp614x** [comment]
Tested default rendering (one call per cubic chunk) and optimized rendering (render all terrain with 1 call).
Using Intel HD graphics 2500, render distance 16 chunks.

Window 700 x 400: default 112 FPS, optimized 122 FPS. 
Fullscreen 1680 x 1050: default 65 FPS, optimized 68 FPS. 

The optimized rendering has incorrect translucent sorting, when fixed the diference should be even smaller.

The weaker GPUs (integrated) are mostly vertex/fragment limited, the number of draw calls has minimal effect on the FPS. On a dedicated GPU the difference may be bigger, but dedicated GPUs generally do not have FPS problems.

Heavily modded minecraft may see a bigger difference if the GPU upload bandwidth is saturated. In this case disabling the terrain animations may be much more effective.
