### ISSUE TITLE
Include Error reporting

### ISSUE THREAD

**Issue by dotModded** [sp614x/optifine#114]
I've noticed that when using includes tracking down errors can be quite annoying, maybe some pre-processor magic to figure out what line in what file the error is happening, if you know the lengths of each file and where it's included it should be fairly simple to figure out where in what file the error is coming from.

**Comment by sp614x** [comment]
The errors are generated by the driver compiler and they are reported in a driver specific format.
If you start MC with argument "-Dshaders.debug.save=true" then the final shaders will be saved in "shaderpacks/debug". They have the correct line numbers and can be used for error tracking.

**Comment by dotModded** [comment]
Yeah I knew about that, you could intercept the errors maybe but just a thought that make make include a bit easier to use

**Comment by sp614x** [comment]
Each driver vendor uses its own format for the error messages, this may also be driver version or context dependant. Finding and recognizing all error format variants is too complex.
Using the final generated shaders shoud be better because this is what the driver really compiles. Includes are added without any checks so open brackets or missing/double defines may produce strange results.
Adding "// Start include XYZ" and "// End include XYZ" as first and last lines in the included file can be used to track from which include file the lines come.

**Comment by dotModded** [comment]
Already doing all of that too xD but makes senseverything, if only this was vulkan and you could write your own error reporting.
