### ISSUE TITLE
Shaders cant render Computercraft Monitors

### ISSUE THREAD

**Issue by BananeMan1** [sp614x/optifine#1237]
Hey,
There is a issue with ComputerCraft's monitors after applying shaders (internals and without works)
[https://prnt.sc/ii0akz](url)
![Bug](https://image.prntscr.com/image/Cxz47QYgSaWQ51KQfR12Vg.png "Bug")

Thanks !
(Note: there is no log)

**Comment by ferreusveritas** [comment]
I'm working on a fix for this and so far what I've found is that CC uses GLDisplayLists to build displays made up of quads with alphanumeric character textures.  It can efficiently re-render the monitor entity by calling the display list.  The display list is rebuilt only when the monitor tile entity is updated with new text information.  I'm think the problem is that Optifine can't get anything useful from a displaylist so it goes unrendered.  I've tested this theory by disabling the displaylist and letting it build the entire display every frame.  This method renders perfectly as you would expect but it is also slow.
  I'm sure optifine needs the quads to be in a sort of VBO to do it's magic.  I will need to cache the display in a VBO instead of a display list to get the performance back to normal.  My question is: What is the best practice for making cached VBOs that Optifine would be hungry for?  Thanks!

**Comment by sp614x** [comment]
Entities (mobs) use cached display lists and they work just fine with shaders.
This may be caused by some special rendering mode (glTexEnv?), using directly GL11 instead of GlStateManager or something similar.

**Comment by ferreusveritas** [comment]
You're right.  Like I said, I was mistaken.  I think I figured it out though.  The main problem is that the Monitor TileEntity keeps track of the last animation frame it rendered on to prevent it from being rendered twice(I have no idea why that's necessary).  The TESR renders the Monitor once during the shadersmod.client.ShadersRender.renderShadowMap pass.  When it renders the second pass with net.minecraft.client.renderer.EntityRenderer.renderWorldPass the renderer is convinced that it already rendered during that frame of animation and prematurely returns without drawing anything.
The other problem is that I had to add OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 0, 0xFF) to the renderer before it draws anything in order for the display to not be black.
After those two conditions are met it seems to draw just fine with Shaders enabled, internal, or off.

**Comment by sp614x** [comment]
The lightmap texture coordinates problem may be related to these: https://github.com/sp614x/optifine/issues/1305, https://github.com/sp614x/optifine/issues/631, https://github.com/sp614x/optifine/issues/302, https://github.com/sp614x/optifine/issues/417
