### ISSUE TITLE
[1.12.2][Forge] Cannot create or load a world with all Optifine versions for 1.12.2

### ISSUE THREAD

**Issue by BenSchwing1337** [sp614x/optifine#1261]
i tried to load or create a world with all the optifine versions that are currently available for Minecraft 1.12.2

Forge version14.23.2.2624
[crash-2018-03-03_18.19.11-server.txt](https://github.com/sp614x/optifine/files/1777764/crash-2018-03-03_18.19.11-server.txt)

**Comment by sp614x** [comment]
The crash complains about not being able to load "NetHandlerPlayServer". OptiFine is not changing anything related to NetHandlerPlayServer. Doesn't seem to be caused by OptiFine.
Does the crash happen with only Forge and OptiFine?
If it crashes only with other mods, which mod is the one that crashes when combined with OptiFine?

**Comment by FrancisDaPugtato** [comment]
I can't replicate this.  (Optifine 1.12.2 D1 with same Forge Version, Optifine is the only other mod installed other than Forge on.)

**Comment by sp614x** [comment]
To quickly find the problematic mod:
1. Remove half of the mods
2. If the problem appears keep the mods, otherwise use the removed half of the mods
3. Continue with 1. until only one mod is left
