### ISSUE TITLE
[1.7.10-E7] Force out the shadersmod integration!!! Crash with fastcraft (no fastcraft update will be made!!!)

### ISSUE THREAD

**Issue by chaos234** [sp614x/optifine#1347]
Referencing to #527 it can't be that now a shadermod was included which causes with fastcraft a crash: https://paste.ee/p/h6Gjz

It makes no sense to implement a shadermod which then forces the author of fastcraft (player) to cut down it's own mod because of stupidity of YOU!

I never ever will use the new version as long as it contains a shadermod which isn't nessecary because such a mod exists externally. This means that I vote for a removel of the sahdermod so that it is compatible to fastcraft's original design again without losing any performance benefits from it.

Hint: Instead of causing problems to other mod authors mods you should check compatibality and if smth. causes a problem or is reported as it then remove the pice of code/feature, which caused it. And if I would be the auther of fastcraft, I wouldn't have released a fix for this ... I would have said to you: "Remove the useless shadersupport. It is your fault and not my ones."

Means in fact that I'll report this bug at any time, as long as you don't releas a version without this crash.
And other version besides HD U D4 are causing this horrible smeltery problem, where ghost blocks are created if smth. is in the smeltery. As long as this isn't fixed too I am either stuck at D4 or I'll kick out OF compleatly but I'll never support such a development!

And yes, that is a bug report and (hard) critic in one together. Your reaction on this will show me, if you can take it, or not.

**Comment by realjackasterisk** [comment]
You might be surprised to know you *aren't* the only person in the entire world who uses Optifine. Lots of other people use shaders too. How do you think they'd feel if Optifine's shader mod support was completely dropped because ***you*** had an issue with some other mod?

**Comment by DethRaid** [comment]
How did you determine that the shadersmod code is causing the TextureMap class to be deleted? That's a super long mod list you have there

**Comment by Strum355** [comment]
I would bet money that more people use optifine (and shaders) than use fastcraft, so the author of fastcraft has more of an incentive to adapt to optifine than vice versa.  
tbh this whole issue is pretty laughable, not just for the fact that you have absolutely 0 composure.

**Comment by Builderb0y** [comment]
This issue has already been fixed on fastcraft's side. Update to 1.25.

> It makes no sense to implement a shadermod which then forces the author of fastcraft (player) to cut down it's own mod because of stupidity of YOU!

> the shaders mod isn't nessecary because such a mod exists externally.

The original developer of the shaders mod has stopped developing it entirely, and all public releases are massively outdated. Most modern shaders don't work at all with it anymore. If optifine hadn't taken over its development, shaders might not still be around today.

> Hint: Instead of causing problems to other mod authors mods you should check compatibality and if smth. causes a problem or is reported as it then remove the pice of code/feature, which caused it.

That's not even close to how mod development works. Ideally the piece of code should be fixed to not cause problems instead of being outright removed, but this bug isn't even on optifine's side. it's on fastcraft's side.

> And if I would be the auther of fastcraft, I wouldn't have released a fix for this ... I would have said to you: "Remove the useless shadersupport. It is your fault and not my ones."

Well you're not. And you're also wrong. When 2 mods have conflicts with each other, it's neither of their "faults". Both mod developers need to work together in order to find a solution. I guess it's a good thing then that you're NOT the developer of fastcraft, because you're very clearly incapable of working with other people.

> Means in fact that I'll report this bug at any time, as long as you don't releas a version without this crash.

I take it this means you'll be deleting this issue then, because it's already been fixed?

> And other version besides HD U D4 are causing this horrible smeltery problem, where ghost blocks are created if smth. is in the smeltery.

That sounds like a tinker's construct issue. If I recall correctly, it was quite buggy back in 1.7. Maybe you should complain to them and see how willing they are to back-port newer versions. /s

> As long as this isn't fixed too I am either stuck at D4 or I'll kick out OF compleatly but I'll never support such a development!

Oh no, a single person doesn't have optifine installed! What ever will we do?! Hint: if you didn't donate to optifine, then weren't "supporting" it to begin with.

> And yes, that is a bug report and (hard) critic in one together. Your reaction on this will show me, if you can take it, or not.

This isn't criticism. This is you throwing a temper tantrum whenever something doesn't go exactly your way. If this is how you treat people who still take the time to support software that's [nearly 4 years out of date](http://www.howoldisminecraft1710.today/), then that's a reflection of YOUR personality, not sp614x's. The only thing this shows is how much of a toddler you are.

**Comment by SergeantSarcasm** [comment]
this nigga dumb

**Comment by sp614x** [comment]
Latest Fastcraft version 1.25 should work.
It was released 3 months ago, so not really new.
