### ISSUE TITLE
Donate and still havent received the confirmation email or the cape

### ISSUE THREAD

**Issue by Cain69** [sp614x/optifine#1349]
Regards.

Last night donate 10 dolars so my child get a optifine cape and still dont receive the confirmation email. Check my bank and the money was transfered, Who help me please

Kain

**Comment by techied** [comment]
Hello,

If you still haven't received your cape or confirmation email, I'd urge you to contact optifinex@gmail.com as described here: https://optifine.net/refund

Thank you

**Comment by Cain69** [comment]
Thanks for the comment. I sent the email Saturday night and still didn´t receive any response yet

**Comment by mindforger** [comment]
>Thanks for the comment. I sent the email Saturday night and still didn´t receive any response yet

well it's been a weekend, have a bit patience please 
it's not an online shop, you just donated

**Comment by Cain69** [comment]
Agreed but nobody tell you that and a little guy (my son) asking eery hour about that. Especially when he see youtuber videos that it's automatically xD

**Comment by Cain69** [comment]
Hi, any new folks?

**Comment by techied** [comment]
If you still haven't received your cape, ensure you have installed OptiFine on your computer and have selected it by clicking the arrow next to the play box. After that, ensure that the cape is turned on in Options -> Skin Customization

If your cape still doesn't show up, you can file a Resolution Center report if you paid with PayPal here: https://www.paypal.com/signin/?returnUri=https%3A%2F%2Fwww.paypal.com%2Fcgi-bin%2Fwebscr%3Fcmd%3D_complaint-view

**Comment by Cain69** [comment]
Hello. I just check step by step and still no cape.


I use PaymentWall->Debit card (banco de chile)


I'm not looking for refund so how we proceed?


Regards


Heinrich (Kain)

My son username is Heiden69


________________________________
De: techied <notifications@github.com>
Enviado: lunes, 09 de abril de 2018 21:36
Para: sp614x/optifine
Cc: Cain69; Author
Asunto: Re: [sp614x/optifine] Donate and still havent received the confirmation email or the cape (#1349)


If you still haven't received your cape, ensure you have installed OptiFine on your computer and have selected it by clicking the arrow next to the play box. After that, ensure that the cape is turned on in Options -> Skin Customization

If your cape still doesn't show up, you can file a Resolution Center report if you paid with PayPal here: https://www.paypal.com/signin/?returnUri=https%3A%2F%2Fwww.paypal.com%2Fcgi-bin%2Fwebscr%3Fcmd%3D_complaint-view

**Comment by sp614x** [comment]
You should contact the payment Paymentwall. 
Only they can check if there is some problem with the payment.

**Comment by Cain69** [comment]
So... it's easier close the topic instead of trying to resolve the issue?????? Lack of respect with people tha donate....

**Comment by mindforger** [comment]
Don't take it personally, this is git hub, a place to solve technical issues not financial issues and especially a donatiomt has nothig to do with technical support ... also the dev is doing this more or less for free and you have shown not very much patientnce until now, you are not a customer to him or have any claims so please be nicer or concider where you are ... To give you a picture, the topic kindof reads like someone visiting Coca Cola factory to argue about a Restaurant serving the coke late because the delivery truck had been delayed

**Comment by Cain69** [comment]
My friend, It's simple than that. See what i see.. I donate so my kids have his cape... Web page frezze after payment so didn't receive the confirmation email but the money was transfered ok from ,my bank so i sent an email explaining this and attach the voucher and wait for your response.... messages between us asking for help and the very next thing i read it's... ask for refund and closed the post. Thats its read as lack of respect not as... please wait longer

Heinrich

**Comment by sp614x** [comment]
The issue was closed as only the payment provider (Paymentwall ) can check if there is any problem with the payment. The payment may be blocked or there may be a problem with the card or with the bank. The payment may be automatically refunded if there is a problem with it. This can only be checked by Paymentwall. When the payment is OK Paymentwall sends a notification to the OptiFine server to activate the cape. There is no notification for username "Heiden69" yet.
You should contact Paymentwall directly and provide all relevant information. Please do not post sensitive information (transaction codes, etc) on this public forum as everyone can see it.

**Comment by Cain69** [comment]
Thanks, i already did it sending the informattion of the transaction

Regards
