### ISSUE TITLE
Name-based CTM and Tile Entity textures disappear when logging back in to multiplayer.

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#1420]
(I haven't been able to test this with all renameable blocks and tile entities yet. Just the furnace and chest.)

When renameable blocks or tile entities are given a custom texture based on display name, the textures reset to the default ones once the player leaves the server and re-connects. Breaking the block and placing it back down again fixes the issue temporarily until the user disconnects again.

**Comment by SetantaLP** [comment]
As far as I know this is an issue, that can't be fixed in multiplayer, because in the normal client the name never used, so the server doesn't send it to the client. So the only way to get the name is to copy the name of the inventory that is displayed when the player clicks the block or to copy the display name of the item when it is placed. 
In single player this works completely fine because optifine can directly access the integrated server.

**Comment by sixfootblue** [comment]
Ahh okay, that's unfortunate. Oh well.

**Comment by SetantaLP** [comment]
Yea, the only way to get this working in multiplayer would be a server-mod/plugin that sends the required data by using a plugin-channel together with a client mod (e.g. optifine) that is able to read the data, because plugin channels are a vanilla feature and it is possible to send any data by using them, but the data is only sent if the receiver (either client or server) has told the sender that it would like to get messages on this channel.

**Comment by sp614x** [comment]
Currently name-based CTM blocks doesn't work correctly in multiplayer. 
The server doesn't send the block entity name to the client until the name is needed, for example when opening the block entity GUI (container).
