### ISSUE TITLE
Improve Minecraft's CPU/GPU utilization?

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [sp614x/optifine#1503]
with I7 7700k and GTX 1080TI
GPU usage is often only 40%
CPU is about 20%
I don't know why, I'm be sure isn't hold on options, I have set up Java and Minecraft in the graphics driver.
I'm be sure on other games isn't have this problem

with my old computer G3250 and GT620
GPU and CPU utilization are nearly 100%
This is very strange

**Comment by Skuhoo** [comment]
Minecraft has poor multicore support. With your old processor being just a dual core the issue wasn't very pronounced, but since your new processor has 8 logical cores the issue becomes very obvious since Minecraft only really uses a single core for almost everything.

Task manager shows this and I've included a screenshot of my processor's usage while playing Minecraft. Each line graph is a different logical core.
![image](https://i.imgur.com/4g5MH08.png)

**Comment by sp614x** [comment]
You can try to enable Render Regions: Video Settings -> Performance -> Render Regions
This should allow the game to better load the GPU.
The CPU being loaded at 20% is normal, one core is fully loaded. Another 2 or 3 can be partially loaded by the internal server and the chunk loading.
