### ISSUE TITLE
[Suggestion] Better Foliage

### ISSUE THREAD

**Issue by jriwanek** [sp614x/optifine#159]
Don't know how much would be relevent to optifine but it'd be nice if optifine could do things like the leaf animations (atleast) and maybe the "fluff" on grass/cactus/lilypads/so on like the BetterFoliage mod does.

List of features:
http://minecraft.curseforge.com/projects/better-foliage/pages/features

Have a pick through if you like and see if any would be suitable for optifine itself.

**Comment by sp614x** [comment]
The current Better Foliage features:
- waving leaves and grass for modded blocks - only relevant for mods with active shaderpack
- extra leaves - can be added by resource packs
- short grass and mycelium - can be added by resource packs
- round logs - too complex to be implemented now, could be implemented as Cusom Models
- better cactus - can be added by resource packs
- better lilypads - can be added by resource packs
- reeds, algae and corals - changes the visuals too much, could be implemented as Cusom Models
- netherrack vines - can be added by resource packs
- falling leaves - unrealistic, green leaves do not constantly fall from the tress
- rising souls - interesting
- connected grass texture - already available as Better Grass

Many of the features can already be added by resource packs by using block models. 
Support for Custom Models could be added, so that resource packs could add round logs, reeds, algae and corals. Support for Custom Particles could be added so resource packs can add falling leaves and rising souls.
Custom Models is on the TODO list with low priority because it is too complex and has some general problems. Custom Particles has not been considered until now.

**Comment by jriwanek** [comment]
Thanks for your feedback!
