### ISSUE TITLE
[Suggestion] Adding an option to choose whether to cull or not cull blocks such as repeaters, slabs, etc. in 1.13

### ISSUE THREAD

**Issue by Higgsboson728** [sp614x/optifine#1609]
I've made a similar suggestion post on the Minecraft Forums, but since I have doubts that Mojang will ever see it let alone consider it I've decided to suggest it here. [Here's the post I made about culling](https://www.minecraftforum.net/forums/minecraft-java-edition/suggestions/2918278-resource-packs-add-an-option-to-choose-whether-to).

Basically, my suggestion is for there to be an option in the settings that enable or disable culling for blocks underneath certain blocks. This way, resource packs that model blocks such as repeaters, comparators, etc. won't break with optifine.

**Comment by ShabanPlayz** [comment]
you can use cit for that and put those cit items into itemframes. that way you dont have to change blocks and your ressourcepack wont make any builds look weird

**Comment by Higgsboson728** [comment]
How is that going to help?

**Comment by Higgsboson728** [comment]
Putting them into itemframes is a solution, but then you'd need to get pretty close to them for them to render. What I'm looking for is an option to enable/disable culling for blocks underneath repeaters and comparators to allow resource pack creators to model them without running into problems.

**Comment by Higgsboson728** [comment]
@sp614x 

My apologies for mentioning you, but since this request has been open for a considerable amount of time with no response from the dev, I thought I'd mention you. Would it be possible for this suggestion (above) to be implemented? Or is the idea too vague, etc? If you could get back to me, that'd be great.

Again, I apologize for mentioning you but I hope you understand as this is a rather urgent matter.
Thanks.

**Comment by sp614x** [comment]
Changing the culling is not enough. 
The light propagation also have to be changed otherwise the blocks behind the non-culled face would be black. Changing the light propagation requires the affected chunks to be relit again which is quite expensive. This also changes the game mechanics (mob spawning).

Because of this it is currently not possible for a resource pack to convert a culled face to a non-culled face and the face culling of nearby blocks is hardcoded in the block itself.
