### ISSUE TITLE
[Suggestion] Ability to change TPS

### ISSUE THREAD

**Issue by Hax4Ever** [sp614x/optifine#1749]
An option to lower the TPS would be nice (obviously the lower you go, the faster some things would need to be in the code, something like that)

It could theoretically make the game run much smoother

**Comment by Prysmal** [comment]
This is non-logical. Tick speed is how the game tells time in it's coding, so decreasing tickspeed would not only mean everything happens less frequently, but also means the game would be less responsive to player-input if I'm not mistaken. If you mean random events exclusively, you can already do that in singleplayer with /gamerule randomTickSpeed

**Comment by Prysmal** [comment]
https://minecraft.gamepedia.com/Tick

**Comment by Hax4Ever** [comment]
This could still have some theoretical benefit to either ram/cpu usage or player input, as a trade-off that anyone may fine-tune

**Comment by Prysmal** [comment]
Thing is, the game tick already scales in the base game for slower hardware. Increasing the tick speed wouldn't really do anything but make movement imperceptibly smoother. Seeing as walking around, etc is already more than smooth enough to play, I don't see a point.

**Comment by sp614x** [comment]
There are client tick speed and server tick speed.
Both are used for various updates and they would change the game mechanics if changed.
The ticks should have minimal effect on FPS if any.
The biggest effect that ticks have on FPS (stability) is via the animated textures. This should be fixed by enabling Emart Animations.
Changing tick speed would break many things if enabled.
