### ISSUE TITLE
Suggestion: make custom item textures work with blocks

### ISSUE THREAD

**Issue by MrConfusioned** [sp614x/optifine#1808]

**Comment by nate33730** [comment]
As a CIT pack developer, this would definitely change the whole dynamic for my resource pack. I'm just not sure how you would pull it up in-game, you wouldn't be able to rename it or attach lore, it'd just clear once you placed it. This used to be possible when each block still had extra meta data but Mojang removed it in a following update. Blocks could have limited multiple textures since each block had its own extra hidden id's to it. You used world edit to select and replace the block with one of its duplicates, so with a resource pack that duplicate would have different texture. Though players without world edit couldn't break and pick up or middle click them, it just broke the texture, which made it somewhat useless for survival mode.

**Comment by sixfootblue** [comment]
This already works with renameable blocks on singleplayer. Check the CTM documentation.

**Comment by MrConfusioned** [comment]
Six foot blue do you mind linking it

**Comment by sp614x** [comment]
This should already work:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/cit_single.properties#L128
