### ISSUE TITLE
Minecraft consumes way more memory than the maximum allocated memory in Java.

### ISSUE THREAD

**Issue by Captain-John-Price** [sp614x/optifine#1856]
I found another one that solely hampers my peformance in my game (on a 2GB ram pc).......the picture says everything.
![untitled](https://user-images.githubusercontent.com/32433983/46400273-92c9fe80-c72c-11e8-970a-eb5fdf2c3e95.png)
](url)    
     
   
here is the deal, before you say "just increase you RAM"........you have to remember that it works fine for me in back in optifine 1.12!!! (I even raised my allocated memory to 1GB back then and didn't have much issues as it is today)

**Comment by Dovahrt** [comment]
I have the same problem (on 2 GB RAM laptop). I was able to enjoy Minecraft 1.12 with Optifine... now I can't. I really hope sp614x or Mojang can fix this.

**Comment by sp614x** [comment]
Java can allocate heap memory (seen by java programs) up to the given maximum. It can also allocate additional native memory (buffers, etc) also up to the given maximum. Additionally the Java Virtual Machine itself needs memory in order to run.

As a result it is normal for Java effectively to allocate twice as much as the given maximum.

In 1.13 Minecraft started to use libraries which allocate native memory outside of the Java memory. As a side effect the Java memory is not used so much as in 1.12. This means that the memory limit can be reduced. For example in the above screenshot 600 MB are allocated of which 400 MB are used, so the limit could be set to 600 or even 500 MB.

Using higher render distance or HD resource packs would need more memory.

**Comment by MNEram** [comment]
i'm having the same issue. I'm using ubuntu and normally when ram consumption is 500 mb , while running minecraft it sometimes jumps to 5-6 gb . I have 8gb ram. So how can I tackle this issue?
