### ISSUE TITLE
Can't pay using Paymentwall! (We were unable to authorize your card.)

### ISSUE THREAD

**Issue by UnspeakableKinG** [sp614x/optifine#1858]
hello i wanna buy a cape, i typed everything right but when i click on the pay button it suddenly shows this message:
<img width="173" alt="ee" src="https://user-images.githubusercontent.com/29225045/46434238-c708e380-c75b-11e8-80c6-d07c9e02fda8.PNG">
its a visa Credit Card
PS: i'm not using an **ad-block** or anything...

**Comment by UnspeakableKinG** [comment]
i use this card with Paypal and bought many thing with it including Minecraft.

**Comment by Regnander** [comment]
Have you enabled Internet purchases and overseas usage for your credit card? I don't know if that's the issue here, but it's usually the issue when my credit card is denied if I'm gonna rent movies online.

**Comment by UnspeakableKinG** [comment]
My card isn't disabled i bought minecraft with it and ranks on different servers like hypixel.

**Comment by HawaiianPi** [comment]
At least you get an error message. When I try to pay, the pay button gets a little swirly busy thing, then after a moment the "PAY 10.00 USD" reappears ... and nothing. No confirmation. No error. Waited a few days to make sure no charges were pending, then tried again, and same thing.

When I bought a cape for my older account PayPal was an option, and that worked fine. Guess I can't make any more donations (or get a cape for my 2nd account) because this new system won't take my money. 👎

**Comment by sp614x** [comment]
You should contact the payment provider (Paymentwall) only they can fix this.
