### ISSUE TITLE
Conected textures

### ISSUE THREAD

**Issue by seba244c** [sp614x/optifine#1886]
The Conected textures freture where glass gets connected to one block does not seem to work with an resouce pack.

**Comment by Regnander** [comment]
Can you upload your resource pack here, so we perhaps can figure out what's wrong?

**Comment by seba244c** [comment]
yes here is an link [https://www.planetminecraft.com/texture_pack/ignafs-quadral-resourcepack/](https://www.planetminecraft.com/texture_pack/ignafs-quadral-resourcepack/)

**Comment by seba244c** [comment]
And heres an modified version that i use [link](https://nofile.io/f/rP0wzmm4WY5/pack.zip) . Optifine version: OptiFine 1.13.1 HD U E3 pre5

**Comment by Regnander** [comment]
Okay, I've found the problem. The reason why connected textures doesn't work for you is because your resource pack doesn't have the necessary files.

In order for a resource pack to have support for connected textures, several images and `.properties` files must be in the `assets\minecraft\optifine\ctm\default` folder, but since I have the necessary tools and time, I've now made a resource pack for you **(note that this _only_ contains files for connected textures, so you will still need your resource pack for all other stuff)**:

[RPG_-_Connected_textures.zip](https://github.com/github/hub/files/2475710/RPG_-_Connected_textures.zip)

Can you test it and give me your thoughts about the colorless windows?

**Comment by seba244c** [comment]
Tommorow. oK!

**Comment by seba244c** [comment]
Nope does not work

**Comment by seba244c** [comment]
Using : pre-4

**Comment by InfiniteCorners** [comment]
Are you using assets/minecraft/optifine/ctm or assets/minecraft/optifine/ctm/default ? It apparently needs to be in the default folder within ctm. I have glass working as it should now in now in pre5 so as long as your directory usage is the same as what Regnander posted for download and you're using pre5 the issue shouldn't exist.

**Comment by seba244c** [comment]
i use assets

**Comment by seba244c** [comment]
but gtg GoodBye

**Comment by Regnander** [comment]
> Nope does not work
> 
> Using : pre-4

The resource pack I made earlier only works for pre5, not pre4. If you want to use pre4, use this instead: [RPG_-_Connected_textures_pre4.zip](https://github.com/github/hub/files/2475857/RPG_-_Connected_textures_pre4.zip)

**Comment by seba244c** [comment]
I am updating now!

**Comment by seba244c** [comment]
Works THANKS!
