### ISSUE TITLE
[Suggestion] Option to disable Leather armor tint in CIT

### ISSUE THREAD

**Issue by Francy-Chan** [sp614x/optifine#1919]
It defaults use an grayed texture, but if I use a colored texture, the armor tint applies, then I can mess with the colors. A quick fix is dye to white but I wanted it for all colors.
![Example](https://user-images.githubusercontent.com/40085587/47122535-93df4d80-d24d-11e8-9ce8-a0ad96c407d0.png)

**Comment by InfiniteCorners** [comment]
Couldn't you just use the overlay layer, which uses normal RGB, for your entire CIT image instead of using the grayscale at all? I assume you mean you want every color of the leather armor to look like the final picture when referenced in CIT which is what you'd get by using the overlay layer instead of the base. If you mean you want the final to be default, and when dyed the colors to change, I'm not sure if that's possible with the way MC applies the coloring to the grayscale.

**Comment by Francy-Chan** [comment]
It works! I completely forgot about the overlay layer, because I replaced the texture for a blank one a looong time ago...
Well.. thank you.

**Comment by crimsonknight51** [comment]
so how do you apply this because right now my armor is brown is there some way i can get a screenshot of the .properties file for this
