### ISSUE TITLE
Connected Glass panes incorrect connected (CTM)

### ISSUE THREAD

**Issue by kay1010100** [sp614x/optifine#1924]
In the south and east direction glass panes are orientated the wrong way, but not for north and west.

This also happens with stained glass panes
![download](https://user-images.githubusercontent.com/44272417/47173440-61e1f000-d30e-11e8-9e12-524b0a46362d.png)
![download 1](https://user-images.githubusercontent.com/44272417/47173441-61e1f000-d30e-11e8-9f05-b1df39120bf6.png)

**Comment by kay1010100** [comment]
I found out some people have this problem and some don't. ¯\_(ツ)_/¯

**Comment by sp614x** [comment]
Is the resource pack using custom glass pane models?
CTM can only work correctly with the original pane models.

**Comment by kay1010100** [comment]
I only changed the texture, not the moddel.

I'm using ctm, mot ctm compact.

**Comment by kay1010100** [comment]
Multible people are using my pack some have the problem and some dont

**Comment by chland** [comment]
IDK if this will help you but I had pretty much the same problem with a clear-glass resource-pack: https://github.com/sp614x/optifine/issues/1913

It happened because I used multiple packs and one of them (NOT the clear-glass pack) was shipping model-files for the glass. When I removed that pack, everything worked fine. I "solved" my problem by just deleting the glass-models from the second pack.

Maybe you (and the people that are having issues) are using multiple packs, too!?

**Comment by Mick43** [comment]
hello, from my side the conected glass does not work at all since the 2 or 3 last version pre, yet it works during the old pre-release

**Comment by giammod** [comment]
what do your .properties look like? I have custom pane models AND ctm and I don'r have this issue.

**Comment by sp614x** [comment]
OptiFine fixes the vanilla pane models so that CTM can work correctly.
If any of the loaded resource packs overwrites the pane model then the CTM will look incorrect from one side (the other side is OK).

**Comment by giammod** [comment]
Really? As I said I have custom pane models and I don't have this issue at all, from either direction.

**Comment by sp614x** [comment]
If your RP changes the pane models in a way that is compatible with CTM then they may work.
