### ISSUE TITLE
 OptiFine 1.13.1 HD U E3

### ISSUE THREAD

**Issue by PsyChung** [sp614x/optifine#1935]
connected textures are not Working

**Comment by D3monPixel** [comment]
pay attention to the new folder structure. With 1.13 Optifine merged the mcpatcher folder into the optifine folder. Be sure to copy things over and swap out numeric id's for block names if you use them due to the flattening Mojang did.

**Comment by PsyChung** [comment]
what do you mean mcpatcher?
connected textures was working in pre 4

**Comment by D3monPixel** [comment]
That was because in pre4 optifine hadn't yet followed Mojang's folder renaming sceme. If you know how to edit a resourcepack, try opening it and locate /assets/minecraft/mcpatcher and rename that folder. It now needs to be /assets/minecraft/optifine. 
If you don't know how to edit packs and using a resourcepack someone else made, try informing them of the Optifine update and ask them for a fix. If it was working in pre4 then that folder issue might be the only one.

**Comment by sp614x** [comment]
In pre5 folder "mcpatcher" was moved to "optifine".
- move all configurations from "mcpatcher" to "optifine"
- replace all numeric configurations (blocks, items, etc.) with names
