### ISSUE TITLE
[Suggestion]About prevent stolen the model

### ISSUE THREAD

**Issue by SKYRIMx6023** [sp614x/optifine#2003]
I think optifine is good mod ,but when i started to add some modeling useing in server,someone badguy always want stolen my model and sell to others with different price,that caused some big problem ,i wish you can develop you optifine ,let it can stop everyone except me to using my model    ,   thank please!

**Comment by Strum355** [comment]
This is relevant to optifine how?

**Comment by SKYRIMx6023** [comment]
> This is relevant to optifine how?
use cit to load the model , and use lore to display the model.

**Comment by Zefferis** [comment]
You're gonna have to be a bit more clear about your issue or suggestion.

>"add some modeling useing in server"

Are you hosting a server with a server resource pack which is being sent out to players automatically?

Are you hosting an independent resource pack with your included model and a "badguy" is just taking those files and selling them?

>"use cit to load the model , and use lore to display the model."

You can already do this. 

as an example:

*assets\minecraft\optifine\cit\sea shells*
blue_conch.png
blue_conch.properties

blue_conch.properties file:
```
items=flint
texture=blue_conch.png
nbt.display.Lore.0=The Blue Conch symbolizes
```

____________

You need to explain exactly what the issue is clearly.

**Comment by Miclebrick** [comment]
If you're distributing the model in a resourcepack, no matter what you do, people will be able to take it. If anything put a license on your resourcepack.

**Comment by sp614x** [comment]
OptiFine is a client side mod, it can't change anything on the server.
