### ISSUE TITLE
Custom texture support for shaderpacks

### ISSUE THREAD

**Issue by DeDelner** [sp614x/optifine#209]
Image files which are located in a seperate folder. For example:
`.minecraft/shaderpacks/<Shader>/textures/dirtyLens.png`

And then using them by a sample2D.
`uniform sampler2D dirtyLens;`

**Comment by Strum355** [comment]
I'm 100% behind this idea

**Comment by robobo1221** [comment]
We should also be able to define the texture twice. for instance if you want to have one as a cubemap and the other one as just a texture without using 2 different textures.

**Comment by sp614x** [comment]
Are the custom textures needed in gbuffers or only in composite/final?

**Comment by DeDelner** [comment]
For me, only in composite and final.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2.
Added support for custom textures: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L46

**Comment by Builderb0y** [comment]
First issue with this system: gbuffers don't have "arbitrary data" samplers. By this I mean they don't use gaux<N> or colortex<N>, so to use custom textures in the gbuffers stages, you have to overwrite other samplers which may be in use. Overwriting normals or specular doesn't seem to work at all (bug?), and overwriting shadow/shadowtex0/1 DOES work, but also decreases framerate due to the fact that declaring any of them as a sampler automatically enables shadow calculations, which requires rendering the whole world twice, and without frustum culling. Using shadowcolor/0/1 seems to work without enabling shadow rendering (oddly), but it would be nice to have at least one dedicated custom textures sampler in the gbuffers stage.

**Comment by sp614x** [comment]
Updated preview B7 for 1.11.2 
- added gbuffers uniforms gaux1 to gaux4, can only be used as custom textures 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L226
