### ISSUE TITLE
More than 8 color buffers

### ISSUE THREAD

**Issue by SergeantSarcasm** [sp614x/optifine#2103]
Right now with Optifine devs are limited to only 8 buffers that we can read and write to, as far as I know this is a really outdated limitation and with certain effects having the ability to reasonably take up several buffers worth of information I don't really see a reason why not.

**Comment by sp614x** [comment]
The problem is that no more than 8 buffers can be bound at the same time.

Most GPUs have a limit of 16 texture units per shader stage:
https://feedback.wildfiregames.com/report/opengl/feature/GL_MAX_TEXTURE_IMAGE_UNITS_ARB

Currently 8 texture units are used for predefined buffers (shadow/depth/noise) and 8 are for color buffers: 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L304

With modern GPUs on windows/Linux the situation is better, most support 32 buffers: https://opengl.gpuinfo.org/displaycapability.php?name=GL_MAX_TEXTURE_IMAGE_UNITS

The biggets limit so far is that the OSX drivers are always limited to 16 buffers even on modern hardware.

**Comment by sp614x** [comment]
Custom buffer flipping can be used to access separately the A/B ping-pong buffers:
https://github.com/sp614x/optifine/issues/1854
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L420

For example defining custom flip for `deferred_pre` and `composite_pre` can be used to write to A buffer in all solid programs, write to B buffer in water program, then read A in `composite` and read B in `composite1`.

**Comment by sp614x** [comment]
Added in G7_pre1 for 1.16.4.
