### ISSUE TITLE
[1.13.2] Water can be see through ice at chunk borders

### ISSUE THREAD

**Issue by achihi** [sp614x/optifine#2194]
Noticed by using OptiFine 1.13.2 HD U E6 pre4

You can see through ice at chunk borders using third-person mode.
Changing shaders from OFF to Default fixes the water but you still can still see the "hole" in ice. 

OFF SHADER:
![javaw_yofeixvu9a](https://user-images.githubusercontent.com/46202204/52654842-2db0c180-2ef3-11e9-9d6e-ce26e6b72fc8.png)
![javaw_5da96qbjg6](https://user-images.githubusercontent.com/46202204/52655324-31911380-2ef4-11e9-9b75-92b92dbb051f.png)

DEFAULT SHADER:
![javaw_qsby2hvfms](https://user-images.githubusercontent.com/46202204/52655296-250cbb00-2ef4-11e9-9296-7791a35be1ae.png)

**Comment by Quavelen** [comment]
I can confirm this: https://giant.gfycat.com/MiserableDizzyItalianbrownbear.webm
Used gfycat, because GitHub doesn't support video uploads. 

First part of the video shows no shaders, then BSL shader, and finally internal shader. With BSL enabled, the see-through ice was fixed. However with internal and no shader, the ice was see-through. This only occurs on a corner, as explained above, and shown in the video. 

Using OptiFine 1.13.2 HD U E6 Pre2 in a singleplayer world.

**Comment by Regnander** [comment]
This is also a glitch in vanilla: https://bugs.mojang.com/browse/MC-60772 <sub><sup>(Feel free to login and leave a vote there!)</sup></sub>
If Mojang can fix it, perhaps we won't have this problem in OptiFine.

**Comment by sp614x** [comment]
This is a vanilla problem and it only happens in third person view. 
The translcent chunks are sorted as seen from the player position, not from the camera position.

**Comment by Regnander** [comment]
A quick update! This bug has now been marked as resolved for 1.14+ on Mojang's bug tracker.
