### ISSUE TITLE
Crash while loading into game?

### ISSUE THREAD

**Issue by MrSpencerRecor** [sp614x/optifine#2228]
Playing with a lot of mods, wondering why Optifine is the one causing this and how to fix it without loosing optifine
https://pastebin.com/nHNy6ZZe

**Comment by sp614x** [comment]
The game crashes because it can't load all textures in the texture atlas.
The GPU maximum texture size is 4096x4096 which is pretty small, most current GPUs support 16384x16384.

Adding OptiFine may cause the crash because it adds some new textures (connected glass, connected stained glass, etc.).

You can try to:
- disable Connected Textureds
- remove some of the mods that add a lot of textures.
```
net.minecraft.client.renderer.StitcherException: 
Unable to fit: refinedstorage:blocks/security_manager/left, size: 16x16, 
atlas: 4096x4096, atlasMax: 4096x4096 
- Maybe try a lower resolution resourcepack?
```
