### ISSUE TITLE
[Request] (Better Skies) Sky depending on world name

### ISSUE THREAD

**Issue by Gunging** [sp614x/optifine#2240]
Hello,

You may ask why linking the sky to the world name, like, who would create a new world only for a sky texture?

Perhaps not in vanilla Minecraft, but I'm talking about servers with Multiverse plugin. What if one of the several worlds is an alien planet? What if the storyline of the rp server takes you to other dimensions? Well this is exactly my case, and I'm certain I'm not the only one.

Honestly, it would just be amazing if the sky could change based on world name, because you can build all kinds of buildings to show that the player is not anymore in their home world, but changing the sky is just the ultimate detail that yells at you "You are somewhere else."

**Comment by SetantaLP** [comment]
It's a cool idea, but that would only work in singleplayer, since the server doesn't send the world name to the client (unless a plugin/mod does that via a payload packet and there is a client mod that handles this data).
Besides that the client doesn't know anything about the world-logic that happens on the server, so it creates some kind of in-memory dummy-wold when you join a server, to display the data sent from the server and handle your input that should be sent to the server, and removes that wold from memory when you leave the server.
And even if you switch the world on the server, the client world stays the same, since you can only switch dimensions not worlds on a vanilla server, while it is running. So switching worlds in BungeeCoord and most likely also in Multiverse is done, by telling the client to respawn the player (which also happens when you press "respawn" after you died.), since that will cause the client to remove all the server-data from it's memory.

**Comment by sp614x** [comment]
Custom sky can be configured per dimension:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/sky.properties#L37
There is no other "world name" available in multiplayer.
