### ISSUE TITLE
Optifine crashes upon loadup

### ISSUE THREAD

**Issue by Gabster123** [sp614x/optifine#2336]
[hs_err_pid1196.log](https://github.com/sp614x/optifine/files/3124418/hs_err_pid1196.log)

**Comment by Quavelen** [comment]
@Gabster123, it tells you what your issue is in the file you uploaded. 

># Problematic frame:
># C  [ig9icd64.dll+0xd76cb]

You're trying to use Intel integrated graphics with either an outdated intel HD driver, or with a setting enabled that your integrated graphics don't support. 


Open the vanilla game, press the F3 key on your keyboard to open the debug menu, and then take a screenshot of the game with that debug menu open. Upload that screenshot here. You can directly upload it to GitHub.

**Comment by Gabster123** [comment]
@Quavelen I have no clue what any of those numbers mean. I am in no means a computer guy nor do i know anything about computers except for the fact that games are fun and i like to play them but here is what you asked for.
![2019-04-28_12 23 35](https://user-images.githubusercontent.com/50060276/56867186-7cc5a900-69b0-11e9-82b2-60b9c31196cb.png)

**Comment by Quavelen** [comment]
Thanks, your debug menu explains your issue; you're using a laptop. When you launched with OptiFine, it tried to use the same settings you had enabled in vanilla, but instead for some reason it did not tell your graphics card to render it; it tried rendering on your processor's integrated graphics chip. 

If you know how, go into your nvidia control panel and setup a profile for "javaw.exe" and tell it to use your graphics card. I believe on laptops, it would be called "high performance nvidia processor"? I don't use a laptop, so I can't be certain.

**Comment by Gabster123** [comment]
I haven't got a clue how to do that.

**Comment by sp614x** [comment]
You can go to "Options -> Video Settings" and disable VBOs.
This should fix it.
