### ISSUE TITLE
[Shaders] Texture Sprite + Atlas Size macros

### ISSUE THREAD

**Issue by BruceKnowsHow** [sp614x/optifine#2342]
A lot of shader packs have an option for "texture pack resolution", I believe this could be fixed by just having a shader macro for the sprite size of the textures in the texture atlas.

Additionally, I'm doing work right now where it would be very convenient to have the texture atlas dimensions, either in the number of sprites, or total pixels.

Example:
#define SPRITE_RES 32
#define ATLAS_SIZE_X 1024
#define ATLAS_SIZE_Y 512

This would be for a "32x32" sized texture pack, where there are few enough textures in the pack that the atlas size is 32x16 sprites.

I believe all of these metrics are already printed to the console, so it would be a simple matter of hooking them up to the shader. Here is a printout from my shader log:
[21:09:18] [main/INFO]: [OptiFine] Sprite size: 32
...
[21:09:19] [main/INFO]: Created: 1024x512 textures-atlas

**Comment by sp614x** [comment]
The texture atlas size is available as uniform: 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L176.

The resource packs don't have a fixed sprite size. There is usually a mix of differently sized sprites.
For example in the default RP water and lava are 32x, while all other sprites are 16x.
The "missing" sprite (purple/black) is always at minimal size (usually 16x) and it can't be changed by a RP.

The "Sprite size" in the log is only shown when mipmaps are enabled and set at maximum. Then the texture atlas may force a minimum size on all sprites in order to optimize the mipmaps. This doesn't stop the RPs from using larger sprites.
