### ISSUE TITLE
[Suggestion] Custom textures to replace ambient occlusion

### ISSUE THREAD

**Issue by realjackasterisk** [sp614x/optifine#2351]
I came across this screenshot browsing the Minecraft subreddit, it really caught my interest.

![zzqlmj8xeru21](https://user-images.githubusercontent.com/31686191/57136041-6167ee80-6d60-11e9-9c37-317c931e8785.jpg)

In my opinion, this sort of "cel-shaded" look on the AO looks absolutely WONDERFUL, and it got me thinking, "what if we could do this with a resource pack?"

Imagine the possibilites. Fully custom AO textures. Sounds like it could be some kind of extension to CTM, as an overlay to all existing blocks and maybe even an additional property to other CTM methods.

**Comment by sp614x** [comment]
It may be possible to replace the AO shadows with textured shadows.
Potential problems:
- slower - the shaded blocks would use 2 layers, the second one being translucent using blending
- only suitable for full blocks, partial blocks would be complicated
- chunk update lag due to all the translucent geometry resorting
- shaders would probably have problems with the translucent overlays

**Comment by sp614x** [comment]
The effect in the screenshot is done with shaders.
