### ISSUE TITLE
Optifine 1.14?

### ISSUE THREAD

**Issue by Blueeyestar** [sp614x/optifine#2363]
Are there any hints if work on 1.14 is in progress and when the first version might be released?

**Comment by LOuroboros** [comment]
@sp614x stated in #2329 that he already started to work in Optifine 1.14, but that's it.
No release dates were given _(and that would probably be a mistake in my opinion, as you never know when something can go wrong)_.

With that being said, 1.14 might be worth skipping, not only because it's pretty buggy, but because [1.14.1 might be close to be released](https://www.minecraft.net/en-us/article/minecraft-1-14-1-pre-release-1).

**Comment by realjackasterisk** [comment]
There is progress updates on the Discord and the pinned subreddit post: https://www.reddit.com/r/OptiFine/comments/bh7o49/optifine_114_progress

**Comment by Blueeyestar** [comment]
Thanks for the useful information :)

**Comment by WolfezzKyne** [comment]
> 
> 
> There is progress updates on the Discord and the pinned subreddit post: https://www.reddit.com/r/OptiFine/comments/bh7o49/optifine_114_progress

There is a discord server for optifine? Can you link it? :D

**Comment by realjackasterisk** [comment]
You could've found the link on the subreddit sidebar but here https://discord.gg/3mMpcwW

**Comment by WolfezzKyne** [comment]
Thank you :)
