### ISSUE TITLE
Backface information?

### ISSUE THREAD

**Issue by dotModded** [sp614x/optifine#237]
I'm working on some facny lighting things and I need some more information to render them properly. I need the normals and depth of back-facing geometry, specifically for the water shader. This would be super useful for what I am doing and would help a tonn, thanks in advance if this can happen I would be a very happy man.

**Comment by dotModded** [comment]
Note, maybe add a shader pass for backfacing geometry, so we have more control. Have one for textured and water.

**Comment by sp614x** [comment]
Currently back-facing geometry is rendered in the shadow pass in order to avoid sunlight shining undrground.
I can add an option to disable back-face culling in the terrain pass if this is going to help. There could be a significant FPS drop.

**Comment by dotModded** [comment]
I believe you are wrong about the back face geometry being rendered, as there still is sunlight shining underground. However if you do make an option that would be amazing.

**Comment by dotModded** [comment]
However I really need this more in the water shader is it would be for doing a BSDF to to transmission and refraction on both incoming and outgoing light

**Comment by sp614x** [comment]
Should the back-face culling be disabled in the water pass or in the terrain pass?

**Comment by dotModded** [comment]
Options for both would be nice, Just having access to backface info will be really nice. However if I where to pick between the two I would like water.

**Comment by sp614x** [comment]
In "shaders.properties":

`backFace.solid=<true|false>`
`backFace.cutout=<true|false>`
`backFace.cutout_mipped=<true|false>`
`backFace.translucent=<true|false>`

would this be ok?

**Comment by dotModded** [comment]
This would be perfect

**Comment by sp614x** [comment]
Added in preview C4 for 1.10.2

`# Enable back-face rendering per render layer`
`# Default is false`
`backFace.solid=true|false` 
`backFace.cutout=true|false`
`backFace.cutoutMipped=true|false`
`backFace.translucent=true|false`

**Comment by zombye** [comment]
Any chance to get backface depth information?

I haven't been able to access it without also discarding the color of frontfaces, which is obviously not an option - I guess that might be a driver bug, but it would still be useful to have another depthtexture for that.

@dotModded, backfaces are actually rendered in the shadow maps. In Continuum 1.2.2 PBR you're actually adding between ~2.5 blocks to ~41 blocks (if the related constants i remember are correct) to backfaces Z position in the shadow vertex shader, so that's probably why it seems like they're not being rendered.

To get that to something that's probably much more like what you want, change line 325 in shadow.vsh to `position.z += pow(max(0.0, 1.0 - abs(normal.z)), 4.0) * 0.01;`

**Comment by dotModded** [comment]
You should be able to generate back face depth quite easy as you have the verts in any space you want, convert them into view space and get the length of that and do a min max cull and you should get the depth.

**Comment by dotModded** [comment]
Actually backface depth would be nice, I changed my mind on this, using an extra buffer for this would be less than ideal.

**Comment by sp614x** [comment]
Is this still relevant, can the issue be closed?
