### ISSUE TITLE
[Suggestion] Fixing how minecraft renders textures on the atlas

### ISSUE THREAD

**Issue by 4rri** [sp614x/optifine#2379]
After a lengthy talk in the discord with people who actually know what they're talking about when it comes to this stuff- this title was born.

Now I have no idea what I'm saying here, so bare with me, but apparently with the way minecraft renders textures, there is a 1-pixel-wide transparent line at the edge of textures, which is annoyingly frustrating. According to "Cadiboo", he managed to fix this in his mod by adding/subtracting 0.00001 (1 / 10000F) from the texture coordinates.

Not sure if this is something that sp would like to address with optifine, but I damn well hope so- especially if this still isn't fixed with Blaze3D when that eventually comes out.

**Comment by sp614x** [comment]
Is this for handheld items?

**Comment by 4rri** [comment]
> Is this for handheld items?

It is indeed!

**Comment by sp614x** [comment]
The handheld item model seams can't be fixed with a simple scale. It would could fix some of the models, but it would make other models much worse.
The problem comes from the fact that the item models are built as a grid of many texture strips, not from single cubes. The seams don't match due to rounding errors in the texture mapping.
One way to fix it would be to create the models from single cubes, but this would make rendering them much slower.
