### ISSUE TITLE
1.13.2 U E7 sign text invisible when create sign-gui by sending packet 

### ISSUE THREAD

**Issue by ziokuroi** [sp614x/optifine#2422]
Client **Without** optifine:
http://i67.tinypic.com/2mfhypx.jpg
Client **With** optifine:
http://i64.tinypic.com/c55z5.jpg

What server sends:
    1.BlockUpdate packet with sign 2 blocks (y) below player
    2.UpdateSign packet with some placeholder text
    3.OpenSignEditor packet
    4.BlockUpdate packet resetting block removed at step 1.

**Comment by Regnander** [comment]
That's strange. The image links doesn't work for me. Can you upload the images here on GitHub by dragging them into the edit box?

**Comment by jere62smi** [comment]
@ziokuroi I also have the same problem since Optifine 1.13, before in 1.12 it worked. I even have sp614x come on my test server, he told me he was watching but no news for several months and appriori, it does not seem to be his priority...
I will try to contact him again, hoping you will do the same, I finally have a person who meets the same problem as me, with a little luck, it will react if we are many.

**Comment by jere62smi** [comment]
@sp614x If that can help you, I went back in the history of optifine and it seems that it is from the 1st version of optifine for the 1.13. While reading the changelog, I noticed a single modification of the signs on the version OptiFine 1.13.1_HD_U_E3 "- optimized sign and item frame rendering". Hoping that you can quickly correct this problem

**Comment by sp614x** [comment]
Is this version fixing the problem?
https://optifine.net/tmp/OptiFine_1.14.2_HD_U_F1_pre13_signs.jar

**Comment by jere62smi** [comment]
Perfect, the version you sent corrects the problem! Thank you, hoping that you will update this shift for Optifine soon available to the entire community.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
