### ISSUE TITLE
1.14.2 pre 6 || ctm_compact bug

### ISSUE THREAD

**Issue by xAphex** [sp614x/optifine#2423]
`OptiFine 1.14.2 F1 pre 6` doesn't handle `ctm_compact` very well.

it makes the glass show weird lines:
![image](https://user-images.githubusercontent.com/5391237/58750402-9a4bce00-849a-11e9-8405-ae0f4b13980d.png)

In Options:
`Connected Textures = Fancy`

Using MultiMC

**Comment by sp614x** [comment]
Resource pack?

**Comment by InfiniteCorners** [comment]
![2019-06-03_11 49 11](https://user-images.githubusercontent.com/41232136/58815751-2aeaf100-85f6-11e9-8d7c-f33dc8dbc201.png)

I would like to add that this bug has existed in all previews of Optifine and that is is definitely not being caused my MultiMC since I have always used the vanilla launcher. I've included a minimum resource pack for glass for testing.

[OptiGlass ctm_compact.zip](https://github.com/sp614x/optifine/files/3248432/OptiGlass.ctm_compact.zip)

**Comment by xAphex** [comment]
My Resource Pack: https://www.planetminecraft.com/forums/minecraft/resourcepacks/clear-glass-resource-pack-1-0-1--588192

**Comment by sp614x** [comment]
Fixed, coming in next preview.
