### ISSUE TITLE
Fabric Loader support

### ISSUE THREAD

**Issue by Madis0** [sp614x/optifine#2429]
Have you considered supporting the [Fabric Mod Loader](https://fabricmc.net/) [(and API)](https://minecraft.curseforge.com/projects/fabric)?

This has partly been implemented by an unofficial mod called [OptiFabric](https://minecraft.curseforge.com/projects/optifabric), however the latter has now been discontinued due to the difficulties in supporting Fabric's rendering API with Optifine's proprietary methods.

> A little over a week ago I released OptiFabric and it quickly came to my attention that there were some incompatibilities, especially with the shaders mod. [...]
>
>The issue was tracked down to be an incompatibly with Fabric API's new Rendering API and the implementation called Indigo. To fix the issue correctly knowledge of how Optifine works is required, this is not possible without good knowledge of the fabric rendering API and details on how Optifine works. [...]
>
> The ideal solution to this whole issue is official support for Fabric from Optifine. OptiFabric has proved that is possible and that users want the feature (5000+ downloads in week!).
>
>I see a few ways this could be made possible:
>
>• Optifine could include parts or the whole of OptiFabric, I see this being the easiest solution as the code already exists and has been proven to mostly work.
>
>• Optifine could become a normal fabric mod that uses mixins. This would require a lot of time and effort from the Optifine Developers but it would allow faster updates to newer Minecraft versions.
>
>If you want to explore this option or just need to ask a few questions feel free to contact me.

https://github.com/modmuss50/OptiFabric (MPL 2.0)

**Comment by sp614x** [comment]
Fabric is replacing the renderer with another implementation (Indigo) which is not compatible with OF.
OptiFine can't influence the Fabric functionality as Fabric is actively installing hooks and reorganizing the rendering pipeline.
The problem with shaders and possible solutions was discussed on Discord with @asiekierka and @grondag.

**Comment by sp614x** [comment]
A temporary solution may be to disable the custom Fabric renderer:
```
#Indigo properties file
always-tesselate-blocks=false
ambient-occlusion-mode=vanilla
```

**Comment by Madis0** [comment]
>A temporary solution may be to disable the custom Fabric renderer:
That would imply making Optifine loadable with Fabric in the first place. Unless you meant the current implementation of OptiFabric...

**Comment by sp614x** [comment]
The above configuration should make OF loadable with OptiFabric and all OF features should be working.

**Comment by asiekierka** [comment]
OptiFabric has been abandoned and is being forked by another developer. The test builds look promising, anyhow.

**Comment by grondag** [comment]
It's not accurate to state that Indigo replaces the renderer.  It adds a few hooks to the vanilla pipeline that allow models to output quads with buffer-time transformations, mixed render layers and better lighting for angled faces.  

But it does so with minimal patches while preserving the vanilla buffer builders structures and vertex formats.  It is similar in scope to the rendering enhancement in Forge for MC 1.12, even though the implementation is quite different. 

Indigo breaks because the vanilla classes it targets have been replaced or modified by OptiFine, causing some patches to fail. (That is what OptiFabric addressed.)  In the case of shaders, the assumption of vanilla vertex formats is no longer valid, but this is probably fixable on our end by using slower/non-bulk input methods for BufferBuilder. 

The other Fabric-compatible render, Canvas, absolutely does replace the renderer, and was never intended to be compatible with OptiFine (or any other similar mod). Canvas is not part of the Fabric project, nor is it required to  use Fabric or Fabric mods.

**Comment by iCaitlyn** [comment]
OptiFabric has been completely abandoned, and from the research of others, OptiFine, if made to work with Fabric, can just disable Fabric's rendering engine/API.

**Comment by Linguardium** [comment]
> OptiFabric has been completely abandoned, and from the research of others, OptiFine, if made to work with Fabric, can just disable Fabric's rendering engine/API.

no. this is currently what sodium does (replaces the renderer entirely even). Because fabric mods rely on the API, optifine for fabric would have to implement support or we'd still be in a "doesnt work with any mod trying to render things" problem. currently sodium has this issue but it is slated to be fixed by supporting fabric renderer api (not the vanilla renderer or indigo).

one simply cannot "disable rendering used by mods" without breaking things...

**Comment by Danjhop4** [comment]
> A temporary solution may be to disable the custom Fabric renderer:
> 
> ```
> #Indigo properties file
> always-tesselate-blocks=false
> ambient-occlusion-mode=vanilla
> ```
You can turn indigo off I believe so optifines render would work
