### ISSUE TITLE
Shaders UINT buffers not working

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#243]
The UINT buffers generate "GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CD6) at pre-useProgram".
They may need some program support: https://www.opengl.org/registry/specs/EXT/gpu_shader4.txt

**Comment by BruceKnowsHow** [comment]
I figured out how to effectively use floating point buffers as uint buffers:
https://github.com/BruceKnowsHow/Ebin-Shaders/blob/829a1d90713bf7773a6c489389f567036f892d5b/shaders/lib/Utility/encoding.glsl#L1

These functions operate identically to the packUnorm functions, however they output out a bitwise floating point caste. In fact, they are slightly faster than the built-in packUnorm functions.

One thing to note is that encoded floating point buffers must have filtering 100% disabled. There seems to be some implicit filtering on all screen textures, even when they are not lodded or offset whatsoever. In order to lookup encoded 32 floating point buffers, you must use texelFetch(). I do not know if uint buffers would have this filtering issue.

As far as I'm concerned, this issue is solved.

**Comment by sp614x** [comment]
Nice.

**Comment by BruceKnowsHow** [comment]
It appears there is always some implicit filtering with translucent surfaces. So far it only happens when the fourth component of the encoded vec4 is either 0.0 or 1.0, so I believe it's possible to workaround at the moment. The ability to disable alpha blending for certain attatchments in gbuffers_water would fix this annoyance.
