### ISSUE TITLE
Water renders in front of smoke

### ISSUE THREAD

**Issue by JstMarc6** [sp614x/optifine#2504]
![2019-06-16 (3)](https://user-images.githubusercontent.com/51888538/59568412-f89eb200-903f-11e9-8da0-02cbe5e92c2d.png)
![2019-06-16 (6)](https://user-images.githubusercontent.com/51888538/59568413-f9374880-903f-11e9-8cf8-1d565071f35a.png)
![2019-06-16](https://user-images.githubusercontent.com/51888538/59568414-f9374880-903f-11e9-9f6a-a22d3f3b50af.png)
Smoke floats behind water texture

**Comment by OktayYeniTR** [comment]
it's an old bug with transparency

**Comment by JstMarc6** [comment]
Thanks.

I had just never noticed it before. Having the perpetual smoke of a campfire on an island made it very apparent.

**Comment by Regnander** [comment]
The bug report can be found at https://bugs.mojang.com/browse/MC-9553 so make sure to watch it so you get notified via email whenever a change is made. You can also vote for it, since it
is a way for Mojang to see what bugs the fanbase wants them to prioritize.

Just note that you will need an account to do so.
