### ISSUE TITLE
Optifine crashes on Ubuntu

### ISSUE THREAD

**Issue by tykl3** [sp614x/optifine#2507]
When I try to launch Minecraft with Optifine it crashes.
![Screenshot from 2019-06-17 20-12-10](https://user-images.githubusercontent.com/45436993/59644891-fff7b580-913c-11e9-97d5-0883c2da4d49.png)

Game output says this
![Screenshot from 2019-06-17 21-50-59](https://user-images.githubusercontent.com/45436993/59647677-1c4e1f00-914a-11e9-9d3b-b5761a274b3b.png)

**Comment by Regnander** [comment]
What Java version do you have?

**Comment by tykl3** [comment]
11.0.2

**Comment by Regnander** [comment]
I don't think OptiFine has support for 11 (yet), but 8 would work just fine.

**Comment by SetantaLP** [comment]
As far as I know Optifine itself works fine with java11, but due to some breaking changes in java9 the official version of the launchwrapper, which is used to override the classes and stuff from the minecraft.jar with the modified data from the optifine.jar at runtime, no longer works on java9+. So to get optifine working, you can either use a modified version launchwrapper or you switch to java8 (e.g. by changing the path to the java-executable for the currently used profile in the launcher).

**Comment by tykl3** [comment]
I switched to java 8 and it works now!
