### ISSUE TITLE
Unable to Install Java

### ISSUE THREAD

**Issue by Parkman145** [sp614x/optifine#2517]
Every time I try to open the Installation wizard I get this Error. Help?

![Annotation 2019-06-20 190641](https://user-images.githubusercontent.com/52058027/59892841-a3d89f80-938f-11e9-9ae7-8c0d31aab843.png)

**Comment by PeterNjeim** [comment]
Remove all versions of Java from your computer, guide [here](https://www.java.com/en/download/help/uninstall_java.xml). Now install [java](https://download.oracle.com/otn-pub/java/jdk/12.0.1+12/69cfe15208a647278a19ef0990eea691/jdk-12.0.1_windows-x64_bin.exe) again, then run [this](http://johann.loefflmann.net/downloads/jarfix.exe) program. It assigns .jar files to open with Java instead of CMD. The program will say that there is an unknown publisher, the program is safe however and only needs to be run once.

You should now be able to simply double-click on the OptiFine .jar file and it will open properly. Please reply if you have further issues.

**Comment by Parkman145** [comment]
Worked Perfectly. Thank You!
