### ISSUE TITLE
feature request: string IDs should be exposed to shaders in some way

### ISSUE THREAD

**Issue by ali1234** [sp614x/optifine#254]
Currently the block ID is exposed to vertex shaders in mc_Entity.x. This is used to make plants move, make glowstone/lava luminous, and to make water look different to stained glass. This can be seen in SEUS gbuffers_terrain.vsh and gbuffers_water.vsh.

The problem is that this assumes that blocks have unique IDs, and those IDs never change. For example, if you look in SEUS, it has hardcoded block IDs for leaves from vanilla and also from biomes o' plenty. The latter will not work under the new string ID system as the mod block IDs will be dynamically assigned, and the mod might use the same block ID for every block it exports.

One possible way to handle this would be to translate the block IDs prior to rendering. Have a config file with a list of 

```
mod:block_name = block ID
```

then pass the remapped block ID into the shader. For example you could write:

```
ic2:luminator = 89
```

and now mc_Entity.x would be 89 (glowstone) for luminators, rather than whatever dynamic assigned block ID it gets. Now the luminator would get the same rendering treatment as glowstone, without having to modify the shader. 

That's just one way to tackle the problem. I don't know how easy it would be to implement or how resource intensive it would be, but it has the benefit of being backwards compatible.

**Comment by ali1234** [comment]
It turns out shadermod already has code for this, if you grep for mc_Entity_x.txt. But the hash map it builds is seemingly never used.

**Comment by sp614x** [comment]
This may lead to block ID conflicts.
For example if "ic2:luminator" has id 160, but it is mapped to 89 and block "minecraft:sandstone" has the id 89. When rendering sandstone the shader will treat sandstone like "ic2:luminator" and make it glow.

**Comment by Builderb0y** [comment]
Vanilla IDs are hardcoded. ID 89 will _always_ be mapped to vanilla glowstone, never sandstone. It's only the modded IDs, like "ic2:luminator", that change.

**Comment by sp614x** [comment]
A better way would be for OptiFine to rewrite the block ids with the current values.
For example if the shader defines:

    const block_sandstone = -1;
    const block_ic2_illuminator = -1;

then OptiFine can replace it when compiling the shader source with the current block ID. 


    const block_sandstone = 24;
    const block_ic2_illuminator = 317;

This will solve the problem with the dynamic mod block IDs. This could also be used to handle entity IDs.

**Comment by Builderb0y** [comment]
Technically that would work, though this also means the shader pack would have to check for every block that follows a given effect, so you'd just end up with a massive boolean/if statements like:

`bool windy = mc_Entity.x == block_sapling || mc_Entity.x == block_deadbush || mc_Entity.x == block_tallgrass || mc_Entity.x == block_yellow_flower || mc_Entity.x == block_red_flower || mc_Entity.x == block_double_plant || mc_Entity.x == block_wheat || mc_Entity.x == block_carrots || mc_Entity.x == block_potatos || mc_Entity.x == block_beetroots;`

And that's just for vanilla plants. Adding onto that all the botania plants and BOP plants and actually additions plants and chromaticraft's plants and every other mod to ever add plants anywhere... It adds up, and it's NOT very performant to check. Especially if you have to do it for every vertex in the world every single frame.

Another example: try making every fluid from minechem have waves. You'll end up with over 100 different IDs to check. (or maybe just one, not sure if it uses NBT data for them or not). Even if that is just one ID though, try adding TE fluids and forestry fluids and BOP fluids and IC2 fluids and BC fluids and chromaticraft fluids and TiC fluids and everything else that shows up when you search for "bucket" in NEI/JEI. It adds up too, and is just as unperformant to check.

I think the original suggestion would be the best way to implement this feature; if some config file somewhere says that a given modded block should be mapped to a specific ID, then mc_Entity.x should return that ID instead of the original block's ID. That way the shader pack only has to compare it to one value, not 50.

**Comment by ali1234** [comment]
Also this won't work in v1.8+ where block states are used instead of block IDs. There, every block in a mod can have the same ID, and the block state can't be serialized into 64 bits as it contains an arbitrary amount of data.

My original suggestion came about after I discussed it at length with forge devs on IRC.

Also I found the shadermod source code and I noticed it already has the beginnings of a remapping function similar to what I described (it works on block IDs instead of block states), but it is commented out.

**Comment by sp614x** [comment]
So the idea is not to target dynamic (moded) block IDs, but to map a list of vanilla/modded blocks to one ID for performance. The target ID can be either vanilla or virtual (id > 4096). Is this correct?

**Comment by Builderb0y** [comment]
Yes.

**Comment by sp614x** [comment]
Sample configuration: "shaders/block.properties", included in the shader pack.

    # Short format
    block.31=red_flower yellow_flower
    # Long format
    block.31=minecraft:red_flower ic2:nether_flower
    # Metadata
    block.31=minecraft:red_flower:6 minecraft:red_flower:7
    # Properties
    block.31=minecraft:red_flower:type=white_tulip minecraft:red_flower:type=pink_tulip

Similar configuration may be added for entities.
Does it look good?

**Comment by Builderb0y** [comment]
That works.

**Comment by sp614x** [comment]
Added block ID mapping to preview B3.
Waving stone blocks: http://i.imgur.com/bnXVAD9.png

The block ID mapping is defined in "shaders/block.properties" included in the shader pack.
Format 

    block.<id>=<block1> <block2> ...

The key is the substitute block ID, the value are the blocks which are to be replaced.
See "properties_files.txt" for the block matching rules.

    # Short format
    block.31=red_flower yellow_flower
    # Long format
    block.31=minecraft:red_flower ic2:nether_flower
    # Properties
    block.31=minecraft:red_flower:type=white_tulip minecraft:red_flower:type=pink_tulip
    # Block ID, Metadata (backwards compatibility)
    block.31=38:6 38:7

**Comment by ali1234** [comment]
Thanks for implementing this. I tested your code snippet above and it works. However I still have a problem with IC2.

I put this in block.properties:

    block.89=minecraft:red_flower:type=pink_tulip ic2:te:type=luminator_flat_active

And this is the result:

![2017-09-24_03 09 46](https://user-images.githubusercontent.com/651970/30778941-cbf71654-a0d9-11e7-8e2b-b31eb2c8a2c0.png)

Here you can see the pink tulip glows as expected, but the others do not.

![2017-09-24_03 11 06](https://user-images.githubusercontent.com/651970/30778946-da7ff678-a0d9-11e7-9c2e-c6df46462493.png)

But for the luminator, optifine does not seem to be able to see the "type:" field and does not correctly select it. Also note that it can see the "transparent:" field. "ic2:te:transparent=true" works as expected.
