### ISSUE TITLE
Optifine 1.14.3 crashes at startup.

### ISSUE THREAD

**Issue by asheden** [sp614x/optifine#2584]
Used to work perfectly, until it crashed for no apparent reason (no settings changed, no uncommon behavior like glitches, no lag). Using the new launcher (but was already using it before the crash). Tried reinstalling Optifine and it didn't work. There doesn't seem to be a crash log, or at least it doesn't seem to appear in the crash message.

**Comment by Vexima** [comment]
Please post your `latest.log`, found in `%appdata%\.minecraft\logs`.

**Comment by asheden** [comment]
[latest.log](https://github.com/sp614x/optifine/files/3356428/latest.log)

**Comment by Vexima** [comment]
Could you post the latest crash report in `%appdata%\.minecraft\crash-reports`?

**Comment by asheden** [comment]
[crash-2019-07-03_15.48.42-client.txt](https://github.com/sp614x/optifine/files/3356601/crash-2019-07-03_15.48.42-client.txt)

**Comment by Vexima** [comment]
Hmm, seems to be to do with Blaze3D. I don't know myself, maybe someone else could help?

**Comment by asheden** [comment]
I can, but I need Optifine because my specs are too low.

**Comment by LapisDemon** [comment]
Confirmed, strangely enough, I was able to login with OF 1.14.3 after installation, noticed emissive textures for blocks were not working anymore, and in order to make sure the fault is not on my side, I downloaded the latest 1.14.2-preview OF-version, as I knew emissive textures would work with that specific OF version.

Logged in with OF 1.14.2, confirmed emissive textures working, then tried to login again with the OF 1.14.3-version to make another proof screenshot, but then the crash happens each time I try to start OF 1.14.3, with the message:
**"The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/TextureUtil"**

I don't have any mods installed other than OF.

**Comment by sixteenhunnid** [comment]
I have the exact same problem. It started happening out of nowhere.

**Comment by sp614x** [comment]
`java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/TextureUtil` is caused by a wrong `launchwrapper` version.
Latest OptiFine installs and needs the `launchwrapper-of-2.1.jar`.
