### ISSUE TITLE
Block entity random entity texture resets to default when unloaded on a server

### ISSUE THREAD

**Issue by thebrickanator** [sp614x/optifine#2595]
I recently used the random entity feature to create a resource pack which changes the texture of shulkers when they are renamed. It works pretty seamlessly and is quite useful in single player but on a server the custom textures are only applied to the block immediately after placing it. When you try re-loading the chunk that the shulker box is in then the texture is reset to default. If someone else places the shulker or it is placed from a dispenser you also cant see the texture. 

I imagine this has something to do with how the server doesn't send the name of the shulker until the player opens the shulker, but I wonder if this is something that can be fixed in a future version of optifine or if there might be a workaround?

My resource pack can be downloaded here if you want to use it to test the issue: https://www.planetminecraft.com/texture_pack/sea-of-shulkers-customizible-shulker-boxes-over-1000-different-combinations/

I understand the random entity texture feature isn't designed for block entities but it would be great to have support for it on servers anyway since it is so close to working. Thanks :)

**Comment by SetantaLP** [comment]
It would be cool to have something like that, but the problem is, that the server only sends the information that a vanilla-client needs to render the world, and the name of a shulker-box (or chest or other inventories) is only relevant, when you open the inventory, which means it is not sent unless you open the inventory.
So there are two ways to solve that without building a server side counterpart for optifine: 
- Optifine request an inventory-open, when a chunk with blocks containing an inventory is loaded or a block containing an inventory is placed and remembers the custom names. But since that would even happen for such blocks far away from you, the server may see that as hacking attempt.
- The server sends the required packages to the client, but that might require a lot of bandwidth, and depending on the amount of inventories it would cause issues since you can't move when an inventory is open.

**Comment by thebrickanator** [comment]
I was worried that might be the case. Isn't there a feature in loot tables that let's you retrieve the names of the items that the block would drop? Or only the type of item? I have never used it I just remember hearing about it from sethblings videos. 

Other than that it might be good enough if optifine is updated to refresh the texture as soon as it receives the entity name (such as when it's opened) . That way I might be able to write a server plug in for it.

**Comment by SetantaLP** [comment]
Sadly loot tables are entirely server side, since their content (as well as the content of chests or of any other block containing an inventory, that is not currently opened by the player) is irrelevant for rendering the world in vanilla. Besides that, sending the contents of a chest would need additional bandwidth and it might be used for cheating.

Concerning texture-refreshing, when optifine receives the entity-name: it's basically what optifine does, when you open an inventory. The problem is, that the packet, that tells the client to open the inventory ui, doesn't contain any information about the block the inventory belongs to (unless the inventory belongs to a horse, then the packet contains an entityID see [wiki.vg](https://wiki.vg/Protocol#Open_Window)), since that's irrelevant for rendering the ui. So I assume that optifine just associates the name of the ui with the block you clicked before the packet arrived.
So the only way to associate the names with the blocks besides from clicking them manually would be using a Plugin channel (see [wiki.vg](https://wiki.vg/Plugin_channels)), which is registered by optifine to notify the server that it sending the data would be needed and if the server supports that, it would send names if there are any.

**Comment by sp614x** [comment]
Currently OF remebers the last clicked container and uses that when the open-gui packet comes.
Requesting an inventory-open on chunk load may also trigger the server cheat detection (the player opens a chest that is 200m away) and the player can be kicked.
There is no easy way to fix the problem until vanilla servers start sending more information on chunk loading.
