### ISSUE TITLE
[Suggestion] Allow block models to disable culling

### ISSUE THREAD

**Issue by NitroCipher** [sp614x/optifine#2598]
Block models should be able to disable block culling, using the additional line of `"culling": false`. It would be useful for model/resource pack makers

**Comment by MushirMickeyJoe** [comment]
But you can already disable culling on each individual face of a block model in vanilla Mc :f

**Comment by NitroCipher** [comment]
How?? I couldn't find any docs for it

**Comment by NitroCipher** [comment]
> But you can already disable culling on each individual face of a block model in vanilla Mc :f

I am talking about a block culling another block, IE: 
![2019-07-06_19 50 57](https://user-images.githubusercontent.com/11393734/60762512-dd640880-a027-11e9-9c74-881d58fcbf5d.png)

**Comment by sp614x** [comment]
This is not going to happen because it changes the light propagation. 
Light propagation is part of the game mechanics (mob spawning). It is also very expensive to relight all chunks after a resource pack change.

**Comment by NitroCipher** [comment]
Ah, interesting. Thanks for the info!

**Comment by Darkar25** [comment]
I don't think you can entirely disable face culling but in theory you can use a little trick to make the culling less of a problem...You can make 6 copies of your model in the same place and for each copy of each face you set the different culling side...This way whichever side gets culled another side takes its place...Until, of course, all sides get culled - then your model would disappear...
However this approach is VERY resource intensive since you're making 6 copies of a model instead of 1 so i would not recommend it for models that might appear a lot in the game.
