### ISSUE TITLE
Mouse Sensitivity bug

### ISSUE THREAD

**Issue by SteelJim** [sp614x/optifine#2602]
So I was playing Minecraft 1.14.3 with the last optifine release when my mouse sensitivity started to bug. Sometimes it worked perfectly and suddenly i was doing random spins, it's as if the sensitivity of the mouse had suddenly tripled, and after that it worked back for a few seconds. I tried to delete the install and made a new one without optifine, and i didn't have te bug anymore. So i reintalled optifine, and the bug came back. Another strange thing is that i have like a fps drop when it starts spin randomy...
Here is the link of a video i made, so you can maybe have a look : https://youtu.be/anDhtqdAiUc
Thanks for helping me, and sorry about my bad english

**Comment by bogmire** [comment]
I am also experiencing this. It seems to occur when chunks are loading and/or generating.

**Comment by PseudoResonance** [comment]
Do either of you use a high poll rate mouse? Something greater than 125Hz? I have a 1000Hz mouse, and I discovered that high poll rates were causing problems for me, especially when combined with loading chunks. If this is your problem, unfortunately, the only solution seems to be to reduce the poll rate until it starts working normally. I personally only use 250Hz in Minecraft, but 1000Hz everywhere else.

**Comment by bogmire** [comment]
Yes, my mouse is set to 1000 Hz. I'll try reducing the polling rate, however it would be nice if this could be fixed. I don't experience the issue when playing without OptiFine.

**Comment by PseudoResonance** [comment]
Yes, unfortunately, it seems that OptiFine does slightly make the problem worse, however I was able to replicate it without OptiFine in certain conditions. As you can see here: https://www.minecraftforum.net/forums/support/java-edition-support/2876740-mouse-speed-sensitivity-erratic

However upon doing some searching, I found many other people are having this same issue and have also found the same conclusion. It seems it's a problem with Minecraft itself, and OptiFine is not to blame. Some changes made in OptiFine do appear to be making the problem more noticeable though, but this issue is also not exclusive to Minecraft, as many other games are affected similarly by high poll rate mice, as shown in the following links.
https://www.planetminecraft.com/forums/help/javaedition/mouse-jerky-fix-here-515428/
https://linustechtips.com/main/topic/1031704-mouse-polling-rate-causing-huge-lag
https://steamcommunity.com/app/222880/discussions/1/135509124604588121/

I've tried to look into what might be causing this issue, but I couldn't figure it out personally. It seems to be poor handling of screen updates when a cursor change is detected by the game however, as from what I could find, the game is called to update the screen every time a cursor change is detected.

**Comment by sp614x** [comment]
Looks like a vanilla bug.

Probably related:
https://bugs.mojang.com/browse/MC-124743
https://bugs.mojang.com/browse/MC-15120
https://bugs.mojang.com/browse/MC-120847

The LWJGL library is used to handle the mouse input. 
OptiFine can influence the system load (more/less CPU load) which could affect the mouse problem.
