### ISSUE TITLE
Geometry shaders still do not work on radeonsi (AMD Linux)

### ISSUE THREAD

**Issue by AsuMagic** [sp614x/optifine#2651]
[This issue](https://github.com/sp614x/optifine/issues/2359#issuecomment-511751963) seems to hint that packs involving geometry shaders should now work on non-nvidia hardware.

However, I still get an `GL_INVALID_OPERATION` error when trying to use the MollyRT shaderpack:
```
OpenGL API ERROR: 4 (GL_INVALID_OPERATION in glBegin(mode=GL_QUADS vs geometry shader input GL_TRIANGLES))
```

![Screenshot of F3 + error displayed in chat](https://cdn.discordapp.com/attachments/568523442652053525/602178797806288906/unknown.png)

Setup (snippet from `glxinfo`):
```
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.32.0, 5.2.1-4-tkg-pds, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.1.2
OpenGL core profile shading language version string: 4.50
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.1.2
OpenGL shading language version string: 4.50
```

Versions tested:
- OptiFine 1.14.3 HD U F2 pre2
- OptiFine 1.14.3 HD U F2 pre3
- OptiFine 1.14.4 HD U F2 pre1

People have been hinting that OpenGL 4.6 support has to be advertised, which appears to me to be unnecessary, but I tried to override the advertised version anyway using the `MESA_GL_VERSION_OVERRIDE=4.6` environment variable, which did not help.

**Comment by sp614x** [comment]
Can you post the error log or game output.
There should be more information about the error.

**Comment by AsuMagic** [comment]
Indeed, there are more errors beforehand. Some shaders seem to have failed to link, but I don't know if it is related.

[launcher_log.zip](https://github.com/sp614x/optifine/files/3413901/launcher_log.zip)

**Comment by sp614x** [comment]
The problem is most probably with the MollyRT shader pack.
It includes geometry shaders for the composite/deferred programs. Usually geometry shaders are not used in deferred/composite programs and the quad rendering is not prepared to deal with them there.

After the macro processing these shaders are most probably turning out to be dummys or empty. In this case it depends on the graphics driver how it would interpret the compilation of an empty shader.

A smart driver should detect that the shader is empty and not turn the geometry stage on. A not so smart driver could turn the geometry stage on and use default processing which would conflict with the quad rendering.

**Comment by AsuMagic** [comment]
OK, forwarded the issue to MollyRT's developer. Thanks!

**Comment by sp614x** [comment]
One of the last versions added fix for geometry shaders in composite/deferred programs.
This should fix the problem.
