### ISSUE TITLE
[Suggestion] CTM Block Model Support

### ISSUE THREAD

**Issue by AnotherWryTeenager** [sp614x/optifine#2765]
Right now, CTM only allows us to specify replacement textures for blocks. It would be great if we could specify replacement *models*, similarly to CIT. With that we could create custom blocks, and structural variations on blocks independent of texture.

I realize there's a risk of errors or conflicts with face culling, but it should be up to us to avoid/fix those, and I don't believe it should be a reason to forego the feature entirely

**Comment by sp614x** [comment]
The biggest limitation of custom models is that it is not possible to replace a full cube model with a non-full model due to face culling and light propagation.
Only non-full models could be connected. Most of the blocks that would benefit from this are already connected (fences, glass panes, walls). There are very few blocks (if any) that have non-full models and that can be connected in a useful way.
