### ISSUE TITLE
Clock isn't working when Optifine is enabled

### ISSUE THREAD

**Issue by smoochiepook** [sp614x/optifine#2774]
I'm having a problem with my clock texture whenever I have Optifine enabled. I'm running it with Forge, and everything else works except for the clock unless I run Forge or Optifine by itself. Together, though, I can only see the actual time of day when I'm holding the clock. But the icon in my inventory is glitched.
![image](https://user-images.githubusercontent.com/54123173/63060423-35f8b200-bec0-11e9-8a2a-5a39df57db19.png)

**Comment by AndanteDevs** [comment]
Theorised explanation:
> I believe model overrides are broken in OptiFine combined with Forge right now in the hotbar, item frame etc

https://discordapp.com/channels/423430686880301056/423433009568546827/611328848503636077

**Comment by smoochiepook** [comment]
Is there a way I can manually/temporarily fix it by myself?

**Comment by AndanteDevs** [comment]
Not as far as I'm aware, I just stopped using OptiFine with Forge until it gets fixed

**Comment by sp614x** [comment]
Which Forge and OptiFine version?
Can you post a F3 screenshot?

**Comment by ThisIsMyDemoOsu** [comment]
> Which Forge and OptiFine version?
> Can you post a F3 screenshot?

I'm using the latest version of both Forge, and OptiFine 1.14.4 HD U F4 pre3. The bug still persists here. Not just the clock, but the compass is also affected; it's always pointing towards North, rather than the world spawn point. I do not believe F3 screenshot helps, but here you go.

The image is supposed to show the compass pointing South, towards world spawn point. Instead, it points North.
![2019-09-02_18 13 21](https://user-images.githubusercontent.com/33790088/64137511-7eafd680-cdad-11e9-9205-515bf91fcb3a.png)
![2019-09-02_18 13 45](https://user-images.githubusercontent.com/33790088/64137512-81aac700-cdad-11e9-9cf0-93d966905eaf.png)

**Comment by FireZtreaM** [comment]
Any news about this issue?

**Comment by sp614x** [comment]
Fixed in latest preview.
