### ISSUE TITLE
CEM mod

### ISSUE THREAD

**Issue by SoniEx2** [sp614x/optifine#288]
The `%` operator is missing.

**Comment by sp614x** [comment]
The expressions are operating only on float values and % is not defined for floats.
It could be simulated like:
`x % y = ((x / y) - (int)(x / y)) * y`

**Comment by SoniEx2** [comment]
What about [`x % y = x - floor(x / y) * y`](http://www.lua.org/manual/5.1/manual.html#2.5.1)?

**Comment by sp614x** [comment]
Practically the same, but it does not work for negative X.
First version works identical to % for negative numbers.

**Comment by SoniEx2** [comment]
The Lua version is saner than the Java version.

**Comment by SoniEx2** [comment]
Meh, couldn't find it...

**Comment by SoniEx2** [comment]
Thanks to the Lua mailing list I found these:

http://hisham.hm/2015/04/18/a-small-practical-example-where-luas-behavior-is-better-than-cs/ (this is the one I was talking about)

https://www.microsoft.com/en-us/research/publication/division-and-modulus-for-computer-scientists/

**Comment by sp614x** [comment]
Not sure which ose should be implemented. 
The Java version is compatible with most existing C-like languages.
The Lua version is more practical.
Maybe implement "%" as Java defines it and add "mod" as the Lua version?

**Comment by SoniEx2** [comment]
Lua has [math.fmod](http://www.lua.org/manual/5.3/manual.html#pdf-math.fmod) as Java's (well C's really) `%`. I personally prefer the idea of `%` as Lua defines it and `mod` as Java defines it.

**Comment by sp614x** [comment]
For me defining "%" like Java and "mod" like Lua is the better way. Most other languages (except Lua) define "%" in the C/Java way (the result sign [differs a bit](https://en.wikipedia.org/wiki/Modulo_operation)).

Most of the time "%" is used as "x % y == 0" in order to trigger an action every "y" steps. For this usage both implementation are working correctly and the practical difference will be minimal.

Java has the Lua mod as [Math.floorMod()](url) so I could use "fmod" for it.

**Comment by sp614x** [comment]
Added:
- operator "%" - similar to Java "%"
- function "fmod(x,y)" - similar to Math.floorMod()
