### ISSUE TITLE
ZGC with minecraft?

### ISSUE THREAD

**Issue by RoiEXLab** [sp614x/optifine#2904]
I'm not sure if this is the right place to ask this, but since it's a rather technical question I thought I should try anyways:

So, with Java 12 came a new experimental [Garbage Collector ZGC](https://wiki.openjdk.java.net/display/zgc/Main).
From the OpenJDK Page:

> **The Z Garbage Collector**, also known as **ZGC**, is a scalable low latency garbage collector designed to meet the following goals:
> - Pause times do not exceed 10ms
> - Pause times do not increase with the heap or live-set size
> - Handle heaps ranging from a few hundred megabytes to multi terabytes in size
> 
> At a glance, ZGC is:
> - Concurrent
> - Region-based
> - Compacting
> - NUMA-aware
> - Using colored pointers
> - Using load barriers
> 
> At its core, ZGC is a **concurrent** garbage collector, meaning all heavy lifting work is done while **Java threads continue to execute**. This greatly limits the impact garbage collection will have on your application's response time.

For me this sound like the exact kind of GC that a game like minecraft would need. I would've tried it, but unfortunately this GC is currently only available on linux-64 systems, and going into a VM for performance testing seems weird.

So I'm asking for the expertise of @sp614x and other people with experience in that field:
**Do you think that using ZGC will boost performance a little bit in the long run?**

**Comment by Barteks2x** [comment]
I haven't actually tried ZGC myself, but I tried `shenandoah` GC, which has similar goals, but works in a bit different way. But to my knowledge they have somewhat similar tradeoffs. So I expect similar results with ZGC in Minecraft.

For 1.12.x, shenandoah is a net negative on the client with normal sized heaps. Generally, most of the remaining ingame frame time spikes just aren't caused by GC. And both of those GC algorithms have up to 20% overhead in typical cases.

On 1.14.x it works quite well, but still can be a net negative in terms of FPS on slower machines. I can see it being useful on huge heaps, with high core count systems. It might also run the game  with heap size shockingly close to the actual used heap and still get somewhat acceptable performance. But as said, it does come at overall average performance hit.

For now, I think G1 is the best general case GC we have, especially for server. Shenandoah and ZGC may be useful on the client, but not on all computers.

**Comment by sp614x** [comment]
Both ZGC and shenandoah are interesting as they could eliminate or decrease GC lag spikes. Currently the GC lag spikes are the only lag spikes that can't be directly controlled by the code. It is only possible to reduce the memory allocation as much as possible and hope that the GC can do most of the work in parallel.

As general performance they are probably a bit slower that G1 due to more overhead (colored pointers, memory bariers, etc.). 

To be effective they would need a reduced allocation rate, which is not the case with vanilla. For example vanilla 1.14.4 would happily allocate 100+ MB/s when loading chunks.

From the shenandoah  wiki:
```
Concurrent GC like Shenandoah implicitly relies on collecting faster than 
application allocates. If allocation pressure is high, and there is not enough 
space to absorb the allocations while GC is running, Allocation Failure would 
eventually happen. 
```

If the allocation rate is low to moderate and there are enough CPU resources (free cores) on which the GC could run, both could be able to eliminate GC lag spikes at the expense of slightly reduced performance.

**Comment by LifeIsStrange** [comment]
Java 14 will reach final release candidate in 3 days, and will bring ZGC on Mac and Windows :)
It will be benchmarck time!
