### ISSUE TITLE
Unable to make CTM Overlay Transitions work with modded blocks 

### ISSUE THREAD

**Issue by nihiluis** [sp614x/optifine#2939]
I'm using this config on 1.12.2,newest Optifine. But I'm unable to make them appear. Am I doing it right or is it perhaps not supported?

```
matchBlocks=gss-decor:ges_sand_nihan 4
method=overlay
tiles=0-16

connect=block
#connectTiles=ges/ges_grass_nihan_top gss-decor:ges_grass_nihan_top minecraft:ges/ges_grass_nihan_top gss-decor:ges/ges_grass_nihan_top ges/ges_grass_nihan gss-decor:ges_grass_nihan minecraft:ges/ges_grass_nihan gss-decor:ges/ges_grass_nihan
connectBlocks=gss-decor:ges_grass_nihan
tintIndex=0
tintBlock=2
```

**Comment by xemnes** [comment]
i have the same issue


`matchBlocks=conquest:stone_full_23
method=overlay
tiles=1-17
connectBlocks=grass
faces=top
tintIndex=1
tintBlock=minecraft:grass
layer=cutout`

it seems to be an issue with matchBlocks and only breaks if using the overlay method, all other ctm methods work fine with matchBlocks for modded blocks.

i know my format is correct, because if i used matchBlocks=stone , it works just fine.
