### ISSUE TITLE
Forge + OptiFine 1.14.4 using classpath instead mods folder

### ISSUE THREAD

**Issue by Nik-mmzd** [sp614x/optifine#2957]
Due to some reasons I need to add OptiFine to 1.14.4 Forge not using mods folder, but using classpath, but I do know is it possible at all, what libraries I should add with OptiFine and what main class I should specify

I know it's not an issue but I need a bit help with it
Thanks

**Comment by Nik-mmzd** [comment]
I thought I got it but...
If I simply add OptiFine to classpath, I getting [this crash](https://www.youtube.com/watch?v=YuNQ_atHC0E) (and all works fine if I add OptiFine to mods folder)
WAIDW?

**Comment by Barteks2x** [comment]
This is probably not something that can be done. AFAIK, Forge doesn't really support loading mods from classpath anymore (in large part due to changes for java9+ compatibility). If you have to load mods from your own location, you could probably write a custom mod locator for modlauncher and add that into classpath. You probably won't get much help with that beyond what I said here.

**Comment by Cadiboo** [comment]
OptiFine loads fine from the libs folder using my [OptiFineDeobf](https://github.com/Cadiboo/OptiFineDeobf)

**Comment by Barteks2x** [comment]
You can't legally redistribute the SRG mappings @Cadiboo

**Comment by Cadiboo** [comment]
> what does deobfuscation have to do with loading from classpath?

I'm not sure what the link between them is, but using my tool works so I shared it. 
> You can't legally redistribute the SRG mappings

I didn't know that, I'll change the tool's mappings to work like BON2.
