### ISSUE TITLE
[OptiFine 1.10.2 HD U D1] - Messy rendering AE2 and RFTools

### ISSUE THREAD

**Issue by ozhound** [sp614x/optifine#298]
Hi, I have been bug testing AE2 and am a tester for the 'All The Mods Modpack'. Due to large modpack, many of our users require optifine. Prior to the latest version, it was unusable with the pack. Now it is 99% working which is fantastic.

I have posted an issue on the AE2 github [here ](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2489) and was wondering if some small collaberation could occur to close out these last few issues. 

Thanks for your Time

Oz

**Comment by mindforger** [comment]
to add a bit more insight

AE2 uses custom uv lightmaps to make parts of the block glow at night
and RFTools combines static and animated textures

there are also other mods doing funny stuf to get around the blockmodel texture bindings

**Comment by sp614x** [comment]
Currently OptiFine imposes some restrictions on the rendering:
- the Forge lighting pipeline is disabled because it breaks too many features
- when Shaders are active, only the default vertex formats should be used. Custom vertex formats can lead to crashes or broken rendering
- low-level manipulations of the VertexBuffer contents may fail when Shaders, AA or AF are active
- FastRender and Shaders are not compatible with some post-processing shaders

**Comment by sp614x** [comment]
How exactly are the custom UV lightmaps implemented?

**Comment by mindforger** [comment]
i have no idea :D i am not that deep into their code as it is absolutely overwhelming :D

but let me try to summon an @yueh

**Comment by yueh** [comment]
We basically have our own model loader to extend the normal models by uv lightmaps. Which then hands them of to the forge lighting pipeline. It might even use a custom vertex format. I had to look into it, but the graphics stuff is clearly not in my field. 

So violating 1) and most likely 2). 

Maybe 3) in some rare case. Iirc we extract some data from the unpacked quads for facades. So we also make use of forge not packing them and wasting tons of memory... But I might be completely wrong here.

**Comment by shartte** [comment]
It's creating it's own VertexFormat during model-loading. I am trying an adaption where it force-switches to DefaultVertexFormat.BLOCK instead of doing that. It'll lose the normals, but since it's fullbright it *shouldn't* matter anyway. Sadly there's no "default" VertexFormat that extends ITEM with TEX_2S, since we use that to force our own lightmap coordinates into the quad.

**Comment by sp614x** [comment]
Further discussion: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2489
