### ISSUE TITLE
[1.12.2] Please Provide a Reasonable ETA of the Crash fix.

### ISSUE THREAD

**Issue by Speiger** [sp614x/optifine#2990]
Reference to #2975

**Comment by Studio528-real** [comment]
you're an idiot, i hope you know that. @sp614x please also close this and if you want and have time to bother close his other new ones if he creates more

**Comment by GregoriusT** [comment]
Ugh why is this an Issue? Why is Optifine split into two Versions in the first place? Sure new Features could always be Experimental Branch but Bugfixes would be immoral to not include in the main branch. Optifine is a Clientside ONLY mod, people dont even need to sync up Mods with a Server, why do you even need to hide Bugfixes from people that way, wouldn't an instant release the time the bugfix happens be much more beneficial for literally everyone?
Also people using Modpacks never even get the opportunity to read big bold warnings on Posts, and then dont want to waste their time reading the List of potential ways to fix it, they just want to get the problem solved instead of having people bicker at each other for no reason because one withholds simple fixes from the general public.

**Comment by sp614x** [comment]
ETA is when it is ready, literally.
Personally I wouldn't be surprised if it appears sometime next week.

**Comment by Speiger** [comment]
ok see ya in a week.

**Comment by Speiger** [comment]
Also @sp614x could you keep this issue open until the release is out please.

**Comment by sp614x** [comment]
This is a question about ETA and such it is resolved.
The #2975 "Release OptiFine 1.12.2 F4" is still open.

**Comment by Speiger** [comment]
@sp614x then unlock #2975 until the release is out.
The point is: You either remove or disable any active participation from people.
Right now you are only adding distrust to your word. So to provide trustablity. Leave something open that shows ok I am working on this give me just some time.
Not: Its done in a week stop sending me messages.
And this only causes more issues to show up.

**Comment by sp614x** [comment]
It is locked so I can concentrate on releasing 1.12.2 instead of being distracted by drama.

**Comment by Speiger** [comment]
Then leave this issue "Open" and not close it.
Again provide trust. Or should I open another issue that is called: "Opend Until next week where Optifines 1.12 patch comes out"?

**Comment by Speiger** [comment]
TL:DR:
Leave 1 commentable issue open related to this. Thats what I am asking you. Nothing more nothing less.
The moment this happens I am stop commenting until end of next week.

**Comment by Speiger** [comment]
simple as that @sp614x

**Comment by Speiger** [comment]
@sp614x since you are still working on the "1.12" fix. here is something else you can fix that i have to do just so your "PreView" patch does not crash.

```
	@Override
	public void loadAllWorlds(String saveName, String worldNameIn, long seed, WorldType type, String generatorOptions)
	{
		SaveHandler handler = (SaveHandler)getActiveAnvilConverter().getSaveLoader(saveName, true);
		if(handler.loadWorldInfo() == null)
		{
			handler.saveWorldInfo(new WorldInfo(settings, worldNameIn));
		}
		super.loadAllWorlds(saveName, worldNameIn, seed, type, generatorOptions);
	}
```
Aka your server crashes if worldInfo is null on loadAllWorlds (note that MC itself declares the function as nullable) So could you fix that too while you are at it.

**Comment by Speiger** [comment]
Good

**Comment by sp614x** [comment]
Fixed loadAllworlds() in pre12.
