### ISSUE TITLE
Swamp does not work properly in the water colormap

### ISSUE THREAD

**Issue by bageldotjpg** [sp614x/optifine#3000]
When using the water colormap, Swamp is biome id 6 but the 6th line doesn't work for swamps, it only works if you put it on the 2nd line. But if you use the 2nd line then it affects plains as well as swamps

**Comment by InSimpleTermsJordan** [comment]
This is actually due to swamps using a hard-coded color in vanilla.
https://minecraft.gamepedia.com/Biome#Swamp_color

**Comment by bageldotjpg** [comment]
Hmm. I don’t understand why it works when using Plains though

**Comment by InSimpleTermsJordan** [comment]
Because most biomes (including Plains) use the color maps in the resource pack for their colors
https://minecraft.gamepedia.com/Biome#Biome
![2019-10-23 05-31-24 612 JKPwnage PWNSTATIONV1-1- 2874x3793](https://user-images.githubusercontent.com/6912435/67360991-02c04800-f52d-11e9-9f84-3ca379917d69.png)

**Comment by bageldotjpg** [comment]
I mean don’t understand why the swamp water changes color when I change the plains water color... that doesn’t make any sense

**Comment by InSimpleTermsJordan** [comment]
Because, as the article says, 

> the color of the water in swamps is always multiplied by a very light green tinge (0xE0FFAE).

It's multiplying the color, not overwriting it. Therefore the swamp water color is still partially dependent on the color map supplied by the resource pack. Changing the default water color affects the swamp water color for the same reason changing a variable in an equation will give a different result.
