### ISSUE TITLE
No very low 16:9 resolutions available.

### ISSUE THREAD

**Issue by TrickyBU** [sp614x/optifine#3032]
Was hoping to run the game at about 848x480p so I could give path traced shaders a go at 60 FPS, but at around that screen size there are no options that support 16:9. Really need just a custom resolution option. I understand Optifine pulls available resolutions from the LWJGL library, but I have played at (very) custom resolutions before in other games. I know my screen supports them.

**Comment by SetantaLP** [comment]
The problem is: Optifine has to rely on what the underlaying software reports, no matter if they are complete or correct, because Optifine has no possibility to get these information, except asking the underlying software. So if the results are incomplete or incorrect, it's up to the devs of this software (in this case LWJGL) to fix that.
And in the meantime I'd recommend to check if the graphics driver allows you to set custom resolutions for certain programs, and if not, change the window resolution via the launcher (might not work in fullscreen and might result in a very small window) or just change the screen resolution, while you test the shaders.

**Comment by sp614x** [comment]
The LWJGL library provides a list of the supported resolutions, this comes from the graphics driver. Some drivers allow the definition of custom resolutions.
Another alternative would be to decrease the render quality to 0.5x, this effectively uses a half resolution.
Options -> Video Settings -> Shaders -> Render Quality
