### ISSUE TITLE
1.8.9 block models don't work (not added yet?)

### ISSUE THREAD

**Issue by MastaNub** [sp614x/optifine#3084]
CEM works just fine but trying to use custom block models just doesn't work at all.

**Comment by sp614x** [comment]
CIT custom models were fixed, but the transforms are all wrong. Not sure if this is due to a bug or model format changes between 1.8.x and 1.9.x.

1.9.4
![image](https://user-images.githubusercontent.com/16635441/69355201-b11cf180-0c81-11ea-8af8-ef145e223548.png)

1.8.9
![image](https://user-images.githubusercontent.com/16635441/69355227-bb3ef000-0c81-11ea-8bfc-cee445a9e635.png)

**Comment by sp614x** [comment]
The 1.9.x transforms are different, 1.8.x models are not shown correctly in 1.9 and vice versa.

**Comment by MastaNub** [comment]
The issue is I couldn't get the custom block model to work at all.
I'm using this for the enchantment table and the .json is located in:
\assets\minecraft\models\block
https://pastebin.com/P3MqV7aE

**Comment by sp614x** [comment]
Fixed, coming in next preview.
