### ISSUE TITLE
I have an rtx 2080 xc but some texture packs still crash my game.

### ISSUE THREAD

**Issue by OdiousBotch** [sp614x/optifine#3092]
I don't understand what the problem is I have 24 gigs of ram and a rtx 2080 xc, I see people running these things in 4k 60fps with worse specs than me but I can't even load the game without it either crashing immediately, having white/green textures, or 1 fps with black and invisible textures. I've updated everything there is to update but no luck.

**Comment by sp614x** [comment]
Have you allocated more memory to minecraft?
Can you post the crash report or the error log?

**Comment by Nixuge** [comment]
To be more precise: 
He tried to run a 2048x texture packs and optifine couldn't load it (white textures only). he has 15gb of ram allowed so it's more than ok. he also tried to run it in vanilla but since vanilla only support packs up to 1024x it crashed instantly.
He also tried other packs. Most of them were working but one of them wasn't, it was Rudy 1024x (v02a). There were also white textures everywhere. This time, he tried on vanilla and it worked perfectly fine.

His specs:
Operating System
    Windows 10 Pro 64-bit
CPU
    Intel Core i7 4770K @ 3.50GHz    37 °C
    Haswell 22nm Technology
RAM
    24.0GB Dual-Channel DDR3 @ 801MHz (10-10-10-27)
Motherboard
    ASUSTeK COMPUTER INC. SABERTOOTH Z87 (SOCKET 1150)    33 °C
Graphics
    ED273UR (2560x1440@59Hz)
    4095MB NVIDIA GeForce RTX 2080 (EVGA)    30 °C

Logs files:
https://cdn.discordapp.com/attachments/646439196378267648/646441715418267658/latest.log (he has no graphics drivers at first, so this log is without graphics drivers)
https://cdn.discordapp.com/attachments/646439196378267648/646493295182348288/latest.log

He also tried to reinstall the nvidia drivers and java but nothing worked, still white textures

**Comment by sp614x** [comment]
The first errors in the log file are 
`OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Render buffer not bound.)`
it hard to say what went wrong.
Big resource packs are generally limited by the maximum supported texture size which is a fixed property of the GPU/drivers.
Running with shaders needs 3x more memory as they also need normal/specular texture atlases to be loaded.

**Comment by sp614x** [comment]
A 2k resource pack may reach the limits of both maximum supported texture size or maximum VRAM available. Disabling CTM may help with atlas texture size. Disabling Custom Sky, Random Entities, etc. may help with VRAM depending on whether the RP is using them.

**Comment by Nixuge** [comment]
What about the 1024x one? It's working fine on vanilla without any issue
