### ISSUE TITLE
Better coping of driver capabilities

### ISSUE THREAD

**Issue by Juesto** [sp614x/optifine#3127]
some things are known to not work properly due to lack of certain ogl features right?
well, why optifine doesn't inform so to the user or at least it is able to adapt and downgrade itself to a slower alternative?
prime example: say your driver compatibility doesnt allow geometry shaders; most users dont realize the importance of them and the fact that while not supported it is possible to up the feature level in linux
alternatively for those situations optifine could/should query the feature set available and disable/enable features based on that instead of erroring out easily

**Comment by sp614x** [comment]
Usually the errors when loading shaders are coming from the graphics drivers when compiling the shaders source and they look like:
```
ERROR: 0:243: '=' :  assigning non-constant to 'const float'
ERROR: 0:244: '=' :  assigning non-constant to 'const float'
ERROR: 0:567: 'texcoord' : undeclared identifier 
ERROR: 0:567: 'st' :  field selection requires structure, vector, or matrix on left hand side 
ERROR: 0:567: 'texture2D' : no matching overloaded function found (using implicit conversion) 
```
The dirver doesn't say explicitely "GL_EXT_gpu_shader4 not supported".
Detecting from the source what OpenGL features would be needed is virtually impossible.

Even if OptiFine could find what feature is missing, it is usually not possible to automatically replace it with another identical feature. The only exception is the "ARB/EXT/core" fallback which uses different names for the same functionality, so it isn't really interesting.

If OptiFine could report "GL_EXT_gpu_shader4 not supported", for the average user this would be useless because:
- he/she has no idea what this is
- switching driver OpenGL context is not something that is possible on Windows/Mac and not something that the average Linux user could do.

Which means it could only help expert users on Linux, and in this case they can just read the log and see what is the problem.

Geometry shaders have been in core OpenGL since 3.2 which was released in 2009 and before that they were available as extensions. Practically all GPUs that could run shaders (OpenGL 3.0) also support geometry shaders.

**Comment by Juesto** [comment]
then suggest users to utilize this unsupported method because mesa refuses to standardize it?
or better clarify the minimum feature support on the respective specifications section?
