### ISSUE TITLE
optifine breaks SCM

### ISSUE THREAD

**Issue by Joshwoo70** [sp614x/optifine#314]
this is caused by the rendering pipeline. more jnfo here : https://github.com/amadornes/SCM-Localization-Issues/issues/110

**Comment by sp614x** [comment]
The "com.amadornes.rscircuits.client.SimpleModelFontRenderer" tries to use OpenGL functions on the chunk building thread and crashes because the thread has no OpenGL context.
The chunk building threads does not have an OpenGL context and they can not use OpenGL functions, this limit comes from vanilla and OptiFine does not change it.

**Comment by sp614x** [comment]
The GlStateManager is NOT thread-safe and it should only be called from the main thread. Otherwise it may break and all kind of random bugs can appear (broken textures, OpenGL errors, etc).

The SimpleModelFontRenderer cache can be populated on the main thread and then it can be used on any other thread as the values are cached and no OpenGL calls will be made.
