### ISSUE TITLE
Add more entites to CEM

### ISSUE THREAD

**Issue by SaltyAimbOtter** [sp614x/optifine#3173]
CEM is currently lacking support for entities like trapped chests or all the different colored shulker boxes. 
This would e.g. allow for tons of different chest types in an RPG ⚔️

**Comment by IMPREZAS** [comment]
Great Idea

**Comment by NitroCipher** [comment]
Trapped chests currently share CEM with default chests btw

**Comment by D3monPixel** [comment]
Actually... https://discordapp.com/channels/423430686880301056/425702172219408385/658286214046023711

Chest types can be differed. That model is by Toxteer from the Optifine Discord.

**Comment by NitroCipher** [comment]
Waiting for confirmation, but that i believe is a single model, just with textures that have invisible components

**Comment by Toxteer** [comment]
I have already brought this up in the optifine discord but since we talk about adding more entities to cem I would like to see models for creeper, zombie and wither skeleton skull block. (head_creeper, head_zombie, head_wither_skeleton)
![optifine](https://user-images.githubusercontent.com/59182487/71382670-32490a80-25d9-11ea-8744-685e3dc2cb87.png)

**Comment by ewanhowell5195** [comment]
extra models have either been added, or it is now possible through the random entity models feature using block detection
