### ISSUE TITLE
Invalid Program issues on Linux

### ISSUE THREAD

**Issue by MoriyaShiine** [sp614x/optifine#3223]
Using Arch Linux with the current latest mesa drivers (19.3.2) and any shader (I used BSL in the screenshot), I get 3 invalid program errors. The game doesn't crash, but it looks a bit odd (bright?) and the shadows are really jumpy based on my position. GPU is an AMD 5700 XT. This also happens on 1.12.2, where it also tells me I get an invalid operation error (1282).

Screenshots of the game and my settings (at the bottom) are provided
![2020-01-10_19 18 27](https://user-images.githubusercontent.com/45156123/72196549-a0197280-33de-11ea-80ac-2bce66cf65f5.png)
![2020-01-10_19 19 51](https://user-images.githubusercontent.com/45156123/72196551-a14a9f80-33de-11ea-9b07-96f657382f49.png)

**Comment by Barteks2x** [comment]
I am not optifine developer and the following is mostly frpm.my previous experience: 

Generally a lot of shader don't work correctly with mesa. And I'm sure mesa developers would blame it on shaders and shader developers on mesa. This is unlikely something optifine can fix. This has to be fixed in the shaders.

**Comment by QuImUfu** [comment]
Some shaders work flawlessly. In general, mesa works if the shader dev does not do wanky, untested things (most do). 
These errors are mostly detected by glslangValidator as well, which should enable developers to find and fix them regardless of their preferred platform. 
Mostly these bugs can be fixed by looking at the errors mesa (or glslangValidator) give.  
In the BSL shader these are:
error1&4:
```
Shader info log: /shaders/world0/gbuffers_terrain.vsh
1:48(9): error: `return' with wrong type int, in function `calcLavaMove' returning float
Shader info log: /shaders/world0/shadow.vsh
error: `return' with wrong type int, in function 'calcLavaMove' returning float
```
is fixed by changing mentioned function in /lib/vertex/waving.glsl to `return 0.0` (float) instead of `return 0` (int)



error2&3: (more cryptic, took me a while)
```
Shader info log: /shaders/world0/gbuffers_basic.vsh
0:23(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end
Shader info log: /shaders/world0/gbuffers_basic.fsh
0:38(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end
```
is fixed by lookoing at the mentioned lines (23/38)
```
#ifdef MC_GL_VENDOR_INTEL
varying vec4 color;
#else
flat varying vec4 color;
#endif
```
and knowing that intels driver are more strict, and things required for them will likely be required by mesa too. Soo, either do:
```
#ifdef MC_GL_VENDOR_INTEL
varying vec4 color;
#else
#ifdef MC_GL_RENDERER_MESA
varying vec4 color;
#else
flat varying vec4 color;
#endif
#endif
```
or, because NVIDIA is likely the only "special snowflake" that supports this properly:
```
#ifndef MC_GL_VENDOR_NVIDIA
varying vec4 color;
#else
flat varying vec4 color;
#endif
```

Done. BSL works without error in world0. Do the same for the others.

**Comment by MoriyaShiine** [comment]
Thank you!
