### ISSUE TITLE
[1.15.2] Static burning up animations

### ISSUE THREAD

**Issue by Pr0vinciano** [sp614x/optifine#3296]
I have all the animations and particles on and the animation of the burning mobs is freezing

![2020-02-13_18 48 53](https://user-images.githubusercontent.com/61030563/74481806-1f90da80-4e92-11ea-9717-4c48b1627028.png)

**Comment by TheRSC** [comment]
I was about to post on this but it seems I was beaten to it. This is due to Smart Animations being set to ON. When it is set to ON, objects such as flaming Arrows or Mobs will have a non-animated Fire texture.

Video of Arrow Fire with this bug:

https://cdn.discordapp.com/attachments/677635928860131328/677636133236113477/video0.mov

**Comment by sp614x** [comment]
Fixed, coming in next preview.
