### ISSUE TITLE
Bugs (1.15.2 HD U G1 pre1)

### ISSUE THREAD

**Issue by KotoHacker** [sp614x/optifine#3312]
CIT:
In the inventory of the model with its own shape, and when you hold in your hands or put on an object, the model does not change. The same situation with armor. With PNG changes no problems.
https://imgur.com/a/RMtbTX4 (before 1 screen)

Simple:
+ When you open the fence appears X-Ray (first screen https://imgur.com/a/RMtbTX4 )

**Comment by dietergandalf** [comment]
![2020-02-14_10 03 40](https://user-images.githubusercontent.com/58730936/74517043-c23c6e00-4f11-11ea-8270-d12e32e4f2f5.png)
![2020-02-14_10 03 53](https://user-images.githubusercontent.com/58730936/74516907-8a352b00-4f11-11ea-9a79-cae76bb8157b.png)
![2020-02-14_10 03 47](https://user-images.githubusercontent.com/58730936/74516912-8bfeee80-4f11-11ea-831f-e5f5c2bc038a.png)
![2020-02-14_10 03 50](https://user-images.githubusercontent.com/58730936/74516919-8dc8b200-4f11-11ea-83e4-b314ec6e4202.png)
Sometimes when placing or destroying a chest the game looks strange.

**Comment by TheLindblomer** [comment]
This issue is occuring with my stone brick building as well; walls disappear adjacent to the placed block and the rainbow's are everywhere
![2020-02-15_12 26 13](https://user-images.githubusercontent.com/61082616/74587255-96dc8080-4ff0-11ea-99b7-4ff05940e284.png)
![2020-02-15_12 26 02](https://user-images.githubusercontent.com/61082616/74587256-980dad80-4ff0-11ea-91f0-11481972c29a.png)
![2020-02-15_12 26 02](https://user-images.githubusercontent.com/61082616/74587257-99d77100-4ff0-11ea-8518-6d7180cce866.png)
![2020-02-15_12 26 13](https://user-images.githubusercontent.com/61082616/74587260-9c39cb00-4ff0-11ea-9c63-b971c0a80146.png)

**Comment by sp614x** [comment]
Should be fixed in pre3.
