### ISSUE TITLE
Strange light shards!

### ISSUE THREAD

**Issue by katkins99** [sp614x/optifine#3356]
Hey! I'm using OptiFine 1.15.2 HD U G1 pre2 and have encountered the issues pictured below and it seemed to toggle when I placed blocks but only in a certain position! 
Hope this helps and thanks for your continued hard work on this mod! 
![2020-02-16_20 12 06](https://user-images.githubusercontent.com/61123533/74611958-b65ed080-50f8-11ea-9897-782403550486.png)
![2020-02-16_20 08 19](https://user-images.githubusercontent.com/61123533/74611961-b8c12a80-50f8-11ea-9b8d-7a8cf5ffff59.png)
![2020-02-16_20 11 49](https://user-images.githubusercontent.com/61123533/74611962-b9f25780-50f8-11ea-8a0b-af6bb4788fc4.png)
![2020-02-16_20 11 52](https://user-images.githubusercontent.com/61123533/74611963-bb238480-50f8-11ea-893a-3fab2f57b770.png)
![2020-02-16_20 11 54](https://user-images.githubusercontent.com/61123533/74611965-bc54b180-50f8-11ea-8a35-039421d6d0ee.png)
![2020-02-16_20 11 59](https://user-images.githubusercontent.com/61123533/74611966-bd85de80-50f8-11ea-9658-463559f59955.png)
![2020-02-16_20 12 00](https://user-images.githubusercontent.com/61123533/74611969-bf4fa200-50f8-11ea-9246-4349d158e78c.png)
![2020-02-16_20 12 03](https://user-images.githubusercontent.com/61123533/74611970-c1196580-50f8-11ea-9e19-054fe70ac998.png)

**Comment by opysium** [comment]
yes it's a general bug, i have too. can you send your screenshot of all video settings tabs to this issue?
note: i didn't test it on pre3 yet

**Comment by GuardianGM** [comment]
There’s my settings. I hope these help. Susan Sent from Mail for Windows 10 From: opysiumSent: Monday, February 17, 2020 2:22 PMTo: sp614x/optifineCc: GuardianGM; ManualSubject: Re: [sp614x/optifine] Strange light shards! (#3356) yes it's a general bug, i have too. can you send your screenshot of all video settings tabs to this issue?note: i didn't test it on pre3 yet—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by NitroCipher** [comment]
Resend of previous message:
> yes it's a general bug, i have too. can you send your screenshot of all video settings tabs to this issue?note: i didn't test it on pre3 ye

**Comment by asbyth** [comment]
they replied to the github email w/ something quoted in the email lol

**Comment by GuardianGM** [comment]
Yeah. . . . as requested? Sent from Mail for Windows 10 From: asbythSent: Monday, February 17, 2020 7:30 PMTo: sp614x/optifineCc: GuardianGM; ManualSubject: Re: [sp614x/optifine] Strange light shards! (#3356) they replied to the github email w/ something quoted in the email lol—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by asbyth** [comment]
bro you're just giving css "settings"

**Comment by GuardianGM** [comment]
> they replied to the github email w/ something quoted in the email lol

Yeah, and? I'm new to this and simply trying to let the developer know of the bugs. I did what they asked for.

**Comment by NitroCipher** [comment]
Reply on the github page itself, not through the email. It is filling up the comments with css spam

**Comment by sp614x** [comment]
Should be fixed in pre3.
