### ISSUE TITLE
1.11_A2_pre Clouds appearing through solid blocks (Shaders) + CIT

### ISSUE THREAD

**Issue by sixfootblue** [sp614x/optifine#336]
I tried using shaders with the latest preview version, and the default minecraft clouds are appearing through all solid objects.
https://gyazo.com/bcc27030284a80fa0de41061d9df6238
https://gyazo.com/26e77e690c0227e4a4b65313a434e6b3

Also has CIT been added to the new version yet? I've been hesitant to ask because I wasn't sure if it was and just isn't working, or if you just have yet to implement it.

**Comment by Strum355** [comment]
Dont use default minecraft clouds with shaders. 9/10 theyre not supported

**Comment by sp614x** [comment]
Most shader packs do not support vanilla clouds, so they turn them off.

**Comment by Builderb0y** [comment]
Clouds don't work even with shader packs that DO support them, like mine. Through experimentation, it seems that this issue occurs whenever gbuffers_clouds draws to any buffer EXCEPT gcolor. When drawing to gcolor it works fine, but this isn't possible in my shader pack for many reasons.

[Here](https://www.dropbox.com/s/338bubjg90pmq3t/Cloud%20bug.zip?dl=0) is a simple shader pack that demonstrates the issue. All it does is sample the textures given to it, and draw them. Only "special" things it does is draw clouds and water to the composite buffer, and everything else to gcolor. The composite buffer is then mixed with everything else in the composite program, and will vary the opacity with time to make it more obvious what is and isn't in there.

You'll notice that stained glass/water/etc... will stop rendering behind walls just fine, despite being rendered on top of everything else. Clouds on the other hand do not, despite doing almost the exact same thing source code wise ([screenshot](http://i.imgur.com/aSPjO8J.png)). The only difference between clouds and water is that clouds don't use lightmap data since it isn't relevant for them.

Interestingly though, clouds do "block" terrain correctly, as in: they're opaque if your Y position is less than ~128, and terrain stops rendering behind clouds if the clouds really are in front. Also interesting is that if your Y position is greater than ~128, clouds do successfully stop rendering in front of things as they should.
