### ISSUE TITLE
[1.15.2] Bug: Pistons, levers and light from redstone lamps do not update correctly when Biome Blend is enabled

### ISSUE THREAD

**Issue by VincyZed** [sp614x/optifine#3403]
So it took a while to find but I think I finally got it. Basically, light from redstone lamps, pistons and their pushed blocks, levers (and maybe more stuff too) do not visually update correctly when Biome Blend is set to anything more than OFF.

This is a demo I recorded with some AB testing showing this off clearly:

https://youtu.be/LIwcBP7BZkY

Note that there are no frame drops whatsoever and that the server is not lagging at all (running @ 20 TPS pretty stable, as demonstrated by the regularity of the music coming from the noteblocks)

The behavior is not always as pronounced. This is probably worst case scenario from what I've seen. I think it might do it more when the player is moving (maybe).

After lots of AB testing, this does NOT happen in vanilla, no matter what the value of Biome Blend is set to.

I haven't found any parameter other than Biome Blend that affect this behavior. I also haven't tested this on any other world yet other than this one.

I'm running the latest public preview build.

Thanks a lot for the great work! :)

**Comment by sp614x** [comment]
The higher values for Biome Blend only slows down the chunk rebuilds and make the issue easier to notice. Vanilla forces all the chunks around the player to update at the same time which may produce a noticeable lag spike. OptiFine may distribute the immediate updates between several frames in order to smooth the lag spike and to make it less noticeable.
