### ISSUE TITLE
[1.15 Preview 6] Coordinates choppy in optifine compared to Vanilla in the F3 menu

### ISSUE THREAD

**Issue by Naeqirelle** [sp614x/optifine#3409]
So i've tested this between optifine 1.15 Preview 6 and vanilla 1.15 the coordinates when moving in a single direction and multiple directions seem to be choppier than in vanilla 1.15 inside the F3 menu.

to reproduce this simply open up vanilla 1.15 and open up the F3 menu and look at a certain number when you move in one direction, you will notice that in optifine it's choppier than it is in vanilla.

also note this isn't a framerate issue

**Comment by sp614x** [comment]
OptiFine updates the coordinates in the F3 menu 10 times per second so they are still readable.
Vanilla updates them once per frame which makes them unreadable when they are changing too fast.

**Comment by Naeqirelle** [comment]
could we get a option for this in the future to determine how often it gets updated?

**Comment by realjackasterisk** [comment]
Unless there's a significant performance benefit, I don't see why OptiFine should change something like that in the first place.

**Comment by ZwipZwapZapony** [comment]
I agree that it should update once per frame, not only 10 times per second.

Most other coordinate-showing things in other games, including Team Fortress 2 and also vanilla Minecraft: Java Edition (but many more games than that, too), update it every frame. People are already used to per-frame coordinate updates.

All intentional "don't update it now"-iness does is make the game look like that something's broken or buggy, and it's still not really "readable" when it updates more than once per second, anyway.
