### ISSUE TITLE
[Suggestion] Chunk load- and view-distance improvements

### ISSUE THREAD

**Issue by rre36** [sp614x/optifine#3465]
To make large view distances more performant the chunk loading distance should be decoupled from the view distance so that each can be configured individually.
The way it should work like would be that new chunks are being loaded and updated inside the loading distance (eg. 12 chunks) but they would not be unloaded unless the player's distance to them exceeds the view distance (eg. 32 chunks). That way larger view distances could be used without having to sacrifice as much CPU-performance as we currently have to due to the chunk loading and updating.
Additinally the view distance should have a setting that disables the unloading of chunks completely to effectively allow for infinite view distances, which would be very useful for screenshots or cinematics, especially on server maps where local tools like Chunky cannot be used.

**Comment by ZtereoHYPE** [comment]
This wouldn’t be more performant at all, as loaded chunks require memory and cpu and would make the world slow down to a crawl if you moved a lot. Still, I see the usefulness for screenshots.

**Comment by Violainbow** [comment]
That's what mods like Chunky are for.

**Comment by rre36** [comment]
Except that you can't use Chunky on servers or with shaders since it is not a mod but a separate piece of software.

> This wouldn’t be more performant at all, as loaded chunks require memory and cpu and would make the world slow down to a crawl if you moved a lot.

I mean performance isn't the goal anyways, just getting past the view distance restriction. But in local worlds it *could* perform better in some situations since it does not just load everything in a 64 chunk viewdistance that is inside the view frustrum but only the chunks you have triggered to load.

**Comment by Brianetta** [comment]
How about sloppy chunk loading? Say, load all chunks within 5 of the player, but don't unload them until they're further than 8 or 10. This would give some good single player advantages, such as farms, redstone devices, fires etc continuing to be processed if the player is regularly travelling between two marginally distant locations, without having to load (and process) a bunch of peripheral chunks.

**Comment by rre36** [comment]
That sounds interesting, the "infinite" thing could then just be a setting for this.
Basically it could work if the load-distance and view-distance are getting decoupled. Afaik thats also what happens in bedrock. It only updates chunks in the closer range.

**Comment by ZtereoHYPE** [comment]
Now this would be cool af

**Comment by rre36** [comment]
Updated this issue to reflect that suggestion

**Comment by sp614x** [comment]
The chunk loading and unloading is handled by the integrated server.
The client creates a visual representation of the chunk by uploading the chunk geometry to the GPU and adding it in the visible chunk list.
If only the client render distance is increased, the chunks will stay visible when they are unloaded by the server. This doesn't speed up the chunk loading later, because when the chunk gets loaded again by the server the client MUST upload the chunk geometry again as it doesn't know if something has been changed.
This can easily be replicated in multi-player with high client render distance. The server is usually limited to 10 chunks, so the chunks only load in the server distance, but they stay visible until they reach the client render distance.
The performance at high render distances (>32) is usually limited by 
 - visibility culling which has to process a huge amount of chunks every frame 
 - raw GPU performance which has to render more then 2-5000 chunks pre frame
 - chunk ticking (haven't tested this recently)
OptiFine generally doesn't change server-related functionality, so changes in the chunk loading/unloading are probably not going to be implemented.

**Comment by rre36** [comment]
Would this also mean that replicating the "Large client renderdistance on a server" thing locally is also impossible?
