### ISSUE TITLE
Weird Texture/Chunk Error

### ISSUE THREAD

**Issue by xDr8ke** [sp614x/optifine#3505]
![2020-03-05_21 48 34](https://user-images.githubusercontent.com/61860172/76053876-ec3eea00-5f2b-11ea-815b-e82be38a5c1b.png)
![2020-03-05_21 48 30](https://user-images.githubusercontent.com/61860172/76053879-ed701700-5f2b-11ea-85a3-2c6541013ea2.png)

These screenshots are of the weird chunk/texture error that occurred. The reason I say it's a chunk error is because whenever i reload chunks it typically fixes itself. It only really happens if i go into an inventory for some reason, (Not 100% Sure). Hope this helps.

**Comment by ZtereoHYPE** [comment]
What version are you using? This was a known bug in < pre3 Versions but should be fixed in the latests

**Comment by xDr8ke** [comment]
I am using OptiFine 1.15.2 HD U G1 pre9
My GPU is a GTX 1050Ti
I am using the new default texture pack.
Let me know if you need anymore information,
-Dr8ke

**Comment by murtezayesil** [comment]
I experienced the same issue when I was in the mines.
![Screenshot from 2020-03-20 16-24-35](https://user-images.githubusercontent.com/24689015/77186002-72e2f200-6afc-11ea-88fa-95af9f23df8e.png)

[Here](https://github.com/modmuss50/OptiFabric/issues/125) is another issue reported to OptiFabric repository because author of issue assumed that it was a related to OptiFabric.

Interestingly, this issue almost always happens together with some chunks not rendering issue.

My system details:
CPU + GPU:  AMD A8-7410 APU with AMD Radeon R5 1GB VRAM(integrated)
OS: Elementary OS 5.1 Hera
Kernel: Linux 5.3.0-40--generic
Java: 1.8
Display Driver: X.Org AMD KABINI
Display Driver Version: Mesa 19.2.8, OpenGL 4.5

**Comment by sp614x** [comment]
Should be working in latest preview.
