### ISSUE TITLE
[1.8.9 HD U L5] Weird smoke particles at crosshair

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#3616]
## Description of Issue
Well, basically just black smoke particles are being shown at your crosshair

## Steps to Reproduce
1. Download HD U L5
2. Join any server (it can be Hypixel, HiveMC and anything else)
3. Look into the void (you can see my screenshot for better understanding btw)

## OptiFine Version
1.8.9 HD U L5 

## Installation Method
I used standalone installer.

## Log Files/Crash Reports
[See the log](https://gist.github.com/runic-tears/9f6a02167d8f10d1db6c2fcbd33083d2)

## F3 Debug Screenshot
[![Screenshot](https://i.imgur.com/ebRe2p9.png)](https://i.imgur.com/ebRe2p9.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- - No, it doesn't. It also doesn't happen on 1.8.9 HD U I7.

**Comment by asbyth** [comment]
This is the server spawning a boss and then despawning it for the bossbar advertisements & the sort. This happens in Vanilla as well as I7 and has been an "issue" for awhile.

**Comment by runic-tears** [comment]
> This is the server spawning a boss and then despawning it for the bossbar advertisements & the sort. This happens in Vanilla as well as I7 and has been an "issue" for awhile.

No, it doesn't happen in vanilla.

![2020-03-29_16 58 54](https://user-images.githubusercontent.com/51153795/77849694-9d107000-71de-11ea-997d-c8c71925031e.png)


Also doesn't happen with I7.

![2020-03-29_17 00 14](https://user-images.githubusercontent.com/51153795/77849720-c8935a80-71de-11ea-9260-a79c89e15003.png)

**Comment by DJtheRedstoner** [comment]
These are the particles of an invisible wither. There is no code to hide particles of invisible withers on vanilla or optifine, but the reason they only show on some servers with optifine is because optifine increases the non ignoreRange particle render distance from 16 to 32. Seeing as many servers use invisible withers for their lobby bossbars, it may be a good idea to add a invisibility check before rendering particles for a wither.

**Comment by sp614x** [comment]
Fixed, coming in M5_pre2
