### ISSUE TITLE
Shaders make chunks not load

### ISSUE THREAD

**Issue by RYUQUAZA** [sp614x/optifine#3632]
## Description of Issue
When  turned on my shaders the chunks stopped loading but the ones there before were still there.

## Steps to Reproduce
1. What do you do... ^
2. ...to find this bug?

## OptiFine Version
Self-explanatory. 1.15.2

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
Installer

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/
No other mods

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment]
Should be working in latest preview.

**Comment by winnetrie83** [comment]
I hope you are seeing this, because it is closed. I can confirm that it isn't working.
I'm using "preview_OptiFine_1.15.2_HD_U_G1_pre23" . Just dropped the jar in the mods folder, so no installer. 
Chunks are not loading/rendering, but when i switch to fast/fancy rendering it loads/render all chunks in render distance.
So whenever i reach the rendering border i do the "fast/fancy" rendering switch again and again all chunks are rendered in render distance.

It looks to me as if the rendering codes doesn't get any update and by switching fast/fancy rendering, you force update the whole rendering code

**Comment by SomeRandomPetey** [comment]
As a temporary alternative you can press F3+a to reload chunks
