### ISSUE TITLE
[Animation CEM] Support .COLLADA models & animations for Entities

### ISSUE THREAD

**Issue by Nickykun** [sp614x/optifine#3741]
Using for Skeleton based rendering and animations for Entities. It allows to use custom and beautifull animations and models created outside of the usual Minecraft, like with for example Blender, and export those models and animations to Collada, for use inside the Minecraft game engine via CEM

**Comment by SetantaLP** [comment]
That sounds cool, but I'm unsure if this would be implemented, because that would most likely require a lot of work to implement that, since CEM is a completely custom format designed to be used in minecraft (so implementing it was relatively easy), while COLLADA is designed to be used in a lot of different places. Because of that, the way models are defined in CEM files is basically the same way models are defined in the code (concerning parts and similar things) and the json based file structure is very close to the block/item-model files, so it's basically just parsing the CEM-files (with a parser similar to the block/item-model parser) and using the result to override the corresponding hardcoded models.
At the same time, COLLADA is it's own standardised format based on xml, so you need an xml-parser to read the data and some functions to transform the data into something minecraft can use for animating (since the game is responsible for deciding which animation is played on a model), moving and rendering the model.

**Comment by sp614x** [comment]
CEM only allows the configuration of the internal models and is based on the vanilla model structure.
Support for other model formats is not planned.
