### ISSUE TITLE
[PERFORMANCE] Drop OptiFine's Reflector

### ISSUE THREAD

**Issue by xxDark** [sp614x/optifine#3748]
## Description of the new feature
OptiFine might use direct method calls to Forge API, and disable them if `NoSuchMethodError`/`NoSuchFieldError` is thrown.

If you will do that, may that patch also be ported to older versions, such as 1.12.x?
Thanks.

**Comment by asbyth** [comment]
it cant use direct method calls if forge doesnt exist in the workspace lol
optifine doesnt use forge. reflection is the compatibility layer.

**Comment by xxDark** [comment]
> it cant use direct method calls if forge doesnt exist in the workspace lol
> optifine doesnt use forge. reflection is the compatibility layer.

what

**Comment by asbyth** [comment]
optifine doesnt use forge
optifine doesnt require forge
if you dont have forge, you cant call methods directly
this wouldnt compile seeing as forge's methods dont exist at compile time, since he doesnt have forge.

**Comment by sp614x** [comment]
Using direct method calls would significantly limit the range of supported Forge versions and it would complicate the development as OptiFine would have to be linked to Forge-modified base classes.
Reflection is also used outside of Forge support to minimize the number of base class edits.
Performance is not a problem if reflection is used properly (caching fields/methods + disabled access checks). A reflection method call is about 2x slower than a normal method call which is practically nothing.

**Comment by SetantaLP** [comment]
(I wrote that post yesterday evening but I didn't finished it completely, so I post it now)
@asbyth Exactly. Optifine is mostly a stand alone mod (which modifies the game code on its own) that can (optionally) also be used together with forge. Because of that the mod is created outside of a forge based workspace, so the only way to access forge methods and fields is using reflection (which by the way also allows to access private methods/fields), even though it would be better for the performance to call methods directly.
By the way, it's quite common to use reflection or similar concepts to access external code that might not be available: e.g. SteamVR uses dlsym on linux or GetProcAdress on Windows to access methods from libraries that are not necessarily available (e.g some vulkan initialisation stuff in vrclient.so) or if the path to the library is not known at compile time (e.g. for the vrclient in the libopenvr_api).

**Comment by xxDark** [comment]
`is about 2x slower than a normal method call which is practically nothing.`, that's why Forge added methods for OptiFine. Good point here.
https://github.com/MinecraftForge/MinecraftForge/blob/0d2a0deef396a46ceadd8cdaeb0deca36770188f/src/main/java/net/minecraftforge/common/ForgeHooks.java#L307

**Comment by xxDark** [comment]
`to minimize the number of base class edits.`, so maybe you sohuld not rewrite the whole classes? Your arguments seems like `ah, i don't want t ocomplicate things, just stick with reflection.`.

**Comment by SetantaLP** [comment]
As I mentioned before, Optifine is mostly a stand alone mod, which means that the only compile time dependency is Minecraft itself and its libraries, while Forge is an optional runtime dependency. Because of that, Optifine cannot rely on the hooks forge adds to the minecraft code by rewriting the classes, so it has to rewrite the classes on its own and if Forge is available at runtime, it calls the necessary forge methods via reflection.
And concerning rewriting classes: vanilla minecraft 1.15.2 consists of around 5100 class-files (all in all 16 MB) of which optifine patches 276 (usually with a few lines of code to add the necessary hooks), which is around 5,4% of all class-files. 
By the way, you know how the event system in CraftBukkkit/Spigot (and probably also in Forge) works? It uses reflection to find methods annotated with _EventHandler_ puts them into the list for the event mentioned in the parameter list, and then calls them via reflection if the event is triggered. Could that be avoided? Probably yes, but that would mean, that you would need an interface for each possible event, which defines a method that is called if the corresponding event  is triggered and which is implemented by any event listener class that should listen to the event.

**Comment by xxDark** [comment]
> As I mentioned before, Optifine is mostly a stand alone mod, which means that the only compile time dependency is Minecraft itself and its libraries, while Forge is an optional runtime dependency. Because of that, Optifine cannot rely on the hooks forge adds to the minecraft code by rewriting the classes, so it has to rewrite the classes on its own and if Forge is available at runtime, it calls the necessary forge methods via reflection.
> And concerning rewriting classes: vanilla minecraft 1.15.2 consists of around 5100 class-files (all in all 16 MB) of which optifine patches 276 (usually with a few lines of code to add the necessary hooks), which is around 5,4% of all class-files.
> By the way, you know how the event system in CraftBukkkit/Spigot (and probably also in Forge) works? It uses reflection to find methods annotated with _EventHandler_ puts them into the list for the event mentioned in the parameter list, and then calls them via reflection if the event is triggered. Could that be avoided? Probably yes, but that would mean, that you would need an interface for each possible event, which defines a method that is called if the corresponding event is triggered and which is implemented by any event listener class that should listen to the event.

No, you might just use consumers, that's for what they was designed. And that's what Sponge does. Everyone knows that bukkit sucks.

**Comment by xxDark** [comment]
If author of optifine would really care about performance, he could use Mixing framework by Sponge to inject it's code during runtime, everyone is happy and classes are not rewritten completely. And if there are REALLY needs to rewrite method bodies, for example, `@Overwrite` annotation might be used.

**Comment by CertainLach** [comment]
> inject it's code during runtime

After little modifications, MixinTweaker can also be used to patch classes in installation time (Same way as it currently works with applying delta, but adding net/optifine classes and applying mixins instead)

**Comment by SetantaLP** [comment]
@xxDark Consumers were introduced in Java 8 (released in 2014), while Minecraft didn't require Java 8 until 1.12 (released in 2017), so even if the devs knew about this feature, they couldn't use it until the release of 1.12 because the minimum java version (Java 6 and later java 7) didn't support it. And after the release of 1.12 they could have used it, but that would mean, that they would have to rewrite the whole event system, which would probably break some things and costs a lot of time, so the important question is: how much faster are consumers compared to the currently used reflection based system?
Using Mixin wouldn't solve the reflector problem since that would only change the way optifine alters minecraft code, but not the way optifine interacts with Forge (if present at runtime), and you definitely can't uses consumers there, since they require that the types are known at compile time.
`@Override` can only be used in subclasses (and tells the compiler, that the annotated method overrides a superclass method with the same signature, so that the compiler can warn if that's not the case), while Optifine and also Forge alter methods directly (because subclasses don't necessarily have access to all methods and fields of the base class, and additionally you can't use the subclass unless you alter the point where the Object is created) and besides that most annotations are not available in the byte code.
And concerning performance: if you really want good performance you'll most likely use c or c++ but never java, because native code is much faster than code executed on a virtual machine (like the jvm).
By the way: it seems that you don't really know the difference of optifine being installed as stand alone mod, and optifine being loaded by forge. The former results in minecraft classes being patched at install time with the xdeltas provided in the patches-folder inside the downloaded jar, saved into `<.minecraft-folder>/libraries/optifine/Optifine/<version name>/<version name>.jar` and loaded at runtime instead of the original class found inside `<.minecraft-folder>/versions/<version name>/<version name>.jar`. The latter results in classes being modified at runtime with the xdeltas provided in `patches/srg` (which are slightly different from the ones in the patches folder) inside the downloaded jar (see `optifine/OptiFineTransformationService.class` and `optifine/OptiFineTransformer.class` for more info).

**Comment by xxDark** [comment]
> 
> 
> @xxDark Consumers were introduced in Java 8 (released in 2014), while Minecraft didn't require Java 8 until 1.12 (released in 2017), so even if the devs knew about this feature, they couldn't use it until the release of 1.12 because the minimum java version (Java 6 and later java 7) didn't support it. And after the release of 1.12 they could have used it, but that would mean, that they would have to rewrite the whole event system, which would probably break some things and costs a lot of time, so the important question is: how much faster are consumers compared to the currently used reflection based system?
> Using Mixin wouldn't solve the reflector problem since that would only change the way optifine alters minecraft code, but not the way optifine interacts with Forge (if present at runtime), and you definitely can't uses consumers there, since they require that the types are known at compile time.
> `@Override` can only be used in subclasses (and tells the compiler, that the annotated method overrides a superclass method with the same signature, so that the compiler can warn if that's not the case), while Optifine and also Forge alter methods directly (because subclasses don't necessarily have access to all methods and fields of the base class, and additionally you can't use the subclass unless you alter the point where the Object is created) and besides that most annotations are not available in the byte code.
> And concerning performance: if you really want good performance you'll most likely use c or c++ but never java, because native code is much faster than code executed on a virtual machine (like the jvm).
> By the way: it seems that you don't really know the difference of optifine being installed as stand alone mod, and optifine being loaded by forge. The former results in minecraft classes being patched at install time with the xdeltas provided in the patches-folder inside the downloaded jar, saved into `<.minecraft-folder>/libraries/optifine/Optifine/<version name>/<version name>.jar` and loaded at runtime instead of the original class found inside `<.minecraft-folder>/versions/<version name>/<version name>.jar`. The latter results in classes being modified at runtime with the xdeltas provided in `patches/srg` (which are slightly different from the ones in the patches folder) inside the downloaded jar (see `optifine/OptiFineTransformationService.class` and `optifine/OptiFineTransformer.class` for more info).

1. There are optional mxiins.
2. They may be used their own interface to implement consumers.

**Comment by SetantaLP** [comment]
1. What do you mean by `optional mxiins` and how is that connected to what I wrote?
2. Completely changing the way how a system works internally will most likely have side effects for people who use the system unless you spend a lot of time to prevent that. And just changing internal stuff is usually much more complicated than completely rebuilding a system from scratch (which is probably one of the reasons why cpw created a completely new system for launching forge on Java8+ named modlauncher instead of just updating the LegacyLauncher). Besides that, it's important to really check how much performance you could gain if you use Consumers instead of reflection, since it doesn't make sense to spend a lot of time to switch to Consumers if the performance benefit is quite low.
3. ah okay.
4. Take a look into optifine's code and you'll see for which purpose reflection is used. It's approximately 50% for preventing compile time (and by that also strict runtime) dependencies to forge, and also approximately 50% to prevent modifications of Entity-Model or Entity-Renderer classes. The former makes sense, since Optifine is mostly a stand alone mod that doesn't require Forge to work (I usually use Optifine without Forge), so having compile time dependencies to Forge would make development much more complicated and would also cause a lot of exceptions  at runtime, that would have to be caught and which would also make code much harder to read. The latter makes sense since it's much cleaner to just use reflection to get access to one or two private or protected attributes in 77 classes instead of adding patches to make these attributes accessible (especially since these attributes are only accessed this way if you load (or unload) a resource pack with custom entity models).
By the way, where do I contradict myself? And besides that, before you complain that reflection slows down the performance, you should make tests that compare the performance of direct access (including all the stuff that has to be added e.g. to catch exceptions) to the performance of reflection.
5. Then you should probably try a different approach, since applying the optifine patches at runtime (most likely on top of the forge patches) obviously works.
6. Yep, that was definitely a misunderstanding, since I hadn't heard about Mixin before this conversation and googling for `@Overwrite` only gave results for `@Override`, so I assumed that it was just a spelling mistake.

**Comment by sp614x** [comment]
OptiFine makes extensive changes to the rendering classes. To get an idea:
- Forge 1.15 patches are 20973 lines, affecting 518 base classes.
- OptiFine 1.15 patches are 21839 lines, mostly concentrated on the rendering classes.

It is effectively refactoring the render engine, not just extending it. This level of complexity can't be managed in a sane way with runtime patching (bytecode manipulation, mixins, etc.).
