### ISSUE TITLE
Emissive Lighting in 1.15

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#3782]
It's time for the obligatory weekly reminder that emissive textures are STILL broken!

I'm aware of how obnoxious I'm sounding, but we've gone through 8 preview versions without the acknowledgement that emissive is broken, so i'm gonna keep mentioning it until it gets acknowledged / fixed.

Thanks!

**Comment by NiemandTV** [comment]
Do you know the principle behind GitHub and issues? Creating duplicate issues on purpose is the dumbest thing you can possibly do. It won't speed up the development of OptiFine. On the contrary, it actually slows it down because people like you make issues harder to navigate through. Also, OptiFine's last preview version was pre13, released 23 days ago. You created the first issue about this bug 9 days ago. What the hell did you expect? Silent updates? Use your brain.

**Comment by HiItsDevin** [comment]
Please don't create duplicate issues, especially on purpose. Just wastes everyone time.

**Comment by MrCheeze446** [comment]
No need to post it twice

**Comment by Studio528-real** [comment]
Ontop of that, forge compat is the current focus, after that final bugfixes (like fixing Emissive and CEM etc) will likely be done, just be patient and wait for it to be done.

**Comment by realjackasterisk** [comment]
Four times total, for that matter.

#3746
#3596
#3500
