### ISSUE TITLE
[1.15.2 pre16] "Dropped Items: Fast" doesn't work correctly

### ISSUE THREAD

**Issue by GreenAndEievui** [sp614x/optifine#3942]
## Description of Issue
When Dropped Items is set to "fast" the items do not appear 2-Dimensional.

## Steps to Reproduce
1. Set dropped Items to Fast
2. Throw an item on the ground

## OptiFine Version
1.15.2 pre16

## Installation Method
Standalone

## F3 Debug Screenshot
Taken with dropped items set to fast. The pumpkin pie on the ground is still 3D
![2020-05-14_22 59 54](https://user-images.githubusercontent.com/14899090/82006874-c8d4a180-9636-11ea-9390-5153455b1c52.png)

**Comment by yezhiyi9670** [comment]
It's intended. (?)

Minecraft won't use 2D models for items when `Quality: Fast` since 1.8. So if `Dropped Items: Fast` have no functionality at all, it should be removed. If it's intended that the setting should revert items to pre-1.7 behavior, it should default to `Fancy` to match the vanilla behavior.

**Comment by sp614x** [comment]
Relevant: #2134

**Comment by XenonZed** [comment]
This option should probably be removed/greyed out from the menu unless it becomes functional again. It's extremely bizarre to have a toggle available in the mod which doesn't do anything and could mislead users into thinking it does.

**Comment by Lassebq** [comment]
I would preffer 2D items at fast graphics be an optifine feature. Th better way is to fix it instead of removing it.
