### ISSUE TITLE
[1.15.2 HD U G1 pre26] Block outline in wrong position when chunk borders shown

### ISSUE THREAD

**Issue by MithicSpirit** [sp614x/optifine#4119]
## Description of Issue
If chunk borders are shown (`F3` + `G`), block outlines appear in the wrong position (i.e.: not around the block). The outlines appear to move around depending on player position and orientation.

## Steps to Reproduce
1. Show chunk borders (`F3` + `G`)
2. Hover over a block
3. Move around a bit while paying attention to the block outline

## OptiFine Version
1.15.2 HD U G1 pre26

## Installation Method
Used the standalone installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4801611/latest.log)

## F3 Debug Screenshot
![2020-06-18_19 07 38](https://user-images.githubusercontent.com/24192522/85080377-0331e100-b197-11ea-97a1-2dc3ddd00c38.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine? No

**Comment by naeqirelle2020** [comment]
this only appears if you activate internal shaders otherwise works fine.

![2020-06-19_06 41 57](https://user-images.githubusercontent.com/63185833/85100427-0ad5a200-b1f8-11ea-891c-6412dbb22eb3.png)

Internal Shaders ^

![2020-06-19_06 42 05](https://user-images.githubusercontent.com/63185833/85100437-1032ec80-b1f8-11ea-88b4-3afca2242ed8.png)

No Shaders ^

**Comment by sp614x** [comment]
Fixed in pre28.
