### ISSUE TITLE
OptiFine pre24

### ISSUE THREAD

**Issue by Kilomegaminx** [sp614x/optifine#4131]
Hi, I am looking for the download of specifically OptiFine pre24, and I cannot find it anywhere. Could you possibly give me a download link?

**Comment by sp614x** [comment]
What is so special about pre24?

**Comment by ewanhowell5195** [comment]
you shouldnt be trying to download old versions. there are lots of things that could be broken, and could crash/corrupt your game. This is why you should always be using the most up to date version possible. If you want a previous version because your resource pack breaks in a newer version, it means that you made your pack work on a version that is broken, so when it was fixed it *broke* your pack. If this is the case it would be best to just try fix it.

**Comment by Kilomegaminx** [comment]
I am looking for pre24 specifically because I am experiencing some problems with a different mod that are caused by OptiFine, and the mod creator suggested specifically OptiFine pre24.

**Comment by Kilomegaminx** [comment]
![Crash On Game Startup · Issue #128 · qouteall_ImmersivePortalsModForForge - Google Chrome 6_20_2020 5_48_18 PM](https://user-images.githubusercontent.com/65316867/85213645-45d1f580-b31e-11ea-976a-5e77b314bff9.png)

**Comment by Kilomegaminx** [comment]
I found a download.
