### ISSUE TITLE
Minecraft Optifine Fatal Error 1.14.4

### ISSUE THREAD

**Issue by k1xd** [sp614x/optifine#4183]
I wanted to play Minecraft with shaders but when i selected a shaderpack, it loaded and for a moment the Minecraft window freezed and it crashed and this was the crash log:
[latest.log](https://github.com/sp614x/optifine/files/4852909/latest.log)

**Comment by sp614x** [comment]
OpenGL debug message, id=0, source=API, type=ERROR, severity=HIGH, message=Unknown internal debug message. 
**The NVIDIA OpenGL driver has encountered an out of memory error.** 

The NVidia driver is out of memory.
Using a smaller resource pack, reducing render distance or restarting the computer could help.
Can't be fixed by OptiFine.
