### ISSUE TITLE
[Bug] Mobs not becoming red when hit

### ISSUE THREAD

**Issue by david92003** [sp614x/optifine#4231]
## Description of Issue
Mobs don't become red after being hit by the player.

## Steps to Reproduce
1. Have the internal shader enabled.
2. Hit a mob.

## OptiFine Version
1.16.1 HD U G2 pre2

## Installation Method
Standalone installer

## F3 Debug Screenshot

![2020-07-04_16 28 18](https://user-images.githubusercontent.com/20598652/86513561-cced9600-be13-11ea-8aad-bebf9a1cbdcf.png)

## Prior Testing
It does not occur in vanilla 1.16.1.

**Comment by yezhiyi9670** [comment]
Can confirm for 1.15.2 G1-pre30.

**Comment by Scorpion34** [comment]
Yeah I just think this was just an accident forgotten about because other shaders do work like Slidurs or SEUS or anything of those kinds but Internal doesn't probably just some old code in there that was forgotten about thus why Internal shaders don't render the entity color correctly hopefully gets fixed soon :>

**Comment by sp614x** [comment]
Internal shaders are only for testing the rendering pipeline.
They should not be used for playing.

**Comment by Scorpion34** [comment]
> Internal shaders are only for testing the rendering pipeline.
> They should not be used for playing.

But why? I like the internal shaders because it makes things just look brighter which I quite enjoy it external shaders like seus or slidurs are great but nothing I'd really enjoy playing with because I don't like the look of realistic I like the simplicity of Minecraft with internal shaders this helped most of my builds to look and shine brighter on top of that YouTubers use internal shaders all the time for this exact reasoning it beautifies vanilla

**Comment by yezhiyi9670** [comment]
Internal shaders will also be used when the shaderpack is dimension-specific and lacks configuration in a certain dimension.
