### ISSUE TITLE
Crashes When Trying To Enable Seus Shaders (RX 570)

### ISSUE THREAD

**Issue by jontheyeetboi** [sp614x/optifine#4448]
## Description of Issue
Minecraft Crashes when Trying To Enable SEUS Renewed v1.0.1 

## Steps to Reproduce
1. Start Minecraft
2. Join Multiplayer Server
3. Go Into Settings > Video Settings > Shaders
4. Enable SEUS Renewed v1.0.1

## OptiFine Version
1.16.1 G2 Pre10

## Installation Method
Standalone installer

## Log Files/Crash Reports
[hs_err_pid22576.log](https://github.com/sp614x/optifine/files/4974666/hs_err_pid22576.log)

## F3 Debug Screenshot
![2020-07-24_17 29 26](https://user-images.githubusercontent.com/45613796/88444723-5967f480-cdd3-11ea-8049-451f60a3ecb6.png)

This was before i enable the shaders

## Prior Testing
Unable To Reproduce in Vanilla Since Their Optifine Shaders

## Additional Information
GPU: AMD RX 570 4GB by XFX

Note:  Doesnt crash when enabling it in the main menu and then joining server

**Comment by Tr4nz1uc3nt** [comment]
I’ve been having this issue as well, since 1.14 Optifine with shaders (any shaders, not just SEUS), with an XFX RX 580. Supposedly it’s an OpenGL driver error on AMD’s part. If you look at the crash report you’ll likely see an Exception Access Violation, with a problematic frame in AMD’s OpenGL driver (atio6axx.dll). There’s hundreds of posts about it all over the internet, but unfortunately I’ve yet to find a fix.

**Comment by sp614x** [comment]
Most probably a problem with the AMD drivers.
