### ISSUE TITLE
[Category] ALL blocks invisible on multiplayer servers

### ISSUE THREAD

**Issue by fire8811** [sp614x/optifine#4454]
## Description of Issue
Upon loading into a multiplayer server nothing is rendering other than players(but their skins do not load, only alex and steve) and entities. All blocks are invisible, but individual chunks can be loaded sometimes by breaking an invisible block. Reloading chunks or resource packs using F3 shortcuts does not fix the issue.

## Steps to Reproduce
Happened on OptiFine 1.16.1 HD U G2 pre09 AND OptiFine 1.16.1 HD U G2 pre10 (did not try older versions) on any multiplayer server
running MacOS Mojave if that helps

## OptiFine Version
1.16.1 HD U G2 pre09 AND OptiFine 1.16.1 HD U G2 pre10

## Installation Method
Installed using standalone installer

## Other Installed Mods
No other mods are installed, no shaders installed either
 
![2020-07-25_11 34 21](https://user-images.githubusercontent.com/23282163/88460584-49035880-ce6b-11ea-9ab4-6a4933d90e40.png)

## Prior Testing
If you've installed standalone:
Issue does not happen in Vanilla

**Comment by Blackholes128** [comment]
yeah I have this issue too, i noticed that skins also don't load and default to alex or steve

**Comment by FirstLadyAnna** [comment]
Yes armoria.de network also has the problem. Exactly the same problem.

**Comment by DasElektronisch** [comment]
I also encountered this issue and could find the following error in the log:
`[18:03:18] [Worker-Main-16/ERROR]: Couldn't download http texture: java.net.SocketTimeoutException: connect timed out`

I'm thinking this issue has something to do with the optifine-capes.
After analyzing outgoing traffic using Wireshark I found that http-connections to `107.182.233.85` seemed to be running into a timeout.

The fact that this issue is only occurring if there are players in range reinforces my suspicion that probably the "optifine cape servers" were offline. By now the service seems to be online again and the bug suddenly vanished.

**Comment by FirstLadyAnna** [comment]
Yes, everything is fine now

**Comment by sp614x** [comment]
Should be fixed in pre11.

**Comment by tesqoswagmoney** [comment]
it still happens for me
