### ISSUE TITLE
Optifine detects very low version of OpenGL on macOS

### ISSUE THREAD

**Issue by siyy123** [sp614x/optifine#4598]
<img width="966" alt="截屏2020-08-12 下午1 08 35" src="https://user-images.githubusercontent.com/11704754/89977135-f912f700-dc9c-11ea-86f7-d47cd1d7cada.png">
the Optifine detects only OpenGL 2.1 on my macOS causing several shaders working inproperly. My Optifine version is 1.12.2 HD U F5 but the same bug also happen on 1.14.4 F5 version and others. my dGPU supports Metal and macOS GPUFamily2 v1 so it should have no problem supporting higher version of OpenGL API.

**Comment by siyy123** [comment]
And the bug present also on 1.16.1 G4

**Comment by sp614x** [comment]
The problem is that MacOS doesn't allow mixing legacy (pre 3.0) and modern (3.0+) OpenGL features.
Minecraft is based on legacy OpenGL (2.1) so MacOS only allows 2.1 to be used.
Minecraft could be made to launch in OpenGL 3.0+ mode, but then it would refuse to run as 2.1 and lower features will be missing. This limitation is a MacOS problem.
