### ISSUE TITLE
someone may have stolen some of your code

### ISSUE THREAD

**Issue by Nathan22211** [sp614x/optifine#4619]
I noticed this going around on fabricord that the creator of thallium supposedly stole some of the code from Optifine for his mod. I know this probably isn't the best way to get a hold of you but I couldn't figure out how to DM you through github, here's the link to the source code of his mod: https://github.com/IsaiahPatton/thallium

**Comment by sp614x** [comment]
What code do you think is taken from OptiFine?

**Comment by Nathan22211** [comment]
I'm not sure since I'm no expert in making optimization mods but try looking at code that does this stuff

1: Replaces the default chunk manager to use fast lookup maps
2: Optimizes animated textures to tick those only in loaded chunks
3: Optimizes BlockPos methods
4: Uses Fast Math, Optimized sine & cosine.
      Allows the change of the algorithm to best fit your computer

5: Adds directional chunk render

this is from the description it has for its features on curseforge

**Comment by Deviouslrd** [comment]
First off, Thallium has already been caught by jellysquid for taking sodium's code (https://github.com/IsaiahPatton/thallium/issues/3 for her original issue post, outlining everything regarding it). The link she provides no longer works simply because Isaiah changed the name of the .java file containing Sodium's code.
Now regarding code stolen from optifine, based on the 5 points of optimization that Isaiah had, the only one i can potentially see as stolen is the Fast Math, Optimized sine & cosine, as optifine already has that feature. The other 4 I am unsure if optifine even uses, so I cannot tell.

**Comment by AppDevMichael** [comment]
![image](https://user-images.githubusercontent.com/33251702/90414578-dff8b480-e0a7-11ea-966b-8c2daf18d1f6.png)

This is the deleted comments on the Thallium issue mentioned above

**Comment by NebelNidas** [comment]
See here: https://web.archive.org/web/20200803092849/https://github.com/IsaiahPatton/thallium/issues/3
