### ISSUE TITLE
[Bug] Sildur's Vibrant Shader's lighting bug

### ISSUE THREAD

**Issue by NaiNonTH** [sp614x/optifine#4698]
## Description of Issue
I have no idea if this is an Optifine's bug, But once I use Sildur's Vibrant shader v1.28 (High-Motionblur), The chest and sign turned black for some reason.

## Steps to Reproduce
1. Install Optifine (Yeah you need to.)
2. Install Sildur's Vibrant (v1.28 High-Motionblur)

## OptiFine Version
Since OptiFine 1.16.2 HD U G3 pre1

## Installation Method
Optifine Standalone Installer

## Prior Testing
If you've installed standalone:
- No for sure. Because shaders need Optifine.

## Additional Information
Image: https://imgur.com/a/XhzXnLQ

**Comment by NaiNonTH** [comment]
Update: In pre-release 5, Beds also occur this weird bug as well and every presets happens.

**Comment by NaiNonTH** [comment]
More Update: Bells too. Well I think all of the model stuff occur this bug

**Comment by sp614x** [comment]
Works correctly with Sildur's Vibrant 1.28 Medium shaders.
To fix it in High-Motionblur go to Options -> Video Settions -> Shaders -> Shader Options -> Normal Map -> RP Support -> OFF 

The problem is that High-Motionblur enables normal map processing and applies it to block entities (signs, chests, beds). 
Up to MC 1.14 the block entities were rendered as blocks, in MC 1.15+ they are rendered as entities and they don't have the extended vertex attributes.
