### ISSUE TITLE
Optifine not working in conjunction with other mods

### ISSUE THREAD

**Issue by Comthefox2486** [sp614x/optifine#4736]
I am a private anarchy server host, and I myself need to hack to test certain things out.
I have 4 mods, Fabric API, OptiFabric, Optifine, and the latest version of 1.15.2 Wurst.
Everything works fine, except when I put in Optifine into my mod list, when I do, it gives me this error
**The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1**
I use Fabric (as hinted by fabric api) to use Wurst, And I NEED NEED NEED Optifine to work correctly as otherwise my FPS drops to almost 0.

If you need the Crash Report, It can be found under this line, Thanks.
https://pastebin.com/9z9xsyXU

**Comment by EdgyPotato** [comment]
Optifine does not support for hacked client and optifabric.

**Comment by MrCheeze446** [comment]
As edgypotato said, OptiFine doesn't support hacked clients.

**Comment by Thorinair** [comment]
This may be an issue in 1.15.2 OptiFabric. I used to have a similar crash when Optifine was used in conjunction with VoxelMap, but it was eventually fixed. You could try reporting the issue to one of the new OptiFabric repos, since the original OptiFabric is dead. I think this is the new "official" one: https://github.com/Chocohead/OptiFabric
