### ISSUE TITLE
Performance issues when using multiple depth buffers

### ISSUE THREAD

**Issue by Builderb0y** [sp614x/optifine#478]
Simply having depthtex1 enabled as a uniform seems to decrease framerate by a significant amount, and having depthtex2 enabled decreases it even farther. The exact values varied between tests, but they were usually between 1/3 and 1/2 of the control test. Additionally, having ONLY depthtex2 enabled has the same effect, even when depthtex0 and 1 are disabled. It's as if it re-renders the world once for each depth buffer.

Having other buffers in use (like gaux1-4) does not have the same effect, even when they're formatted with high-precision, so writing depth information to those buffers manually is actually _better_ on framerate. In my testing, I wrote to gaux1, 2, and 3 with `gl_FragData[1, 2, and 3] = vec4(gl_FragCoord.z, 0.0, 0.0, 1.0);` using the same rules that depthtex normally follows (water doesn't write to 2, hand doesn't write to 3, etc…). All 3 of these buffers were formatted with R32F, and yet there was significantly less framerate impact than having depthtex2 enabled. (between 2/3 and no impact at all compared to the control test). Why is writing to depth buffers so much more costly than normal buffers?

Tested in versions 1.11.2_HD_U_B5, B6 and B7 (not the preview version).

**Comment by sp614x** [comment]
For me enabling `depthtex0-2` has minmal effect.

Testing with a minimal shader pack with one composite program (equivalent to vanilla):
- base = 290 fps
- enabled depthtex0 = 290 fps
- enabled depthtex1 = 280 fps
- enabled depthtex2 = 270 fps

The FPS drop is caused by the depth buffer copying.
When depthtex2 is enabled, then depthtex0 and depthtex1 are also automatically enabled.
