### ISSUE TITLE
[color or colormap | BUG]  color setting at particle.water didn't work on rain splash and bubbles

### ISSUE THREAD

**Issue by Jimmy-sheep** [sp614x/optifine#4890]
## Description of Issue
particle.water in color.properties didn't work on rain splash and bubbles, like the two picture I show below(red circle)...
Or maybe its colormaps' problem, but the color I draw in waterdrop.png(16x1 pixel) is same (99CCFF).

This is what I type in this file...
particle.water=99CCFF  
99CCFF is look like this : ![image](https://user-images.githubusercontent.com/65125836/95418416-04fffa00-096a-11eb-8910-ac838419b862.png)
And the particle color should work like the right corner at second picture(green circle).

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

## OptiFine Version
OptiFine_1.16.3_HD_U_G3

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No. only optifine.

## Additional Information
![2020-10-08_13 11 58](https://user-images.githubusercontent.com/65125836/95418532-57d9b180-096a-11eb-9fec-dfdff42aeae7.png)
![2020-10-09_11 17 06](https://user-images.githubusercontent.com/65125836/95539632-72bb2d00-0a21-11eb-84ec-d6073b046c8a.png)

**Comment by SLimeyMC** [comment]
Firstly do you change the water splash texture (splash0,..,splash3)? if yes, mostly it is black or white? but if you not maybe that is bugged it. 

The water splash texture use full-color format rather than grayscale and it was dark blue so the colormap you apply get multiplied and it dont has any changes (or is it?).

**Comment by Jimmy-sheep** [comment]
Yes, I change the water particle color its Light blue (99CCFF as I write in upward), not only black, gray or white.
Umm, so the particle use colormap..?  I thought it didn't, cause fishing splash particle seems didn't use...
Is there anyway to let it won't use colormap? I hope all the particle color in red circle at my picture show like particle in green circle.

Sorry, I'm bad at English, hope you can know what I'm saying...

**Comment by SLimeyMC** [comment]
> Umm, so the particle use colormap..?

Partially but for the splash particles nope. but since u apply colormap on them so it should be grayscale but since you state that the water splash texture color is light blue so I don't know what caused it. but since you said you bad at English maybe you just mistaken 

> Is there anyway to let it won't use colormap?

By delete the line you made (`particle.water=99CCFF`)

**Comment by Jimmy-sheep** [comment]
> By delete the line you made (`particle.water=99CCFF`)

Oh, I try this, and it's solved.
I'm very thanks for your help~~

**Comment by SLimeyMC** [comment]
No problems now ire your jobs to close this issue.
