### ISSUE TITLE
Feature: More mipmap levels

### ISSUE THREAD

**Issue by BiatuAutMiahn** [sp614x/optifine#492]
When using high resolution textures such as 512x512, there is a lot of noise in the distance. I think this could be resolved if we could have more mipmap levels.

**Comment by sp614x** [comment]
Mipmap level 4 is interpreted as Maximum and then OptiFine uses the maximum possible level.
The maximum level depends on the size of the majority of the textures. For example a 64x resource pack will use mipmap level 6. Adding several big textures to a low-res resource pack will NOT increase the maximum mipmap level, because the majority of the textures would still be small. This is done to avoid excessive texture atlas waste and to avoid the texture atlas growing above the maxumum supported texture size.

**Comment by BiatuAutMiahn** [comment]
ah ok, thanks for the clarification
