### ISSUE TITLE
Optifine 1.16.3 not working with my mod list

### ISSUE THREAD

**Issue by RaffHzTM** [sp614x/optifine#5000]
Hey there,

Whenever I try to load Optifine with my mod list I receive this error:

The game crashed whilst initializing game
Error: java.lang.VerifyError: Bad local variable type
Exit Code: -1****

Any chance anyone knows how to fix this? I've tried using OptiForge and different versions of Optifine previously but nothing seems to fix it.

All the mods are on 1.16.3, I'm using OptiFine 1.16.3 HD U G4, Forge 1.16.3-34.1.42 & OptiForge-MC1.16.3-0.3.4

The mods I'm currently using are as linked below:
[mods (1).zip](https://github.com/sp614x/optifine/files/5489880/mods.1.zip)

Thanks!

**Comment by BlazingFlame15** [comment]
OptiFine 1.16.3_HD_U_G4, which is the version that you have, only supports up to forge 34.0.0 as said in the patch notes, 

`OptiFine 1.16.3_HD_U_G4
 - not working: antialiasing and anisotropic filtering
 - fixed shadow bug with sildurs shaders and campfire (#4372)
 - added support for Forge modlauncher Target.PRE_CLASS (#4515)
 - fixed MineColonies GUI, fixed AT invokespecial/virtual (#4582)
 - added particle culling
 - updated to 1.16.3
 - **compatible with Forge 34.0.0**
(02.11.2020)
`
In order to play with Optifine you need to get G5 which they thankfully updated for us that supports up to 34.1.42, which is the version you have.

**Comment by Tsoccerguy3** [comment]
Note that Optifine does not support obfuscate-0.5.0-1.16.3.jar , Only can be fixed by sp514x , because we don't have access to the Optifine source .

**Comment by Tsoccerguy3** [comment]
https://github.com/MrCrayfish/Obfuscate/issues/3

**Comment by KaiAF** [comment]
Looking at MrCrayfishs' issue, looks like it has been fixed now. If not, let me know.
