### ISSUE TITLE
Any shader containing composites breaks the game

### ISSUE THREAD

**Issue by blint071** [sp614x/optifine#5091]
## Description of Issue

An average of 200 entities + 16 render distance + any shader containing composites(situation which can be found in a normal survival map) tanks the fps in any pc. As you can see in the video, none of the cpu threads, gpu or ram is near from being fully used.

It is a problem related to shader composites and textures. I know this because even the lightest shader containing them(even if it is a shadows-only shaders with shadows disabled) would cause just the same problem. I tested waving-shaders without composites and the issue was not there. This suggest that the issue might be in optifine´s code. 
The problem is even more aggressive in the last optifine versions, where you don’t even need any resource pack to reproduce the issue. In this video you can see a comparison video showing the fps with a shader containing composite files and a shader not containing them. 

https://youtu.be/PX1cT_YAyRc

I tested the same map in minecraft 1.12.2 using the same settings and I got an average of 60 fps. **A 128x or x64 resource pack is needed to reproduce the issue** in this version of the game. This problem is present in all versions of the game.

## Steps to Reproduce
The video.

## OptiFine Version
All of them.

## Installation Method
Standalone installer without mods.

**Comment by blint071** [comment]
Reproducing the same flaw using minecraft´s version 1.12.2:
https://www.youtube.com/watch?v=osTa6GGFjVE&feature=youtu.be

**Comment by blint071** [comment]
Considering 99% of shaders use composites, I think something should be done to fix it, because all of this is starting to become very uncomfortable and the problem is getting bigger and bigger with the last optifine´s versions...

**Comment by sp614x** [comment]
This probably the effect of the shadow map pass. 
When shadows are disabled, the shadow pass is probably still active, but not used.
Composites are only GPU limited and usually have much less impact on performance.
In the shadow pass OptiFine has to render everything a second time (terrain, entities, etc) and it has to render much more chunks because chunks that are not visible may still throw a shadow on the visible chunks. Then in the shadow pass it has to disable face culling in order to fix the light shining in underground caves, this again means 2x more processed quads. At the end in the shadow pass probably 4x more geometry is being rendered compared to the normal pass.
One CPU core (rendering) is loaded at 100% and the others are probably 20-30%, but you can't see it because the operating system is switching the load around the cores to distribute the heat generation evenly and to avoid one core overheating.
