### ISSUE TITLE
User Interface is missing

### ISSUE THREAD

**Issue by harmalom** [sp614x/optifine#5288]
OptiFine version 1.16.5 G7 pre5, completely disappears the user interface, including all menus and submenus within the game, preventing you can access the player inventory, the menu of all storage blocks, game menus, etc..

In other words, you can only see the game without any menu or interface.
UI, GUI

Optifine 1.16.5 G7 pre5
Minecraft 1.16.5
Forge 1.16.5-36.0.13

Resources Pack
Complementary_v3.10
Stoo's Deluxe Ressource Pack v1.10
VanillaTweaks_r999741

Shaders Pack
ComplementaryShaders_3.10

ListMods
https://pastebin.com/qr9v8AEP

![2021-02-02_08 56 11](https://user-images.githubusercontent.com/67077986/106612379-0ff12280-6537-11eb-97e3-cbca4aba34e5.png)

Note:
There is no crash log because the game works correctly only without any GUI, with the preview_OptiFine_1.16.5_HD_U_U_G7_pre4 version, it works correctly.

![2021-02-02_09 32 39](https://user-images.githubusercontent.com/67077986/106614781-bb9b7200-6539-11eb-89a1-1322516e6a2f.png)

**Comment by Tsoccerguy3** [comment]
yes , this version is broken , wait for a pre 6 version

**Comment by harmalom** [comment]
GUI still does not work with 1.16.5 G7 pre6

**Comment by sp614x** [comment]
Most probably a conflict with one of the installed mods.
Can you post the error log?
You can fond the problematic mod by splitting the mods in half, test an keep the half which has the problem.
Repeat until only one mod except OptiFine is left.

**Comment by WenXin20** [comment]
I had this happen too. It was caused by Xaero's Minimap and world map. Updating those two should fix it.

**Comment by harmalom** [comment]
Thanks, it worked, Xaero's was the problem.

**Comment by bonkmaykrQ** [comment]
> 
> 
> Thanks, it worked, Xaero's was the problem.

I second this, using 1.16.4 build of minimap was breaking it. I'd have never guessed

**Comment by WenXin20** [comment]
J________________________________Sincerely, David NewvilleOn Jun 4, 2021 6:31 PM, bonkmaykrQ ***@***.***> wrote:

Thanks, it worked, Xaero's was the problem.

I second this, using 1.16.4 build of minimap was breaking it. I'd have never guessed

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
On Jun 4, 2021 6:31 PM, bonkmaykrQ ***@***.***> wrote:

Thanks, it worked, Xaero's was the problem.

I second this, using 1.16.4 build of minimap was breaking it. I'd have never guessed

**Comment by KaiAF** [comment]
This was resolved.
