### ISSUE TITLE
"Ignore Recommended Limits" Option in OF Settings

### ISSUE THREAD

**Issue by Cjnator38** [sp614x/optifine#5469]
### This option should already be available in some other games such as GTA V/Online with the "Ignore Suggested Limits" option:
![image](https://user-images.githubusercontent.com/39870226/111940685-583fb200-8a9d-11eb-8df0-b38a0072412e.png)

There's a chance that an option you would like to access isn't available on your platform of choice.
Like Fancy Fog being available in Linux, but not in Windows ~~(this comes from experience)~~. Having freedom to try out options without restrictions adds more customization to OptiFine. It would also be best to give out a warning to keep a backup of the "settingsof.txt" file just in case Minecraft stops working.

**Comment by sp614x** [comment]
Games like GTA quite often use different rendering profiles on different hardware in order to optimize performance and fix driver bugs.
OptiFine doesn't have different rendering profiles, so this option is meaningless.
The fancy fog is not available on Linux because the driver doesn't support the extension NV_fog_distance. If it is used the driver will probably generate errors/warnings.
