### ISSUE TITLE
Unable to use Optifine

### ISSUE THREAD

**Issue by Rosie714Posie** [sp614x/optifine#5472]
I get as far as downloading Optifine but my laptop labels it as unsafe to use. Is there a way around this, seeing as no one else is having this issue? The download website may be the issue, as it's labeled as unsafe by my laptop. Downloading it from the website only gives me a internet explorer thing to open.

**Comment by Cart3r1234** [comment]
All .jar files are marked as unsafe by most antiviruses; as long as you downloaded the .jar from optifine.net and didn't click any ads that may have been shown to you before/after the download, it is safe to open

As for opening it with java rather than internet explore, the program Jarfix solves this and can be found at https://johann.loefflmann.net/en/software/jarfix/index.html

**Comment by sp614x** [comment]
The JAR files downloaded from https://optifine.net are safe.
This can be confirmed by scanning the file with an antivirus or https://www.virustotal.com.
