### ISSUE TITLE
[1.17] Chunk not loading when you change dimension

### ISSUE THREAD

**Issue by AxeGt2802** [sp614x/optifine#5757]
## Description of Issue
When you , for example, go to nether or end , the chunk will are at 2 render distance and if you want to continue, the chunks do not load, you must disconnect and restart the game for it to load, but if you change dimension, the same problem appears: I have a quick video proof if you wish:  [https://www.youtube.com/watch?v=VHYqe0LYRLY&ab_channel=Axeloune]

## Steps to Reproduce
1. Go to another dimension , like the Nether
2. You will see that the chunk will not loading

## OptiFine Version
OptiFine 1.17 G9 pre18 ( i've used the pre17 and the same bug are also here)

## Installation Method
I've install my OptiFine version just with open the .jar and click install.

## F3 Debug Screenshot
![2021-06-10_10 40 20](https://user-images.githubusercontent.com/42324132/121494470-0f7f0180-c9d9-11eb-8520-bacda3862f95.png)

## Prior Testing

Does this happen in Vanilla without OptiFine?
This bug not happen without OptiFine

**Comment by sp614x** [comment]
Can't reproduce it in single-player. Is this multiplayer?
The portal transition seems to take too long.

**Comment by AxeGt2802** [comment]
It's not Multiplayer , you can see it in my video , i start a singleplayer world and idk why the transition was so long

**Comment by bigsoda2005** [comment]
I am having this exact same issue.

**Comment by KaiAF** [comment]
This could be related to #5762? But I am not able to reproduce this either

**Comment by KaiAF** [comment]
I believe you are right @mckellen98
![image](https://user-images.githubusercontent.com/60985521/121580683-a4dabf80-c9f2-11eb-9565-5c7095c5ca4a.png)

**Comment by 0x05** [comment]
Same thing here in single player. Never happened in previous versions. Render distance is usually 8-12 so that shouldn't be the issue.

http://puu.sh/HNUlJ/dece67b845.jpg

**Comment by hollmanovec** [comment]
This happens to me in pre-17 too, I am living in spawn chunks, so it loads them, but never loads anything further. My render distance was probably around 13-16

**Comment by codeyGuppy** [comment]
I can tie this to entities flickering in and out of existence from around certain blocks and positions. Luckily I had Shadowplay on to capture it.
[https://youtu.be/c14YMo0lAiE](url)

**Comment by Scorpion34** [comment]
This happens to me too render distance always lower than 16 however I was experiencing it with 64 render distance as well, it isn't related to rendering regions or fast render because I turned those off and it didn't work also tried reloading all chunks but that also didn't work the only current solution I could find is to exit the world and then rejoin. Here are my screenshots in the nether I don't have any screenshots of the overworld but this exact issue occurred for me as well. 

![2021-06-10_23 03 04](https://user-images.githubusercontent.com/15971924/121629347-9a471700-ca40-11eb-979a-a2fa7086f057.png)

![2021-06-10_23 03 23](https://user-images.githubusercontent.com/15971924/121629353-9c10da80-ca40-11eb-86f0-9094d2338495.png)

(I also tried chunk updates to 1 didn't work, tried smooth world on/off didn't work, I tried lazy chunk loading on/off didn't work, dynamic updates on/off didn't work, etc. Pretty much everything in the performance tab and anything affecting chunk loading, tested everything as well with an on and off state with no effect. So the only current solution is to leave and then rejoin the world.

**Comment by Hellster90** [comment]
I can confirm this report, every time you change dimensions through a nether portal the chunks will not load, or you end up with a black screen only showing the horizon and the sun (overworld).
Happens in both pre 17 and pre 18, with and without Fabric integration.
The only temporary fix i've found is to exit and start the game again, but as soon as you go through a portal again the same thing happens again,

**Comment by AxeGt2802** [comment]
I have retry with the pre19 version , the bug is still there unfortunately...

**Comment by Zondrus** [comment]
Im having this issue with some chunks in the end dimension

**Comment by T43omen** [comment]
My thread for the same issue was closed, so Id just like to add this screenshot if it can be of any help.
![121406811-9f1aa680-c92c-11eb-9c45-44f18c2b8963](https://user-images.githubusercontent.com/85641984/121725554-6824cc00-cab7-11eb-918d-38fd3c268071.png)

**Comment by sp614x** [comment]
Can anyone post an error log?

**Comment by KaiAF** [comment]
https://pastebin.ubuntu.com/p/pzTh69fVMN/ @sp614x got it

**Comment by sp614x** [comment]
Managed to reproduce it when running with the official launcher.
It doesn't happen when OF runs in development mode. Maybe reobfuscation gone wrong.

**Comment by sp614x** [comment]
When the chunk loading breaks, reloading all chunks doesn't help, looks like something in the integrated server.
Reloading resources doesn't help either.
Teleporting around doesn't seem to trigger it, only changing dimension when outside of spawn chunks.

**Comment by sp614x** [comment]
Changing render distance (which affects the integrated server) doesn't fix it either, may be related to #5762.

**Comment by AxeGt2802** [comment]
i hope you will find a way to fixed these !

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by Kancer8496** [comment]
Same issue here.

**Comment by Scorpion34** [comment]
> Same issue here.

This issue is closed use the latest optifine preview it fixes it, optifine in 1.17 does not like big worlds though so be maddeningly cautious if your playing hardcore or survival.

**Comment by Loyertaze** [comment]
same thing happening here, My minecraft world was started using 1.16 world generation then after a few weeks I updated to 1.17, by this time i havent really explored my world so that i can experience the new world generation then i explored and found an ocean monument, so i decided to hook that up to a nether portal for easy access and when i did i spawned isnide a geode wohoo fun stuff but to my suprirse i was shocked it wasnt loading.

 

I tried ways to fix this before making a post, so i first saved and quit and it worked!. But after the many of times i did entering the nether portal again the chunk problem just keeps happening.

 

For more info my render distance is just 14chunks and the monument is just 2000blocks away from spawn.

![BUGS 1](https://user-images.githubusercontent.com/86518806/123511369-cb1f8100-d6bb-11eb-9e98-422f9b947fa1.png)
![BUGS 3](https://user-images.githubusercontent.com/86518806/123511371-cce94480-d6bb-11eb-97a4-671dcb552307.png)
![BUGS 2](https://user-images.githubusercontent.com/86518806/123511372-ce1a7180-d6bb-11eb-88b6-c17ed13437aa.png)

**Comment by Loyertaze** [comment]
Ayo people, soo i fixed my problem, basically my launcher uses some pre 1.17 stuff with optifine and thats why the chunks loaded are not loading correctly, so what i did is i changed my game version into the 1.17 release without the optifine or anything modified to it and it worked marvels. Hope this is helpful to some of yall. Stay Safe!!!

**Comment by Hellster90** [comment]
> Ayo people, soo i fixed my problem, basically my launcher uses some pre 1.17 stuff with optifine and thats why the chunks loaded are not loading correctly, so what i did is i changed my game version into the 1.17 release without the optifine or anything modified to it and it worked marvels. Hope this is helpful to some of yall. Stay Safe!!!

That issue got fixed in Optifine a few weeks ago, since pre 21

**Comment by velnias75** [comment]
I've found out that there is a *hang* of the client dependent on the `view-distance`:

 * If I have a `view-distance` of `22` it will freeze the client for up to 6 minutes.
 * If I have a `view-distance` of `10` it will freeze the client for a few seconds.

I'm using `preview_OptiFine_1.17.1_HD_U_G9_pre27`
