### ISSUE TITLE
Spyglass zoom

### ISSUE THREAD

**Issue by Friskipoo** [sp614x/optifine#5791]
## Description of Issue
The Spyglass doesn't zoom
## Steps to Reproduce
1. Use the Spyglass

**Comment by KaiAF** [comment]
Zooms in for me. Can you send a F3 screenshot? Make sure that dynamic Fov is enabled also

**Comment by just-kevin2** [comment]
For me Dynamic FoV OFF disables the zoom of the spyglass, but not the (rectangular viewport) animation. Dynamic FoV ON fixes it. I still think this is a bug, since the spyglass is a vanilla feature so it should work regardless of the chosen setting. The spyglass still works if I turn the FoV Effects to OFF in vanilla minecraft.

**Comment by KaiAF** [comment]
Already addressed here: #5736
