### ISSUE TITLE
[Bug] Lag spikes with render distance above 32

### ISSUE THREAD

**Issue by PainApp1e** [sp614x/optifine#5853]
## Description of Issue
When rendering above 32 chunks, frequent, almost patterned lag spikes occur

## Steps to Reproduce
1. Open minecraft with render distance above 32
2. Wait for enough chunks to load

## OptiFine Version
1.17 pre21

## Installation Method
Opened jar file

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/85756033/123143024-5c8fb880-d45a-11eb-93cc-62388e8be05f.png)

## Prior Testing
Does not happen in previous versions (1.16.5)
Idk if this is a minecraft or optifine issue since i cant render higher than 32 in vanilla and even then it lags horribly

**Comment by DaCoolKitty** [comment]
Since 1.17 terrain has been modified from previous versions it may be laggy generating new terrain, and it is not as optimized as other versions since it was just implemented.


### FIXES

- If this happens when standing still, you can make it occur only when moving by going to the setting "Performance > Dynamic Updates" and changing it to off, which will make it only occur when moving. 

- Another Fix could be allocating more RAM to Minecraft, since just by standing still you are reaching 86% of the allocated RAM (you have 2GBs allocated, maybe try 3 or 4)

- In general 32 chunks is a laggy experience, so I would recommend turning it down to something around 25 if Minecraft keeps lagging.

**Comment by Jiingy** [comment]
It's generally advised to not play with a render distance as high as 32 even with good hardware. Combine the lower down worlds if you use the 1.18 datapack and it's unavoidably more laggy. I'd recommend playing with a render distance around 16-20 if you want a higher than normal render distance.

**Comment by Jiingy** [comment]
Closing as this isn't all that unusual behavior for high render distances.
