### ISSUE TITLE
Crashes after loading into a world

### ISSUE THREAD

**Issue by marchhofmann1** [sp614x/optifine#5921]
Game crashes instantly after loading into a world with an active shader.

Computer:
MacBook Pro M1

**Comment by marchhofmann1** [comment]
On version: OptiFine HD U G9 pre24, 1.17

**Comment by Whitelisted1** [comment]
Shaders have been causing problems with Macs, so you might just have to wait until the official release of optifine to use shaders. Not sure if this will help, but there are other mods that may help (unsure if mc will still crash with them on instead of optifine though). One is Iris that runs with fabric

**Comment by KaiAF** [comment]
Already addressed here: #5900.
