### ISSUE TITLE
[Category] Clicking shaders in the menu crashes the game

### ISSUE THREAD

**Issue by sleepyheadkarsten** [sp614x/optifine#5956]
## Description of Issue
Turning shaders on in the menu immediately crashes the game. 

## Steps to Reproduce
1. I downloaded the 1.17 complementary shaders.
2. Try to select the shaders in the shaders folder and it crashes the game.

## OptiFine Version
1.17 G9 pre24

## Installation Method
I downloaded it from your official twitter and opened it for it to auto-install.

**Comment by Zamboni1** [comment]
I'm having the same problem, at first I thought I had too low ram or something so I changed ram to 4gb instead of two but that also crashed my game, another thing is I can activate shaders in the start menu no problem but as soon as I try to start a world it crashes, same if I try to enable it while already playing in a world.

**Comment by Ari-RERA-43** [comment]
I had this issue while playing on Forge awhile back but I haven't been able to reproduce it since then.

**Comment by KaiAF** [comment]
Can you provide a crash log?
