### ISSUE TITLE
Black pixels for blocks, seeds, saplings, crafted items like chests

### ISSUE THREAD

**Issue by xY00RA** [sp614x/optifine#5961]
Hello, 

I am using Sildurs Vibrant Shaders 1.29 Lite, however, some blocks and items appear as black pixels.

![image](https://user-images.githubusercontent.com/86863424/124341367-bfcfc800-db89-11eb-9344-15a4315e0bd4.png)

Little info about my PC, I currently have an integrated graphics card. AMD Ryzen 5 3400G Quad-Core 3.7 GHz Socket AM4 65W YD340GC5FHBOX Desktop Processor AMD Radeon RX Vega 11

Any help is appreciated! The shader is fine otherwise, no lag, no frame skip, absolutely lovely!!

Thank you!

**Comment by Ari-RERA-43** [comment]
This has already been reported. There is no fix besides disabling shaders.

**Comment by xY00RA** [comment]
> This has already been reported. There is no fix besides disabling shaders.

Is there going to be a fix? I'm sorry I tried searching google and nothing was popping up! Would you know if I have to wait until I guess the official optifine release? Or would you know if any shaders work rn? Because my friends don't have a problem, but I do, and we can't pinpoint why?

**Comment by Ari-RERA-43** [comment]
1: There will probably be a fix soon
2: You may have to wait until the full release but that's probably not too far off
3: No, I don't know of any shaders that do not have this issue
4: You could try resetting video and shader settings but I can't guarantee that will fix it

You should also close this issue because it's a dupe.

**Comment by xY00RA** [comment]
Thank you! I shall close it now!!
