### ISSUE TITLE
Chisel & Bits Compatibilty 

### ISSUE THREAD

**Issue by whitestarx0312** [sp614x/optifine#60]
There is currently an issue in the 1.9.0 version of Optifine and the forge mod "Chisel & Bits." 
I don't actually know what is causing it, but the author referred to it here: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/29

**Comment by sp614x** [comment]
Forge adds a new model rendering (pipeline), Optifine is built on the vanilla model rendering.
Currently OptiFine disables the Forge rendering pipeline, because it breaks all model related OptiFine features (shaders, connected textures, better grass, better snow, custom colors, etc).

**Comment by sp614x** [comment]
I could try to enable the Forge pipeline only for non-vanilla (mod) models. 
The non-vanilla models will lose connected textures and custom colors (probably not relevant for them).
Shaders, AA and AF will be problematic.

**Comment by whitestarx0312** [comment]
It seems the author of Chisel and Bits has implemented something that fixes blocks on his end. My bug is only when using blocks from the Chisel mod (http://tinyurl.com/osl4v6j) which I assume is something on their end because Chisel is in such an early alpha.

With that said I don't see why you need to do anything with Optifine, but thank you for the quick response and sorry for this obsolete report.

**Comment by AlgorithmX2** [comment]
@whitestarx0312 Support for the forge pipeline would be a good feature on optifine's end, a lot of mods expect that it is used, and moving forward more mods will continue to be created that require it for one or more reasons.

I have had to disable features to enable compatibility in the mean time, however that means that when using Optifine certain features simply don't work properly, that is not a great solution in the long run, but rather a temporary fix.

**Comment by whitestarx0312** [comment]
Hmm okay that makes sense.

**Comment by bunSakurAing** [comment]
1.8.9 also have the same problem

**Comment by JCMais** [comment]
This is also a problem with Tinkers crafting stations.

**Comment by AlgorithmX2** [comment]
Seems that RenderWorldLastEvent with shaders continues to be an issue since most mods I've checked that use it use it to render in-world overlays.

C&B just added a new measuring tool, and FTBUtils uses it to do chunk/light overlays as well as two examples.

Seems the the worst issues is that any GL_LINES seem to disappear, possibly because they are too thin unsure exactly, The FTBUtils overlays seem to have some usual alpha issues where its opaque instead of transparent. And my Text Overlays seems to blend into the sky or have strange transparency  associated with it.

I'm not sure what the best solution is, but from my testing it seems to be using the cloud shader or GL State, which results in the rendering producing invisible or unusual results.

This seems to be the only event available for this sort of thing with forge at the moment, so optifine may have to make some special provision to enable those overlays to render properly.

**Comment by sp614x** [comment]
The correct issue is probably: AlgorithmX2/Chisels-and-Bits#60 and https://github.com/sp614x/optifine/issues/198

The rendering order is important for the shaders. If the RenderWorldLastEvent has to be fired at the end of the rendering then OptiFine can't do much about it. 

The shaders have full control over the rendering and they can organize the pipeline however they wish. For example: the terrain is rendered in buffer A, then the water is blended with buffer A and the result is put in buffer B, then the hand is drawn in B, it is mixed with special effects and put in buffer C which is shown on screen. If the RenderWorldLastEvent tries to render terrain after the water is rendered then it will write to A, but A will not be read anymore because the water rendering is finished and only the water program can move the data from A to B. The water program is using a translucent logic (water reflections, etc) so it can not be used to draw non-water objects.

**Comment by Dushess** [comment]
Continues even with Ultra D2 for 1.10.2 (it compatible with Forge 2099)

That panel is on the calling block, but everything "chiseled" still have problems.
![2016-11-15_22 05 30](https://cloud.githubusercontent.com/assets/15954961/20325127/c0bbfe22-ab9c-11e6-9cbe-4ced885933f3.png)

**Comment by Dushess** [comment]
In D3 it working fine, thanks..

**Comment by Dushess** [comment]
Strange thing, on my installation new D3 for 1.10.2 just won't work. Behavior like in D2, but game main menu shows Forge ... 2099 (Last in launcher) and OptiFine ... D3. You will laught, but in other place, that i played, all is fine.
And nothing suspicious in the log.
