### ISSUE TITLE
Optifine patches/removes a field from RenderChunk causing a crash if mods try to reference it.

### ISSUE THREAD

**Issue by iChun** [sp614x/optifine#602]
Crash log here: https://github.com/iChun/IssueTracker-Mods/issues/61
and here: https://github.com/iChun/IssueTracker-Mods/issues/56#issuecomment-293927013
and here: https://github.com/iChun/IssueTracker-PortalGun/issues/58

iChunUtil creates a new class that extends RenderChunk. When referencing the region (searge name) field (new in 1.10 I think) it crashes.

**Comment by sp614x** [comment]
The field `private ChunkCache region;` has been moved inside the method `rebuildChunk()` to fix various crashes caused by race conditions.

Sometimes the vanilla multi-threaded chunk loading may load the same chunk on two different threads at the same time. This **should not** happen, but it **still** happens from time to time (multi-threaded synchronization is hard). Aditionally the method `resetChunkCache()` which modifes the ChunkCache is being called on the render thread. When the ChunkCache is a shared object field this leads to strange and hard to reproduce crashes due to race conditions (the ChunkCache class is not thread safe).

Moving the ChunkCache inside `rebuildChunk()` fixes this. If two threads happen to load the same chunk at the same time then each one would use its own ChunkCache.
