### ISSUE TITLE
[Crash] Game Crashes

### ISSUE THREAD

**Issue by TTangerines** [sp614x/optifine#6026]
## Description of Issue
Whenever I try to play the game with Optifine installs, it crashes and displays 'exit code 0'

## OptiFine Version
So far all of them except for pre21

**Comment by fayer3** [comment]
Are you on macos and have shaders enabled? They don't work yet with macos.

**Comment by KaiAF** [comment]
Can you send a crash log?

**Comment by delpiero224** [comment]
Same for me. Getting an "Could Not Create the Java Virtual Machine" error and Minecraft crashes. Works fine with the regular profile (without Optifine), however.

Which log do you need? Can't see any Minecraft log (since it doesn't start), but part of the launcher log is attached:

[minecraft log.txt](https://github.com/sp614x/optifine/files/6879568/minecraft.log.txt)

**Comment by KaiAF** [comment]
The original author has not responded so I'm going to close this. Your issue @delpiero224 is that you most likely need to update java to 16
