### ISSUE TITLE
Transparent grass

### ISSUE THREAD

**Issue by MODKILLER1001** [sp614x/optifine#613]
Grass is transparent in the end biome

**Comment by sp614x** [comment]
Screenshot, resource pack?
Forge installed, mods?
Error log?

**Comment by MODKILLER1001** [comment]
No resource packs installed. Latest optifine. Grass 3d block sorta is transparent on the grass block.
http://prntscr.com/f2r9z8 http://prntscr.com/f2ra2m

**Comment by Builderb0y** [comment]
I've seen this in the end dimension as well ([screenshot](http://i.imgur.com/9Z8D1vJ.png)), but haven't managed to reproduce it in the overworld, even when an end biome exists there. Using shaders in that screenshot to set skytextured to pure white so it's easier to see, though this isn't necessary. Also currently using version 1.10.2_HD_U_D7.

It seems to be an issue with mipmapping, as disabling it fixes the issue. Also only occurs after you're far enough away for mipmapping to take effect. Perhaps textures that end up being semi-transparent after mipmapping prevent fully-opaque mipmapped textures behind them from rendering at all due to them failing on depth testing?

However, this doesn't explain why it only effects the end specifically, or why only some blocks fail to render (grass being one of them). It isn't shown in that screenshot, but end stone does successfully render behind the mipmapped leaves/grass. Perhaps biome coloring has something to do with it as well?

**Comment by sp614x** [comment]
I can reproduced it, seems to be connected to the End sky rendering.
Turning the sky OFF fixes the grass in the End.

**Comment by sp614x** [comment]
Updated preview B9
- - fixed tall grass rendering in the End when mipmaps are enabled
