### ISSUE TITLE
Optifine breaks/blurs 48x48 textures

### ISSUE THREAD

**Issue by Nazenn** [sp614x/optifine#618]
I'm an artist working on mod support for the Lithos Resource Pack. I noticed today that when optifine is enabled, our 48x48 flora goes from looking like this without optifine:
https://www.dropbox.com/s/99v4lzzc5udr5nc/2017-05-03_13.39.35.png?dl=0
to this with optifine:
https://www.dropbox.com/s/27e0yrmzeigrmst/2017-05-03_13.40.41.png?dl=0
As you can see there's quite a noticeable blur. The texture itself has no translucent pixels and renders fine otherwise. It happens on BOTH modded and vanilla flora, anything with a 48x48 texture.

Using OptiFine_1.11.2_HD_U_B7 however I have also noticed it in older versions as well.

Yes I'm aware thats also an odd texture resolution, however vanilla minecraft does support it, and a handful of resource packs use it so it is breaking functionality unfortunately.
Any chance for a fix? Also let me know if there's any other data I can provide to help out or if you want me to run any more tests for you.
Also a quick thank you for your work, not just with making optifine itself which is an essential mod for me, but spending so much time working on bug reports and supporting optifine so diligently.

**Comment by sp614x** [comment]
This is a side effect of enabling mipmaps.
When mipmaps are enabled ALL block textures must have power of 2 dimensions (16, 32, 64, 128, etc) otherwise either the mipmaps can not be fully used or there would be visual artifacts (lines on the block edges).
In this situation vanilla Minecraft decreases the mipmap level until it is compatible with all textures, effectively removing the texture smoothing at a distance. This results in visible flicker in distant objects.
OptiFine takes another approach and scales up all problematic textures to a power of 2 dimensions so that mipmaps can work correctly. This guarantees that there is no flicker at a distance. The user is free to decrease the mipmap level or disable mipmaps if he does not like the scaling.
To fix it either:
- disable or decrease the mipmap level (Video Settings -> Quality -> Mipmaps)
- use textures which have power of 2 dimensions

**Comment by Nazenn** [comment]
Thank you very much for the clarification on how that works and why it became an issue. I very much appreciate it.

**Comment by Builderb0y** [comment]
Just out of curiosity, can you elaborate on why non-power-of-2 texture sizes cause problems? I can understand smaller-than-normal textures limiting the maximum mipmap level or lines appearing on block edges if the resolution isn't divisible by two, but 48 is a multiple of 16, so I don't see any specific reason why they can't be scaled to 24x, 12x, 6x, and 3x when mipmapped.

**Comment by sp614x** [comment]
A power of 2 texture can use all available mipmaps levels. For example a 32x texture can use 5 levels (16x, 8x, 4x, 2x and 1x). This means that when needed the texture can be represented as a single pixel.

Non-power of 2 textures can not go down to 1x. For example 48x can use 4 levels (24x, 12x, 6x and 3x). The smallest 3x texture has 9 pixels (3x3). 

When the texture is visible as 1 pixel on the screen the GPU takes the smallest size (3x) and samples 1 pixel from it. When moving around the sampling is selecting different pixels from the 3x3 texture and it looks like the one pixel visible on the screen is flickering.
