### ISSUE TITLE
[CEM] limb_swing does not seem to represent actual limb swing when used with bone.ty

### ISSUE THREAD

**Issue by joshieman06** [sp614x/optifine#6197]
## Description of Issue
When setting bone.ty to `limb_swing * 10`, it doesn't work correctly

## Steps to Reproduce
1. Set an animation for body.ty on the pig to `limb_swing * 10`
2. Observe

## OptiFine Version
1.17.1 OptiFine HD U G9 pre33

## Installation Method
Standalone Jar

## F3 Debug Screenshot

![2021-08-29_09 20 35](https://user-images.githubusercontent.com/71846165/131257641-cd9b7acf-b5b7-4af6-bbbc-0c11503d455a.png)
## Additional Information

https://user-images.githubusercontent.com/71846165/131257737-a55982ac-6f15-4cec-bb2b-bfaadddfb6d1.mp4

**Comment by ZenithRogue** [comment]
Can you describe what you hoped to accomplish with `limb_swing`?

The variable `limb_swing` is an integer representing the number ticks in which the mob has moved

**Comment by ZenithRogue** [comment]
to produce a swinging motion, you would do `sin(limb_swing)`

to produce the standard swing of a mob's legs `limb_speed*sin(limb_swing)`

`limb_speed` is a float that represents how fast something is going

**Comment by sp614x** [comment]
Using `this.rz` instead of `slate.rz` fixes the problem.
This part of the docs is important:
```
# The model can be:
#  "this" - current custom model
#  "part" - the original part model to which the custom model is attached
#  "<part>" - original model by part name  
#  "<id>" - custom model by ID
#  "<part>:<sub_id>:<sub_sub_id>:..." - (hierarchical) start with original model by part name, then find children by ID
#  "<id>:<sub_id>:<sub_sub_id>:..." - (hierarchical) start with model by ID, then find children by ID
```
The models are rendered like this:
- parent model update (animations)
- parent model rotate/translate
- parent model render
- render child models (update + rotate/translate + render) 

CEM works by making the parent invisible and attaching the new model to it.
The animation is in the child model (CEM) update.
When the child tries to change the rotation of the parent model it is too late as the parent model has already been rendered.
The child model can only change its own rotation or the rotation of its children (or other top models rendered after it).

**Comment by Rey2723** [comment]
ZenithRogue, how can i make the standard sswing of a mob's leg without using limb_speed or limb_swing in minecraft bedrock json files?
