### ISSUE TITLE
Parrots With Random Textures Lose Them When On Your Shoulder

### ISSUE THREAD

**Issue by MentallyFloridian** [sp614x/optifine#6223]
## Description of Issue
When A Parrot With A Random Texture Is On Your Shoulder, It Reverts Back To Its Default Texture

## Steps to Reproduce
Use a random textured parrot and put it on your arm

## OptiFine Version
1.17.1

## Installation Method
Standalone Installer

![2021-09-05_22 38 15](https://user-images.githubusercontent.com/90166057/132152855-38c5f6e5-bc8c-4729-9d8f-b06041816758.png)

^^^^
## Prior Testing

I am not sure if this is a bug, or the texture has to do with the players model or smth and can be fixed some other way

**Comment by MinecraftMinun** [comment]
I looked into it and this bug is weirder than expected. With my resource pack, parrots are set to have random textures, but can also be renamed.

When flying around in game, they render as expected.
![2021-12-21_20 15 42](https://user-images.githubusercontent.com/22704209/146913009-ebf8dc8f-2e9a-42c5-bd1c-7b7ec8540b2e.png)

When in inventory, they show as the default parrots. (As noted in the bug report)
![2021-12-21_20 12 56](https://user-images.githubusercontent.com/22704209/146913069-f7330f06-b5e1-4a39-8fec-8bf4f47e4af6.png)

Now here's the really weird bit: when shown in f5 on the shoulder, they render as two completely different parrots.
When a parrot gets off and gets back on the shoulder, the parrot has the same texture as when it was on the shoulder previously.
![2021-12-21_20 14 50](https://user-images.githubusercontent.com/22704209/146913177-c382200e-79a6-41c1-881d-9fcea9abd01b.png)

After finding this out, I decided to test it with a parrot skin that only appears via renaming. Here's it in game, rendering as expected.
![2021-12-21_20 23 23](https://user-images.githubusercontent.com/22704209/146914172-b0c0030e-9d37-4c3d-ad6b-77ed944e7a50.png)

When on my shoulder, it renders as a random parrot, not what it should be when renamed.
![2021-12-21_20 23 38](https://user-images.githubusercontent.com/22704209/146914239-97bf36c4-5085-4f5f-98f5-b41013c84b6d.png)

This all leads me to believe that the game somehow treats the parrots on the shoulders and the parrots in the world as different things, with the parrot on the shoulder being a parrot without any entity data (as seen by the fact that the named parrot doesn't work and renders with a random texture. 
I'm not 100% on this conclusion, as I'm not familiar with how minecraft's code works.

**Comment by sp614x** [comment]
Fixed, coming in next preview.
