### ISSUE TITLE
[Localization] Create zh_hk.lang

### ISSUE THREAD

**Issue by THGABS** [sp614x/optifine#6513]
Minecraft had added a new Chinese variant `zh_hk` in 1.17, so its translation for OptiFine should also be added.
The file below is the translation file I've made, based on zh_tw.txt and tweaked into TXT format.
[zh_hk.txt](https://github.com/sp614x/optifine/files/7775979/zh_hk.txt)

**Comment by Regnander** [comment]
Good job and thanks for translating, but in order to add your translation you need to do this instead:

1. Go to https://github.com/sp614x/optifine/new/master/OptiFineDoc/assets/minecraft/optifine/lang.
2. Enter `zh_hk.lang` in the small text field that says "Name your file...".
3. Copy-paste the content of your txt file into the large text field below.
4.  Click the green "Propose new file" button at the bottom of the screen.
5. Click the green "Compare & pull request" button at the top of the screen. 
6. Finally click the green "Create pull request" button.
