### ISSUE TITLE
Portal Gun other end render incompatible with optifine

### ISSUE THREAD

**Issue by Umbrew-Foxiroe** [sp614x/optifine#664]
https://github.com/iChun/IssueTracker-Mods/issues/81 It works if in the config the other side's render system is off, but it's quite annoying to have to pick between good FPS / shaders and that...

Is it possible for something to be done about this? I've got a pretty old CPU processor, so it makes it extremely hard to go without Optifine for heavily modded Minecraft 1.10.2 ; Skyblock maps have good FPS without but if it's an overworld map and such then Optifine is almost necessary to have proper gameplay for me.

Even if it'd be a compatibility version of optifine with less features or something, I'd be willing to use that, as long as it doesn't break things like this...

**Comment by sp614x** [comment]
Crash log, game output?

**Comment by Umbrew-Foxiroe** [comment]
[crash-2017-05-22_21.48.01-client.txt](https://github.com/sp614x/optifine/files/1020680/crash-2017-05-22_21.48.01-client.txt)

[latest.txt](https://github.com/sp614x/optifine/files/1020684/latest.txt)

There's the logs from the crash, hope one of those two have what ya need; other people have had issues even with just optifine and portal gun, so figured the modpack I'm playing on wouldn't make it too different.

**Comment by sp614x** [comment]
Relevant part of the crash log:
```
java.lang.NoSuchFieldError: field_189564_r
    at ... RenderChunkWorldPortal.func_178581_b(RenderChunkWorldPortal.java:71)
```

**Comment by sp614x** [comment]
The RenderChunkWorldPortal is trying to access the private field `private ChunkCache field_189564_r;` from RenderChunk.

OptiFine moves the field inside the method rebuildChunk() because the chunk cache is not thread safe and it should not be stored as a class field. This fixes a lot of problems caused by race conditions when accessing the chunk cache.

The RenderChunkWorldPortal can override createRegionRenderCache() and keep its own copy of the ChunkCache if needed.
