### ISSUE TITLE
[Bug] Cape not found

### ISSUE THREAD

**Issue by 9Epic** [sp614x/optifine#6657]
Every time I try to change my cape I am met with an error that says "Cape not found for 9Epic." Prior to this happening I was experimenting with multiple cape designs and changed my cape several times. Is there any way I can fix this?
![image](https://user-images.githubusercontent.com/101084838/156974933-4ef0b8b3-bb6f-45bc-a00c-c821251fcec9.png)
![image](https://user-images.githubusercontent.com/101084838/156977233-6ce4e7fa-d46c-4eea-b02b-6bedb2ffdcd5.png)

**Comment by vinc3nz** [comment]
Dublicate of #6586
Discord FAQ post:
Q: Why does it say "Server error" when I try to edit my cape or move it?

A: Your cape is broken. While we don't know why this happens, we just know it happens. You need to make a ticket in #support-tickets and let us know with your Minecraft username. Only we can fix this, sorry for the inconvenience.

Please understand it might take some significant time in order to fix your cape, as only sp614x can fix it.

**Comment by KaiAF** [comment]
Yeah join the discord and make a support ticket. https://optifine.net/discord
