### ISSUE TITLE
Juvy Client - Optifine

### ISSUE THREAD

**Issue by jamgr** [sp614x/optifine#6802]
Hello,

I am writing to you today to request permission to use **Optifine** in an upcoming client, Juvy Client.

This will be paired with our server, 'Juvy Network'. We have a team of commited developers behind us, ready to start developing as soon as this licence is approved.

Thanks,
James

Discord: lunar#1235

**Comment by Rodney-RWR** [comment]
Hello, Head Dev/Owner of Juvy Client here if you check your optifinex email there is a full description of use we would be using optifine and how, it is under the name of Rodney Client, The client has gone through 2 rebrands since!

**Comment by TheKodeToad** [comment]
Rodney Client

This has gone too far!

**Comment by Rodney-RWR** [comment]
> Rodney Client
> 
> This has gone too far!
> 
> As far as I am aware, no client has officially got permission to use OptiFine. I can't say for sure, but OptiFine itself is a client.

optifine is a mod not a client this client is discontinued because of reasons and has gone back to just Neptune Client

**Comment by TheKodeToad** [comment]
> > Rodney Client
> > This has gone too far!
> > As far as I am aware, no client has officially got permission to use OptiFine. I can't say for sure, but OptiFine itself is a client.
> 
> optifine is a mod not a client this client is discontinued because of reasons and has gone back to just Neptune Client

I personally consider it to be a client, because you can use it standalone.
Forge itself, is a client, but not its mods.

This is sort of like "is cereal soup?", and this probably isn't the place to discuss these things.

However, because of OptiFine's distribution rules (https://www.optifine.net/copyright), I doubt any client has got permission to use it, and you'll find that most (traditional) modpacks don't include it.

I admit I may have used an automatic OptiFine version scraper in a few of my launchers and mods (simply for user experience), but that is more of a grey area.

You could scan the user's .minecraft to see if they have it installed, therefore you don't have to worry about any distribution issues.
