### ISSUE TITLE
native Apple Silicon support

### ISSUE THREAD

**Issue by jacobB1290** [sp614x/optifine#7000]
with the release of 1.19, Minecraft has officially added native support for apple silicon macs. This greatly improved performance from being apple to use Fabulous graphics and increasing frame rates to well over 100fps with maxed out settings, but sadly all these improvements are gone once you use optifne. No more fabulous graphics support and frame rates lower than without optifine. imagine what native apple silicon support could unlock. and if support is being worked on, we would love to try out beta versions while it is being developed.

**Comment by Nico314159** [comment]
Absolutely agree as an M1 user. Optifine is supposed to *boost* FPS!

**Comment by mindforger** [comment]
>we would love to try out beta versions while it is being developed

I am sure spx614x would love to tell an apple m1 device his own, maybe one of you could buy him one?

**Comment by sp614x** [comment]
Minecraft (Java) is not using native code for any performance related functionality.
If there is a difference between vanilla and OptiFine on a Mac then it is probably caused by different JVM, JVM arguments or the Mac recognizing Minecraft as a performance application.
You can compare the vanilla and OptiFine profiles in the launcher and see if there are differences in JVM or JVM arguments.
