### ISSUE TITLE
[1.19.2] Optifine needs a rebuild to forge 43.2.0+

### ISSUE THREAD

**Issue by Vectrobe** [sp614x/optifine#7261]
## Description of Issue
Some mods have issues with optifine, in that internal minecraft rendering functions are missing, presumably due to transform miss-matching as a result of running optifine for forge 43.1.52 atop of 43.2.0.
However many mods have 43.2.0 as a minimum requirement, since this is the current stable version.

## Steps to Reproduce
- create an instance of minecraft with forge 43.2.0
- add optifine 1.19.2 I1 (forge 43.1.52)
- add immersive engineering for example
- scroll through the creative menu for said mod, the game will freeze when the crash occurs
- check the logs and see how many crashes occurred, I've seen three for example since they occur inside multiple render threads
- `java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.vertex.PoseStack.pushTransformation(com.mojang.math.Transformation)'
	at net.minecraftforge.client.extensions.IForgeTransformation.push(IForgeTransformation.java:51) ~[forge-1.19.2-43.2.0-universal.jar%23242!/:?] {re:classloading}` is a snippet of a prime example

## OptiFine Version
"1.19.2 OptiFine HD U I1" (forge 43.1.52)

## Installation Method
downloaded it and put it in the mods folder of course

## Fabric/Forge Version
Forge 43.2.0

## OptiFabric Version
x

## Other Installed Mods
there's a lot here, but immersive engineering is the primary one that crashes with the current optifine
bookshelf, create (flywheel), balm, applied energistics 2 and quark also have transforms/mixins that show in these crashes, but how much those in particular are affected I haven't seen
the full list of mods are in the crash log if you want to check all of them

## Log Files/Crash Reports

[debug.log](https://github.com/sp614x/optifine/files/10553654/debug.log)
[latest.log](https://github.com/sp614x/optifine/files/10553655/latest.log)
[crash-2023-02-01_16.20.56-client.txt](https://github.com/sp614x/optifine/files/10553661/crash-2023-02-01_16.20.56-client.txt)

note that these logs dont seem to cover the entire set of text dumped to the console, which of itself is very very long

## F3 Debug Screenshot

![2023-02-01_16 48 55](https://user-images.githubusercontent.com/3912867/215962518-85960160-1896-467d-a15a-b9c14d5fb601.png)

## Prior Testing
problem does not occur with optifine on its own, or at least it doesnt seem to
problem does occur with various mods that require the vanilla functions to be intact as expected for forge 43.2.0
problem does not occur with these mods if optifine is not present
other problems occur if forge 43.1.52 is used, since this is a much older build of forge and is _not_ marked stable, many mods have since been built on 43.2.0 which _is_ marked stable

## Additional Information
1.19.3 is still very new, and thus forge and many mods don't have full (or any at all) support for it yet
the currently released version of forge at this time of writing is 43.2.4, though I would not recommend building for that new of a version

**Comment by omerien** [comment]
The problem isn't compatibility with other mods but the compatibility with Forge.
Many things can change between 2 versions of Forge, and OptiFine doesn't like changes.

**Comment by Ibirtem** [comment]
True. Waiting for the bug fix! There are not so much mods on 1.19.3 to switch to it!

**Comment by SKiiDROW** [comment]
lol and that's why you can take your time with it? :D Many mods are on 1.19.3 you talk trash!!! 

And it's a problem that Optifine no longer runs with Forge. 
But no matter with the slow speed Fabric gets new wind times. Most have to switch because most servers already run with 1.19.3. 


2 weeks we wait now and it is still no Forge fix appeared.

**Comment by SKiiDROW** [comment]
lol and that's why you can take your time with it? :D Many mods are on 1.19.3 you talk trash!!! 

And it's a problem that Optifine no longer runs with Forge. 
But no matter with the slow speed Fabric gets new wind times. Most have to switch because most servers already run with 1.19.3. 


2 weeks we wait now and it is still no Forge fix appeared.

**Comment by toutlamer** [comment]
I can’t respect someone that uses "lol" to start their complaint, but I guess I’m talking to a young person who think they can give lessons, so I’ll explain to you :

OptiFine is a mod coded by a single person, which is closed source because of legal reasons. It modifies the game in ways that normal mods usually don’t touch, so a comparison with other mods is irrelevant. If you’re not happy, switch to another optimization mod.

**Comment by SKiiDROW** [comment]
> I can’t respect someone that uses "lol" to start their complaint, but I guess I’m talking to a young person who think they can give lessons, so I’ll explain to you :
> 
> OptiFine is a mod coded by a single person, which is closed source because of legal reasons. It modifies the game in ways that normal mods usually don’t touch, so a comparison with other mods is irrelevant. If you’re not happy, switch to another optimization mod.

Save yourself the denunciation. I am perfectly capable of reading things. You don't have to go through everything twenty times.

That doesn't change the fact that it takes too long. You don't have to explain anything to me. I know what I'm talking about....

And don't worry, I already have :) 
Because factually it looks like compatibility is now a few months off ;) 

But I wish you only the best.... 



####lol####

**Comment by toutlamer** [comment]
I am also using another mod for recent versions of Minecraft, but if you do, don't come here to spread negativity ; it doesn't help anyone

**Comment by Vectrobe** [comment]
since we're talking about updating optifine between two close forge versions on the same version of minecraft, I expect the changes to be very minimal, a far cry from updating from 1.19.2 to 1.19.3, unless someone with access to the source can convince otherwise.

**Comment by clarity8080** [comment]
I don't know why any mod uses optifine anymore. Every time I've ever tried to use it, it never works. I believe I had to use forge 43.2.1 for cobblemon, and no matter what else I took out for mods, I couldn't get optifine to work, so I just gave up. Sad, because I wanted to try out glowing ores. I thought that would be a cool combo with Cobblemon, mine easier to get to the main game quicker and look cool at the same time. But.....whatevs. I guess I'll do without.

**Comment by Plutonicwave** [comment]
Is this why whenever I play on [1.19.2] forge 43.2.0, I get booted out of the game before it even gets to launch, and it just gives me the error code "Exit code 1" when I use optifine? This only happens when I add optifine and I've tried (OptiFine HD U H9) & (OptiFine HD U I1) to no avail.

**Comment by sp614x** [comment]
Updated to Forge 43.2.14
