### ISSUE TITLE
Launch crash using Optifine 1.12 HD U C3

### ISSUE THREAD

**Issue by Anno861** [sp614x/optifine#729]
I get this crash when attempting to use Optifine 1.12 HD U C3:

https://pastebin.com/dk6aEmg1

This is using Forge 14.21.0.2373, and Java 1.8.0_91 on OS X 10.10.5. Full log here: https://pastebin.com/AvHFSKPN

I haven't modded in a while, so if the solution is blindingly obvious I apologise. I will also try rolling back to the other Optifine versions and, if need be, older Forge versions.

**Comment by SetantaLP** [comment]
I would try downgrading Forge to 14.21.0.2331, because that's the version which should be compatible according to the changelog.

**Comment by sp614x** [comment]
OptiFine is compatible with Forge #2331.
Forge is currently rewriting the registry system and is unstable.

**Comment by SimonOrJ** [comment]
Latest Forge version that works with Optifine 1.12 C3 seems to be "14.21.0.2362".

Something that they did here may have broken it for the latest version of Forge:

```
Build 1.12-14.21.0.2363:
	fry:
		Cleanup of model system, taking advantage of java 8; replaced guava
		Optional and Function with java 8 versions.
```

**Comment by SetantaLP** [comment]
@SimonOrJ that's right. But I think the main problem is that optifne is more a stand alone mod for minecraft than a forge mod, because forge is not required for running optifine but optifine can be used with forge so that you can use it with other mods. And that means that it's required to make a lot of changes on your own (I already saw that, because I once decompiled an optifine-modded minecraft to start a modded client), but do that in a way that they don't collide with the changes forge makes. I just looked a little bit into minecraft and optifine: So including the files for "normal" and anonymous inner classes Minecraft in 1.10.2 consists of 2917 class-files. And optifine in 1.10.2 D6 adds 141 class-files (in the default package), 62 class-files in `net/optifine/entity/model`, 32 class-files in `net/optifine/entity/model/anim`, 7 class-files in `shadersmod/common`, 47 class-files in `shadersmod/client` and also patches 203 class-files (approximately 7% of minecraft's class-files). So it's a quite huge mod and it might be hard not to break something inside optifine, if you are changing something in forge which is somehow related to rendering or to the other optimizations optifine makes.

And the problem for forge is, that people will complain at them if they change something and that breaks a mod like optifine (no matter that there is a note in the changelog for which forge-version is compatible with this optifine-version), because these people often simply don't know or understand how that stuff works, so how should you explain them the problem without explaining them the whole world? So that might have lead the forge-team to the decision that core-mods (or any other mod that directly alter minecraft code) should have some kind of visible source, so that it's easier for them not to break such mods directly by changing some things inside the forge minecraft-patches. But I can also understand that people don't want others to see their code. So it's a very difficult situation.

**Comment by sp614x** [comment]
@SimonOrJ Currently Forge is in the process of rewriting a lot of things.
OptiFine will be made compatible with latest Forge when Forge stabilizes.

**Comment by sp614x** [comment]
Preview C4 for 1.12 is out
 - compatible with Forge #2387
