### ISSUE TITLE
[Feature Request] Option for display entities to still render when looking away

### ISSUE THREAD

**Issue by jakestrash** [sp614x/optifine#7377]
## Description of the new feature
In vanilla minecraft, block displays will still render when you're not looking at where the entity actually is - this is useful if the entity is scaled up a large amount; the player can look at it from any angle and still be able to see it.

When using Optifine, this is not the case; as soon as the block's origin point is out of view the entire entity stops rendering. I can only assume this is a performance thing, as is the case for other entities but it makes it a lot harder to use these entities on a larger scale without disabling Optifine first.

Please implement an option to keep them rendered.
![comparison](https://user-images.githubusercontent.com/16510735/236684201-22b08ec1-821a-48ad-ba26-88a4a478f314.gif)

**Comment by Steve982950** [comment]
YEAH MR sp614x. PLEASE ADD THIS!!!! BECAUSE THIS RUINS CRACKER'S WITHER STORM MOD!!!! ADD THIS NOOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

**Comment by Lolothepro** [comment]
> YEAH MR sp614x. PLEASE ADD THIS!!!! BECAUSE THIS RUINS CRACKER'S WITHER STORM MOD!!!! ADD THIS NOOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

STOP

**Comment by Steve982950** [comment]
> > YEAH MR sp614x. PLEASE ADD THIS!!!! BECAUSE THIS RUINS CRACKER'S WITHER STORM MOD!!!! ADD THIS NOOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
> 
> STOP

I DONT STOP, I GO! AND WHEN I LOOK AT YOU, I THROW!

**Comment by SilentWhisperer** [comment]
bruh

**Comment by MiraculixxT** [comment]
2 month later, any updates about this? 

Like jake mentioned, optifine can not be used currently in any custom map or even on some servers, because a lot is not loading.

In addition, not only on big objects it bugs out if you slightly look away. If the block display is translated it get even worse. When the translation is higher then 10, it completely stops rendering if looking directly on it. Easy example, if you create an elevator that smoothly moves up and down the block display vanishes completely:
![Image](https://discord.com/channels/423430686880301056/896862947480068137/1133017619675480149)
(Vanilla - Optifine)

**Comment by sp614x** [comment]
Vanilla has the same problem when the visible model extends in a chunk that has no blocks or other entities.

**Comment by sp614x** [comment]
Fixed, coming in next preview.

**Comment by Steve982950** [comment]
can this ''Preview'' be for 1.19.4 and up?

**Comment by Steve982950** [comment]
hoping you keep updating optifine for old versions of MC

**Comment by SilentWhisperer** [comment]
Sp sometimes updates older versions
but by the next preview he probably means it's for 1.20.1

**Comment by MiraculixxT** [comment]
It's already out and works now like vanilla (visual)
> http://optifine.net/adloadx?f=preview_OptiFine_1.20.1_HD_U_I6_pre6.jar

**Comment by Steve982950291** [comment]
is theere a version for 1.19.3
