### ISSUE TITLE
Issue following GL error convo

### ISSUE THREAD

**Issue by Pugmaster04** [sp614x/optifine#7514]
Locking issue for continued unnecessary conversation.

_Originally posted by @Jiingy in https://github.com/sp614x/optifine/issues/7507#issuecomment-1659374006_
            

Unnecessary conversation? Adding information is what you requested if I was to continue the report. I added information and you proceeded to shut me down. Shutting this one down as well will continue to prove your inability to responsibly communicate and respond to issues under your control with optifine. "Optifine issue continued to arise errors as well as crash the game whenever shaders were activated and deactivated." is a graphical error and in need of attention. As well as the game refusing to work with shaders after they were reactivated. Another graphical error that is in need of attention.

https://drive.google.com/file/d/1GhKhweF3U3K5AV3KqTVbEsgPuBDwVxZI/view?usp=drive_link
https://drive.google.com/file/d/1w2SpSwCuUHSTcD9rLmOkK402M9Oq6Bxj/view?usp=drive_link
https://drive.google.com/file/d/12o8Eq3yCv3b_0-h3u0f3TkNLBYCV2oQL/view?usp=drive_link
https://drive.google.com/file/d/1y7Yjb2mLJrgXjXQ4VLAeVgCAeiUVOiH7/view?usp=drive_link
![Screenshot 2023-07-31 210443](https://user-images.githubusercontent.com/73559998/257378789-c49ab23b-ba0c-42b2-b5a1-d0ede1999eb7.png)
![Screenshot 2023-07-31 210500](https://user-images.githubusercontent.com/73559998/257378794-ac343632-a9ac-4b6b-92b3-87e99ae8f4ea.png)

**Comment by Jiingy** [comment]
1. This, and the previous issue already duplicate #4655. If that issue needs to be updated, I will update it. If you would like to leave a comment on that one you can. It our fault for not making that clear enough that the previous issue was a duplicate, and should have been closed for that reason. 
2. As already stated, very often if not all the time error 1280 does not cause crashing. It can be correlated to the crash, but not the reason. After reading the previous post, it seems far more likely there is another underlying issue causing the crash as it happens specifically when disabling shaders.
3. The previous issue was closed for "unnecessary conversation" because two collaborators (myself, and ZenIsBestWolf) had already a: provided you a solution to the problem, b: stated that there are already issue posts with this exact issue (meaning yours was a duplicate), and c: specifically advised against continuing the conversation any further (thus, resulting in me locking the issue with the provided reason).

If you would not like to disable OpenGL errors, another possible solution is to try updating your java version, and computer driver version. Commonly these can be solutions to error 1280.

I am closing this issue, and locking it so please do not make another issue or I will disable your ability to post. Issue #4655 can be updated if necessary as yours is a duplicate. I apologize for not  being clear enough in my reasoning on the previous post, but when an issue is closed with a provided solution, please respect that.
