### ISSUE TITLE
Swamp Biome Water Color Incorrect in OptiFine 1.21

### ISSUE THREAD

**Issue by SeraphStha** [sp614x/optifine#7736]
In OptiFine version 1.21, the water color in the swamp biome appears to be the same as the regular water color, instead of the distinctive greenish, mossy hue it should have. I have confirmed that the 'Swamp Colors' setting is turned 'ON'. The grass color in the swamp biome is correctly displayed.

Tested Versions:
    OptiFine HD U J1 pre2
    OptiFine HD U J1 pre6

No additional mods (e.g., Forge, Fabric) are installed, only OptiFine.

![Normal Swamp](https://github.com/user-attachments/assets/664c831f-2f32-44f6-8ac8-d8dddf544a89)
![OptiFine Swamp](https://github.com/user-attachments/assets/d952d5d9-b2bf-4560-808b-efeed5e69ed9)

**Comment by richiemilos** [comment]
I thought I was the only one that had that happen to me.
OptiFine 1.21 HD U J1 pre8 That keeps happening
![2024-09-03_20 30 48](https://github.com/user-attachments/assets/78083743-9034-4697-8fa6-0831a28f8a4e)
I think it's a bug or error in optifine 1.21 because in previous versions you don't get that.
![2024-09-02_23 30 35](https://github.com/user-attachments/assets/bece115d-4189-48c5-9df4-b0416fdfe620)

**Comment by SeraphStha** [comment]
Tried the latest releases, OptiFine 1.21 HD U J1 pre9 and OptiFine 1.21.1 HD U J1 pre9, still encountering the same issue.

**Comment by SeaOfPixels** [comment]
Fixed in pre12.
