### ISSUE TITLE
Shaders are using a lot of CPU, losing frames

### ISSUE THREAD

**Issue by nerthexx** [sp614x/optifine#786]
When running minecraft 1.12 with shaders (any shader, even internal) minecraft starts to use a lot of CPU (30% on my i5-3470, with render distance set to 10 chunks), and there is a significant fps loss even though I have GTX 960 graphics card. For example, when I'm running Chocapic13 V6 High shader I only get around 50-60 fps with a lot of micro freezes (which is another sign of intense CPU usage). 
However, my friend has GTX 770 but stronger CPU (i7-4770K) and he's getting around 90 fps with same shader.
I was curios and downloaded original shadermod and installed it on same minecraft version (1.12). With original shadermod I was getting 110-140 fps with same shader.
As I cannot play with shadermod alone (it's not compatible with literally anything), I would like to see some optimization done to optifine. 
Thanks.

**Comment by sp614x** [comment]
This is most probably connected to the shadowmap generation.

The classic shaders mod has two problems with the shadows:
- flickering (disappearing) shadows 
- sunlight shining underground

OptiFine fixes both of them at the cost of increased CPU load. Because most shaders are GPU limited the additional CPU load is usually not problematic. In the case of fast GPU and slow CPU, the FPS difference may be significant.

The FPS difference becomes bigger on longer render distances, so decreasing the render distance may help.

OptiFine adds another shadow optimization which has no side effects, but it has to be activated and supported by the shader pack:  https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L333
