### ISSUE TITLE
Custom Sky resetting at 06:00

### ISSUE THREAD

**Issue by sp614x** [sp614x/optifine#804]
There's a weird bug with respect to Better Skies that's been bothering me for some time. With some texture packs (Pixel Atmosphere and Conquest Reforged pack being some examples), the clouds texture will "reset" at exactly noon, in-game time 6000.

Here is a gif illustrating the problem, from the Pixel Atmosphere resource pack (again, this is far from the only resource pack affected). And attached is a screenshot of the sky.properties file which seems to be the root of the problem.

https://gfycat.com/ThoroughImperturbableAfricancivet

Is anyone else noticing this? What's wrong here?

![image](https://user-images.githubusercontent.com/16635441/28801910-1e3c86fc-7654-11e7-8ee9-917fe5a69363.png)

**Comment by elwood612** [comment]
Thanks for creating this. I've done some more research, and (contrary to what appears in the image I linked, not sure how that happened) this only affects sky.properties files that have the rotation speed set to something other than an integer. So for example, this particular pack actually had the speed set to 1.19 before I changed it, and Conquest Reforged currently has it set to 1.1. Neither of these work. Misa's pack works because she has it set to 2, and the pack screenshotted above would now work (indeed, does work) with a speed of 2. 

Anyway, if this is intended behavior, then you can go ahead and close this. If there's a way to solve it though, that would be awesome. 

Thanks again.

**Comment by sp614x** [comment]
The skybox rotation is calculated for the current day, at the next day it starts from zero. If the rotation is not integer, then there will be a skip because the sky has only made a partial rotation.
Not sure why the day start for Custom Sky is at 6000.

**Comment by sp614x** [comment]
The skybox angle at the start of the day could probably be changed to depend on the number of days passed and the rotation speed.

**Comment by sp614x** [comment]
Updated preview C7 for 1.12.2
- fixed Custom Sky resetting at time 6000 when rotation speed is not an integer (#804)
