### ISSUE TITLE
Improve resource pack applying/loading

### ISSUE THREAD

**Issue by Phoenix616** [sp614x/optifine#856]
This is a plea for an optimisation of how the client applies new resource packs. From what I could gather it currently has to reload all resource packs that a user has applied in order to find overriding files and to sticht together the textures to an image like in the first texture packs.

This results in annoying client freezes that can last for up to a couple dozen seconds depending on the size of the textures (especially noticeable in HD packs) and your machine's performance. It is especially annoying when using server resource packs as you have to wait ages until the pack is applied with no protection from what is going on in the world.

This has also been brought to Mojang's attention but was dismissed as not being a bug ([MC-69644](https://bugs.mojang.com/browse/MC-69644)) so I hope that I find some more open ears here as Optifine is all about optimisation and improvements. (I would look into contributing a solution myself but there doesn't seem to be any code in this repo?)

**Comment by SetantaLP** [comment]
In general it's not a bug, because it's a probably annoying but normal behavior, so the bug-tracker is the wrong place to discuss this. A better place might be the [minecraftsuggestions-subreddit](https://www.reddit.com/r/minecraftsuggestions/).

It's an interesting idea, but I think it might be quite difficult to realize:
- it will only work if you enable additional resourcepacks, but it means that you have to know which rps were enabled before (which should be easy to detect) and you might have issues if one of the enable rp's has been removed from the rp-folder or has been modified/replaced.
- the texture-atlas and especially the model-registry are a quite difficult place, because models might depend on other models and the final registry which is returned by the setup-method only knows the fully baked model, no json-data or dependencies (that is only stored inside the ModelBakery). So if you want to be able to just replace a model, it is required, that you know which other block/item-model uses this model, which means, if you (re)load the resources you have to build a dependency tree for the models, and if you replace one, you have to update this tree, identify and remove all models that are no longer needed (to avoid memory leaks) and rebake all models that depend on this model, so that the visible result of this action is exactly the same as when you reload the whole resource-manager.
And besides that, you have to update all the maps where the model is referenced, which is error-prone and would require a lot of work, because the ModelBakery is not designed for having the ability to replace specific models (it's simply replaced with a new instance if the resource-manager is reloaded). And it's also not possible to simply replace a texture inside a TextureAtlasSprite because there is a lot of data that has to be updated, but if you create a new TextureAtlasSprite you have to update all baked models that use this specific instance.
And not to forget, if the rp includes a lang-file, for the language that is currently used, and/or sound-files you also have to reload the language- and/or sound-manager.

Let's summ up what is necessary to achieve the same result as by simply reloading the resource-manager:
1. on first start/on reload: build a dependency-tree for the models (has to be implemented)
2. check if any loaded rp has changed (because in the current system this is done indirectly by just reloading all rp's, has to be implemented)
3. check which models, textures, blockstates, sounds, lang-files are affected by the new rp (has to be implemented).
4. update the affected texture-sprite-objects in the TextureMap (has to be implemented) or find out where the object is referenced and replace it (requires a dependency-tree/usage-map, has to be implemented) and create new ones for newly registered textures.
5. update the changed and affected models and blockstates (impossible in the current system, completely new ModelBakery required).
6. reload language- and/or sound-manager if necessary (already implemented).

So I think the reason for simply reloading the whole resource-manager is, that it's much easier to implement (and already used in many cases), much easier to maintain and much less error-prone, because you simply do the same as when the game starts and you don't have to deal with a lot of special cases.

**Comment by sp614x** [comment]
Detecting what has changed between the old and the new resource pack(s) is practically impossible.
There are many dependancies that are very hard to track. Even if this were made to work for vanilla it would definitely be incompatible with Forge and all the mods that use custom texture and model loaders.

The solution for server resource packs would be for the server to wait for the client to load the resource pack before spawning the player in the world. This would be a vanilla bugfix, not for OptiFine.

**Comment by Phoenix616** [comment]
Well detecting which parts of the resource packs changed was an example for a perfect solution of the problem, I bet there are other ways of improving the applying of a resource pack e.g. by running the reloading in a separate thread as mentioned by /u/61352151511 on /r/minecraftsuggestionst.

**Comment by SetantaLP** [comment]
The main problem is, that the whole resource manager (and anything that relies on the it) is exactly build for the current procedure. So if you modify the procedure, it's quite sure that something will break.

Reloading the RPs in a separate thread would be also a tricky thing because reloading means unload the old data and then load the new data, so if you want to flip the procedure you have to load the new data into a new resource manager (which needs additional ram), then replace the old resource-manager and then update the render-engine, which also means "rebuild all render-chunks". And that means that all chunks would suddenly disappear and then reappear with the new resources, which might cause problems for the player depending on the situation. Or you replace the render-chunks one after another, but that will cause a mixture of old and new which might look strange and will be difficult to manage because if the players moves you also have to load new chunks and unload old ones. But no matter how you do it, it would be more difficult to handle than the current procedure, because in the current procedure you only have one resource manager at a time, so the garbage-collector can run quite easy after unloading the data if ram is limited (which is normal for slower machines) and you can easily rebuild all render-chunks, because the player can't do anything while reloading the RP's. So the current procedure might not be the best in some situations, but it is used since a long time and in all situations where rp's are (re)loaded.

And one example: Let's say you have a normal computer and you have an hd-resourcepack loaded. Now you join a server that uses a server-rp, that only adds some custom items (for optifines cit-feature). In the current procedure that means, you'll have to wait some seconds until everything is ready (which also means that the garbage-collector has started if necessary). In the other procedure you won't have to wait, but the client will load the whole hd-resourcepack a second time (so the memory usage will be increased constantly, and maybe the garbage collector starts multiple times because the ram-usage crosses a certain threshold, which cause the game to freeze for some seconds). After finishing, the client will switch the resource managers, unload the old data and rebuild the render-chunks, which probably causes the garbage-collector to start, because the ram-usage crosses a certain threshold, so the game freezes for some seconds. So I'm not sure if this would be really better than the current procedure.

**Comment by sp614x** [comment]
Loading the resources in a second thread is not possible as it modifies a lot of OpenGL resources (textures, display lists, etc) and this can only happen on the main thread. OpenGL is not multi-threaded friendly.
