### ISSUE TITLE
Crash on clicking play with optifine 1.12.2 HD U C5.

### ISSUE THREAD

**Issue by makiharukawa** [sp614x/optifine#960]
When I try to play minecraft on 1.12.2 with the most recently released launcher (2.0.995) it crashes when i click the button. This is not the launcher's error, as without optifine it starts up fine. Is it not compatible with this new version of the launcher or something? kinda frustrated. I dont know where to find the crash log in this edition but this is what i found in the launcher_log.txt file : https://pastebin.com/PcU3gWnz

**Comment by rawdr** [comment]
Same had just happened to me... but launcher 2.0.1003 and optifine HD_U_C6. 

So I reinstalled Optifine, this caused the launcher to update itself again when I opened Minecraft, so I thought it was going to crash again but no... it opened successfully this time.

**Comment by UserAnimated** [comment]
https://twitter.com/Dinnerbone/status/923204144948752384

**Comment by sp614x** [comment]
This is a launcher problem, not related to OptiFine. It affects all custom configurations including Forge.
https://www.reddit.com/r/Minecraft/comments/78psjj/psa_linux_users_mc_even_without_mods_may_not_be/
https://www.reddit.com/r/Minecraft/comments/78o2y6/minecraft_forge_crashes_as_soon_as_i_hit_play_on/
https://www.reddit.com/r/Minecraft/comments/78of9s/modded_game_crashes_are_now_fixed_with_launcher/

The problem seems to be fixed already for most platforms.
