### ISSUE TITLE
[Suggestion] 'Custom block textures' (CIT for blocks)

### ISSUE THREAD

**Issue by LavaSnakeGaming** [sp614x/optifine#968]
Hello there, I always wanted Custom Item Textures for blocks. So for an example if I rename a stone block "Green block" when I place it down it turns into a green stone block. But I'm pretty sure this will not be possible because items have NBT for names, but most blocks do not (if I'm not mistaking) but just wanted to ask anyways. Thanks

 -- LavaSnakeGaming

**Comment by SetantaLP** [comment]
As you said it's currently impossible. But something similar (using unused sub-ids for new blocks) was possible before 1.8 (and removed in 1.8 due to the introduction of block states and block-models) and depending on how exactly the new id-system handles nbt-data on blocks, it might be possible to implement in 1.13. So I would say, let's wait for 1.13 and then talk about the idea again.

**Comment by sp614x** [comment]
Block don't have names or NBT tags. They have only ID and metadata (0-16). This is done to keep the memory usage down, because a normal world has A LOT of blocks.
In 1.8 the metadata was replaced with block states and since 1.8 it is not possible to use the free metadata values for custom block textures.
Most probably 1.13 is going to remove the block IDs so there would be only block names and block states left. This would not make it easier to add custom blocks.

**Comment by PolySaken-I-Am** [comment]
How about reviving this since blockdata is a thing

**Comment by xalixilax** [comment]
i might be late for that, but what abour barrel? We can rename them and they keep their name when placed and destroyed.

**Comment by SetantaLP** [comment]
@xalixilax I assume they work exactly the same way as chests, which means (if you play on a multiplayer server) on chunk load you only get the info that there is a barrel at a certain location (which is enough for the vanilla-client to render it). And when you click the barrel the server sends (based on the data that is stored inside the BlockEntity associated with the clicked barrel) a packet that tells your client to open a chest-gui (with a certain amount of slots and a specific name (which can be a custom one, if there is a corresponding entry in inside the BlockEntity)) and a packet with the item stacks to display.
By the way, this is basically the same problem as in #2595.
