### ISSUE TITLE
CTM does not work correctly with multiple resource packs

### ISSUE THREAD

**Issue by Luke18033** [sp614x/optifine#985]
When a resource pack that does not support CTM for default blocks (such as glass) is used on its own, the non-connecting texture from the pack will be used instead of the default CTM version. However, this is not the case with multiple resource packs - the connected textures from the lower pack will be used instead. These are the packs I currently have selected:
![image](https://user-images.githubusercontent.com/19228201/32670522-df23f4b0-c5f8-11e7-9c94-1ff72d3264ae.png)
Better Than Default adds custom connected textures for several blocks including quartz, iron and gold. ApertureCraftPack, which is placed above Better Than Default, also contains custom textures for these which don't support CTM, and shouldn't.

Since ApertureCraft is higher on the resource pack list, its non-connecting textures should be used. However, the Better Than Default CTM textures continue to be used as long as the option is enabled.

Tested on 1.12, I'm not sure if this still happens in 1.12.2. Also note that although both of these packs are downloadable online, they're very outdated. These are personal versions of the packs which I've been updating myself and adding my own textures to, including the Better Than Default CTM which it did not have originally.

**Comment by MisterQuiggly** [comment]
Since it's in a selected pack, its CTM features will be used. As an example, if you have a dirt block in the Better Than Default pack with no CTM on it, and you have a dirt block in the AperatureCraftPack with no CTM, then the AperatureCraftPack dirt will show up because it has a texture in the same location with the same name (in this case dirt) that it will use instead of the one from the pack below it. If Better Than Default has a CTM glass texture, and AperatureCraftPack doesn't, there is nothing to use instead of it that replaces it. The CTM will take priority if there is no CTM for that block in the pack above it. I believe this is intended and I am very glad it is, as I use it.

**Comment by Luke18033** [comment]
In that case, shouldn't it behave the same way with the default resource pack? If a resource pack adds a custom glass/bookshelf/sandstone texture that does not include CTM support, it's used instead of the default connecting texture even when CTM is on. This is the behavior I was also expecting for multiple packs. ApertureCraft includes quartz/iron/gold textures without CTM support, which should be used instead of the connecting texture even with CTM on. If this is indeed intended, it should also behave this way with default CTM textures.

> I believe this is intended and I am very glad it is, as I use it.

In that case, it may be a good idea to add an option for this, like "Higher Packs Override CTM" or something. When off, the current behavior would be used and connecting textures from lower packs would override non-connecting textures from higher packs. When on, textures from higher packs which do not have CTM support would be used instead of the lower ones that do.

**Comment by MisterQuiggly** [comment]
It would and does behave the same way with the default pack, but the default pack does not have any CTM in which to take priority over the blocks in the higher resourcepacks. If one of the two resourcepacks is missing a texture, then the default one will be used.

**Comment by Luke18033** [comment]
> the default pack does not have any CTM in which to take priority over the blocks in the higher resourcepacks.

Yes it does? Glass, sandstone and bookshelves connect by default. Last time I checked, if a resource pack includes custom textures for those blocks which don't have CTM support they'll override the default connecting textures.

**Comment by MisterQuiggly** [comment]
>  Glass, sandstone and bookshelves connect by default.
This isn't in the default pack. This is added by optifine and is found in the files for the optifine mod. It is just applied to the default pack. If another pack is applied, then it is not going to use it even if it does or does not have ctm for that item.

**Comment by sp614x** [comment]
The default OptiFine CTM configuration (glass, sandstone, etc) is deactivated when a resource pack adds a non-standard texture for one of the blocks. This is needed because the default configuration is always included and there is no other way to turn it OFF.
Normal resource packs don't have this restriction. They can be stacked on top of each other and they can mix their CTM textures as needed.
The user is free to remove the CTM folder from one pack to avoid it conflicting with another pack.

**Comment by Luke18033** [comment]
Okay, decided to come back to this. This is how the texture priority currently is:
```
Pack 1 CTM
Pack 2 CTM
Pack 1
Pack 2
Default CTM
Default
```
However, I would expect it to either be:
```
Pack 1 CTM
Pack 1
Pack 2 CTM
Pack 2
Default CTM
Default
```
Or:
```
Pack 1 CTM
Pack 2 CTM
Default CTM
Pack 1
Pack 2
Default
```
While I can see why the current behavior would be intended, it's pretty confusing for people who haven't specifically looked into it this much (i.e. myself two years ago). I've always thought of CTM as an extension of an existing texture, not something entirely separate. With this in mind, it would make the most sense that a standard texture in a higher pack should override CTM in a lower pack. Either way, the behavior should at least be made consistent between the standard connected textures and those added by resource packs.
